<script setup lang="ts">
import { computed, ref } from 'vue'
import type { AppLocale } from '../../../types/ml.ts'
import type { LogisticPublishedInteractionAsset } from '../types.ts'
import { buildCalibrationLimitsSceneModel, sceneNumber } from './sceneModels.ts'

const props=defineProps<{asset:LogisticPublishedInteractionAsset;locale:AppLocale}>()
const mode=ref<'original'|'sharpened'|'softened'>('original');const view=ref<'banknote'|'xor'|'circles'>('banknote')
const model=computed(()=>buildCalibrationLimitsSceneModel(props.asset as LogisticPublishedInteractionAsset & {sceneId:'linear-limits'},mode.value,mode.value,view.value))
const copy=computed(()=>props.locale==='zh-CN'?{title:'校准与一条直线的边界',mode:'概率模式',view:'观察视图',banknote:'Banknote 验证集',xor:'合成 XOR',circles:'合成同心圆',reset:'重置',table:'校准或几何数据表',read:'Banknote 校准与合成容量诊断严格分离；合成点不能改变真实数据模型。',synthetic:'合成诊断：未用于 Banknote 拟合或模型选择。',accuracy:'固定 0.5 阈值准确率'}:{title:'Calibration and the limit of one line',mode:'Probability mode',view:'Inspection view',banknote:'Banknote validation',xor:'Synthetic XOR',circles:'Synthetic circles',reset:'Reset',table:'Calibration or geometry table',read:'Banknote calibration and synthetic capacity diagnostics remain strictly separate; synthetic points cannot alter the real-data model.',synthetic:'Synthetic diagnostic: never used for Banknote fitting or model selection.',accuracy:'Fixed 0.5 threshold accuracy'})
const options=computed(()=>props.asset.controls[0]?.options??[])
function reset(){mode.value='original';view.value='banknote'}
function onKey(event:KeyboardEvent){if(event.key==='ArrowLeft')view.value=view.value==='circles'?'xor':view.value==='xor'?'banknote':'banknote';if(event.key==='ArrowRight')view.value=view.value==='banknote'?'xor':view.value==='xor'?'circles':'circles';if(event.key==='r')reset()}
function px(value:number){return 35+((value+1.5)/3)*270}
function binX(boundary:number){return 42+boundary*280}
function binWidth(lower:number,upper:number){return Math.max(1,binX(upper)-binX(lower)-3)}
</script>

<template>
  <section class="logistic-scene" tabindex="0" :aria-label="copy.title" @keydown="onKey"><header><p>pᵀ = σ(z / T)</p><h4>{{ copy.title }}</h4><p class="logistic-scene__read">{{ copy.read }}</p></header><div class="logistic-scene__controls" role="group" :aria-label="copy.title"><label>{{ copy.mode }}<select v-model="mode"><option v-for="option in options" :key="String(option.value)" :value="String(option.value)">{{ option.label[props.locale] }}</option></select></label><fieldset><legend>{{ copy.view }}</legend><label><input v-model="view" type="radio" value="banknote"/>{{copy.banknote}}</label><label><input v-model="view" type="radio" value="xor"/>{{copy.xor}}</label><label><input v-model="view" type="radio" value="circles"/>{{copy.circles}}</label></fieldset><button type="button" @click="reset">{{ copy.reset }}</button></div><p v-if="view!=='banknote'" class="logistic-scene__warning" role="status">{{ copy.synthetic }}</p><svg v-if="view==='banknote'" class="logistic-scene__svg" viewBox="0 0 360 200" role="img" :aria-label="`${copy.banknote}: ${mode}`"><title>{{ copy.banknote }}</title><line x1="32" y1="170" x2="335" y2="170" class="axis"/><g v-for="bin in model.bins" :key="`${bin.lower}-${bin.upper}`"><rect :x="binX(bin.lower)" :y="165-Math.min(120,(bin.meanProbability??0)*125)" :width="binWidth(bin.lower,bin.upper)" :height="Math.min(120,(bin.meanProbability??0)*125)" :class="bin.count===0?'predicted empty-bin':'predicted'"/><path v-if="bin.observedRate!==null" :d="`M ${binX((bin.lower+bin.upper)/2)-6} ${165-Math.min(120,bin.observedRate*125)} l 6 -8 l 6 8`" class="observed" fill="none"/><text :x="binX((bin.lower+bin.upper)/2)" y="188" text-anchor="middle">{{ sceneNumber(bin.lower,1) }}</text><text v-if="bin.count===0" :x="binX((bin.lower+bin.upper)/2)" y="158" text-anchor="middle">∅</text></g><text x="30" y="20">ECE = {{ sceneNumber(model.expectedCalibrationError,8) }}</text><text x="30" y="40">{{ copy.accuracy }} = {{ (model.accuracy*100).toFixed(2) }}%</text><text x="30" y="60">bars = mean probability · caret = observed rate · ∅ = empty bin</text></svg><svg v-else class="logistic-scene__svg" viewBox="0 0 360 200" role="img" :aria-label="model.dataKind"><title>{{ model.dataKind }}</title><line x1="25" y1="100" x2="335" y2="100" class="axis"/><line x1="180" y1="20" x2="180" y2="180" class="axis dashed"/><circle v-for="point in model.points" :key="point.label" :cx="px(point.x)" :cy="170-((point.y+1.5)/3)*140" r="4" :class="point.kind" :aria-label="point.label"><title>{{ point.label }}</title></circle><text x="24" y="20">{{ model.dataKind }}</text><text x="24" y="40">solid circle = class 1 · striped circle = class 0</text></svg><table class="logistic-scene__table"><caption>{{ copy.table }}</caption><thead><tr><th>Field</th><th>Value</th></tr></thead><tbody><tr v-for="item in model.table" :key="item.label"><th scope="row">{{ item.label }}</th><td>{{ item.value }}</td></tr></tbody></table></section>
</template>

<style scoped>
@import './scene.css';.axis{stroke:#475569;stroke-width:1.5}.dashed{stroke-dasharray:4 3}.predicted{fill:#2563eb;stroke:#172033;stroke-width:1}.empty-bin{fill:#e2e8f0;stroke-dasharray:3 2}.observed{stroke:#b45309;stroke-width:3}.class-one{fill:#0f766e;stroke:#172033;stroke-width:1.5}.class-zero{fill:#fff;stroke:#b45309;stroke-width:2;stroke-dasharray:3 2}.logistic-scene__svg text{font-size:9px;fill:#172033}.logistic-scene__warning{padding:.6rem;background:#fff7ed;border-left:4px solid #b45309}.logistic-scene fieldset{display:flex;gap:.4rem;flex-wrap:wrap;border:1px solid #94a3b8;border-radius:.5rem}.logistic-scene fieldset label{display:flex;font-weight:400}
</style>
