<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { dataLabModules } from '../data/modules'
import type { DataLabLocale, DataLabProgress } from '../types/dataLab'
import { loadDataLabProgress } from '../utils/progress'

const { locale } = useI18n()
const progress = ref<DataLabProgress>(loadDataLabProgress())
const currentLocale = computed(() => locale.value as DataLabLocale)

const copy = computed(() =>
  currentLocale.value === 'zh-CN'
    ? {
        eyebrow: 'Data Lab',
        title: '数据实验室',
        subtitle:
          '从原始表格出发，学习怎样判断列语义、清洗数据、编码类别、划分数据集，并把这些步骤变成可训练、可复查的机器学习输入。',
        start: '开始数值数据',
        continue: '继续学习',
        path: '学习路径',
        pathTitle: '五章建立数据到泛化的完整主线',
        note:
          '每一章先讲概念，再解释为什么重要，最后用浏览器实验和 pandas 代码把表格变化、特征向量变化、评估风险连起来。',
        runtime: '运行方式',
        runtimeTitle: '本地浏览器实验 + pandas 对照',
        runtimeNote:
          '交互结果由确定性 TypeScript 函数生成，适合课堂演示；pandas 代码作为真实工程写法，便于学生带到 notebook 练习。',
      }
    : {
        eyebrow: 'Data Lab',
        title: 'Data Lab',
        subtitle:
          'Start with raw tables and learn how column semantics, cleaning, encoding, splitting, and diagnostics become trainable machine-learning inputs.',
        start: 'Start numerical data',
        continue: 'Continue learning',
        path: 'Learning path',
        pathTitle: 'Five chapters from data to generalization',
        note:
          'Each chapter defines the idea, explains why it matters, then connects table changes, feature-vector changes, and evaluation risk through browser labs and pandas code.',
        runtime: 'Runtime',
        runtimeTitle: 'In-browser labs + pandas code',
        runtimeNote:
          'Interactive outputs are generated by deterministic TypeScript functions; pandas code provides the engineering equivalent for notebooks and classroom use.',
      },
)

const continueRoute = computed(() => {
  const preferred = progress.value.lastVisitedModuleId ?? dataLabModules[0]?.id ?? 'numerical-data'
  return `/data-lab/modules/${preferred}`
})
</script>

<template>
  <div class="data-lab-page">
    <section class="data-lab-hero">
      <div class="data-lab-hero__copy">
        <span class="eyebrow">{{ copy.eyebrow }}</span>
        <h1>{{ copy.title }}</h1>
        <p>{{ copy.subtitle }}</p>
        <div class="hero__actions">
          <router-link class="action-button action-button--primary" to="/data-lab/modules/numerical-data">
            {{ copy.start }}
          </router-link>
          <router-link class="action-button" :to="continueRoute">
            {{ copy.continue }}
          </router-link>
          <router-link class="action-button" to="/math-lab">
            Math Lab
          </router-link>
        </div>
      </div>

      <div class="data-lab-hero__visual" aria-hidden="true">
        <div class="data-lab-table-plane">
          <span v-for="column in ['vector', 'encode', 'quality', 'split', 'curve']" :key="column">{{ column }}</span>
        </div>
      </div>
    </section>

    <section class="data-lab-dashboard">
      <article class="data-lab-panel">
        <header class="section-header">
          <span class="eyebrow">{{ copy.path }}</span>
          <h2>{{ copy.pathTitle }}</h2>
          <p>{{ copy.note }}</p>
        </header>

        <div class="data-lab-path">
          <router-link
            v-for="moduleDefinition in dataLabModules"
            :key="moduleDefinition.id"
            class="data-lab-path__node"
            :class="{ 'is-complete': progress.completedModuleIds.includes(moduleDefinition.id) }"
            :to="`/data-lab/modules/${moduleDefinition.id}`"
            :style="{ '--data-accent': moduleDefinition.accent, '--data-theme': moduleDefinition.theme }"
          >
            <span>{{ currentLocale === 'zh-CN' ? `第 ${moduleDefinition.order} 章` : `Chapter ${moduleDefinition.order}` }}</span>
            <strong>{{ moduleDefinition.title[currentLocale] }}</strong>
            <p>{{ moduleDefinition.subtitle[currentLocale] }}</p>
            <small>
              {{
                progress.completedModuleIds.includes(moduleDefinition.id)
                  ? currentLocale === 'zh-CN'
                    ? '已完成'
                    : 'Completed'
                  : currentLocale === 'zh-CN'
                    ? '打开章节'
                    : 'Open chapter'
              }}
            </small>
          </router-link>
        </div>
      </article>

      <aside class="data-lab-panel data-lab-panel--compact">
        <span>{{ copy.runtime }}</span>
        <strong>{{ copy.runtimeTitle }}</strong>
        <p>{{ copy.runtimeNote }}</p>
      </aside>
    </section>
  </div>
</template>
