import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync, statSync } from 'node:fs'
import {
  buildCnnHyperparameterSnapshot,
  calculateReceptiveField,
  calculateCnnOutputSize,
  calculateConvCell,
  calculateMaxPoolCell,
  softmaxScores,
  summarizeLayerShape,
  type CnnLayerSnapshot,
  tinyVggClassLabels,
} from '../src/utils/cnnExplainer.ts'

const root = new URL('../', import.meta.url)

function read(path: string) {
  return readFileSync(new URL(path, root), 'utf8')
}

test('CNN explainer pure math computes convolution, pooling, softmax, and summaries', () => {
  const conv = calculateConvCell(
    [
      [
        [1, 2],
        [3, 4],
      ],
      [
        [2, 1],
        [0, -1],
      ],
    ],
    [
      [
        [1, 0],
        [0, 1],
      ],
      [
        [0.5, 0.5],
        [1, 0],
      ],
    ],
    0.25,
    0,
    0,
  )

  assert.equal(conv.channelContributions?.length, 2)
  assert.equal(conv.channelContributions?.[0]?.sum, 5)
  assert.equal(conv.channelContributions?.[1]?.sum, 1.5)
  assert.equal(conv.weightedSum, 6.75)

  const pooled = calculateMaxPoolCell(
    [
      [1, 3, 2],
      [4, 2, 8],
      [0, 5, 9],
    ],
    0,
    0,
  )

  assert.equal(pooled.poolMax, 4)
  assert.deepEqual(pooled.poolMaxPosition, { row: 1, col: 0 })

  const softmax = softmaxScores([1000, 1001, 999])
  assert.equal(Math.abs(softmax.probabilities.reduce((sum, value) => sum + value, 0) - 1) < 1e-12, true)
  assert.equal(softmax.probabilities[1]! > softmax.probabilities[0]!, true)

  const summary = summarizeLayerShape({
    kind: 'conv',
    outputShape: [32, 32, 16],
    parameterCount: 448,
    nodes: Array.from({ length: 16 }) as never[],
  })
  assert.equal(summary, 'conv: 32x32x16, 16 nodes, 448 params')

  assert.equal(calculateCnnOutputSize(5, 3, 1, 1), 5)
  assert.equal(calculateCnnOutputSize(5, 2, 2, 0), 2)

  const hyperparameterSnapshot = buildCnnHyperparameterSnapshot({
    inputSize: 5,
    padding: 1,
    kernelSize: 3,
    stride: 2,
    selectedRow: 2,
    selectedCol: 1,
  })
  assert.equal(hyperparameterSnapshot.paddedSize, 7)
  assert.equal(hyperparameterSnapshot.outputSize, 3)
  assert.equal(hyperparameterSnapshot.strideFits, true)
  assert.equal(hyperparameterSnapshot.selectedStartRow, 4)
  assert.equal(hyperparameterSnapshot.selectedStartCol, 2)
  assert.equal(hyperparameterSnapshot.inputCells.length, 49)
  assert.equal(hyperparameterSnapshot.kernelCells.length, 9)
  assert.equal(hyperparameterSnapshot.outputCells.length, 9)
  assert.equal(hyperparameterSnapshot.inputCells.find((cell) => cell.row === 0 && cell.col === 0)?.isPadding, true)
  assert.equal(hyperparameterSnapshot.inputCells.find((cell) => cell.row === 4 && cell.col === 2)?.isKernel, true)
  assert.equal(hyperparameterSnapshot.outputCells.find((cell) => cell.row === 2 && cell.col === 1)?.isSelected, true)
  assert.equal(buildCnnHyperparameterSnapshot({ inputSize: 5, padding: 0, kernelSize: 2, stride: 2 }).strideFits, false)
})

test('CNN receptive field tracing maps selected activations back to input pixels', () => {
  const inputOutput = Array.from({ length: 5 }, (_rowValue, row) => Array.from({ length: 5 }, (_colValue, col) => row * 5 + col))
  const convOutput = Array.from({ length: 3 }, (_rowValue, row) => Array.from({ length: 3 }, (_colValue, col) => row * 3 + col))
  const layers: CnnLayerSnapshot[] = [
    {
      id: 'input',
      name: 'input',
      index: 0,
      kind: 'input',
      inputShape: [5, 5, 1],
      outputShape: [5, 5, 1],
      parameterCount: 0,
      nodes: [
        {
          id: 'input-0',
          layerName: 'input',
          layerIndex: 0,
          index: 0,
          kind: 'input',
          output: inputOutput,
          bias: 0,
          inputLinks: [],
          outputLinks: [],
        },
      ],
    },
    {
      id: 'conv',
      name: 'conv',
      index: 1,
      kind: 'conv',
      inputShape: [5, 5, 1],
      outputShape: [3, 3, 1],
      parameterCount: 10,
      nodes: [
        {
          id: 'conv-0',
          layerName: 'conv',
          layerIndex: 1,
          index: 0,
          kind: 'conv',
          output: convOutput,
          bias: 0,
          inputLinks: [
            {
              sourceLayerIndex: 0,
              sourceNodeIndex: 0,
              targetLayerIndex: 1,
              targetNodeIndex: 0,
              weight: [
                [1, 1, 1],
                [1, 1, 1],
                [1, 1, 1],
              ],
            },
          ],
          outputLinks: [],
        },
      ],
    },
    {
      id: 'relu',
      name: 'relu',
      index: 2,
      kind: 'relu',
      inputShape: [3, 3, 1],
      outputShape: [3, 3, 1],
      parameterCount: 0,
      nodes: [
        {
          id: 'relu-0',
          layerName: 'relu',
          layerIndex: 2,
          index: 0,
          kind: 'relu',
          output: convOutput,
          bias: 0,
          inputLinks: [{ sourceLayerIndex: 1, sourceNodeIndex: 0, targetLayerIndex: 2, targetNodeIndex: 0 }],
          outputLinks: [],
        },
      ],
    },
    {
      id: 'pool',
      name: 'pool',
      index: 3,
      kind: 'pool',
      inputShape: [3, 3, 1],
      outputShape: [1, 1, 1],
      parameterCount: 0,
      nodes: [
        {
          id: 'pool-0',
          layerName: 'pool',
          layerIndex: 3,
          index: 0,
          kind: 'pool',
          output: [[8]],
          bias: 0,
          inputLinks: [{ sourceLayerIndex: 2, sourceNodeIndex: 0, targetLayerIndex: 3, targetNodeIndex: 0 }],
          outputLinks: [],
        },
      ],
    },
    {
      id: 'flatten',
      name: 'flatten',
      index: 4,
      kind: 'flatten',
      inputShape: [1, 1, 1],
      outputShape: [1],
      parameterCount: 0,
      nodes: [
        {
          id: 'flatten-0',
          layerName: 'flatten',
          layerIndex: 4,
          index: 0,
          kind: 'flatten',
          output: 8,
          bias: 0,
          realIndex: 0,
          inputLinks: [
            {
              sourceLayerIndex: 3,
              sourceNodeIndex: 0,
              targetLayerIndex: 4,
              targetNodeIndex: 0,
              sourcePosition: { row: 0, col: 0 },
            },
          ],
          outputLinks: [],
        },
      ],
    },
    {
      id: 'dense',
      name: 'output',
      index: 5,
      kind: 'dense',
      inputShape: [1],
      outputShape: [1],
      parameterCount: 2,
      nodes: [
        {
          id: 'dense-0',
          layerName: 'output',
          layerIndex: 5,
          index: 0,
          kind: 'dense',
          output: 16,
          bias: 0,
          logit: 16,
          inputLinks: [{ sourceLayerIndex: 4, sourceNodeIndex: 0, targetLayerIndex: 5, targetNodeIndex: 0, weight: 2 }],
          outputLinks: [],
        },
      ],
    },
  ]

  const convField = calculateReceptiveField(layers, 1, 0, 1, 1)
  assert.deepEqual(convField?.bounds, { rowStart: 1, rowEnd: 4, colStart: 1, colEnd: 4, rowSpan: 3, colSpan: 3 })
  assert.deepEqual(convField?.channels, [0])
  assert.equal(convField?.sourceCellCount, 9)

  const poolField = calculateReceptiveField(layers, 3, 0, 0, 0)
  assert.deepEqual(poolField?.bounds, { rowStart: 0, rowEnd: 4, colStart: 0, colEnd: 4, rowSpan: 4, colSpan: 4 })
  assert.equal(poolField?.sourceCellCount, 16)

  const denseField = calculateReceptiveField(layers, 5, 0, 0, 0, { denseSourceIndex: 0 })
  assert.equal(denseField?.selectedDenseSourceIndex, 0)
  assert.equal(denseField?.sourceVectorIndex, 0)
  assert.equal(denseField?.sourceMapIndex, 0)
  assert.deepEqual(denseField?.bounds, poolField?.bounds)
})

test('CNN explainer Tiny VGG assets, labels, and provenance are local and documented', () => {
  const modelPath = new URL('public/cnn-explainer/tiny-vgg/model.json', root)
  const weightsPath = new URL('public/cnn-explainer/tiny-vgg/group1-shard1of1.bin', root)
  const licensePath = new URL('public/cnn-explainer/tiny-vgg/LICENSE', root)
  const samplePaths = [
    'lifeboat.png',
    'ladybug.png',
    'pizza.png',
    'bell-pepper.png',
    'school-bus.png',
    'koala.png',
    'espresso.png',
    'red-panda.png',
    'orange.png',
    'sport-car.png',
  ]
  const docsSource = read('docs/cnn-explainer-assets.md')
  const referenceSource = read('docs/ml-atlas-references.md')

  assert.ok(existsSync(modelPath))
  assert.ok(existsSync(weightsPath))
  assert.ok(existsSync(licensePath))
  assert.equal(statSync(weightsPath).size > 70_000, true)
  for (const samplePath of samplePaths) {
    const sampleUrl = new URL(`public/cnn-explainer/samples/${samplePath}`, root)
    const sampleBytes = readFileSync(sampleUrl)
    assert.ok(existsSync(sampleUrl))
    assert.equal(sampleBytes[0], 0x89)
    assert.equal(sampleBytes.toString('ascii', 1, 4), 'PNG')
    assert.equal(statSync(sampleUrl).size > 20_000, true)
    assert.match(docsSource, new RegExp(samplePath.replace('.', '\\.')))
  }

  const model = JSON.parse(read('public/cnn-explainer/tiny-vgg/model.json'))
  assert.equal(model.format, 'layers-model')
  assert.equal(model.modelTopology.model_config.config.layers.length, 12)
  assert.equal(model.weightsManifest[0].paths.includes('group1-shard1of1.bin'), true)

  assert.deepEqual([...tinyVggClassLabels], [
    'lifeboat',
    'ladybug',
    'pizza',
    'bell pepper',
    'school bus',
    'koala',
    'espresso',
    'red panda',
    'orange',
    'sport car',
  ])

  assert.match(docsSource, /d0971f9447ed9806022a3d47587b62394682bc51/)
  assert.match(docsSource, /MIT/)
  assert.match(docsSource, /sample JPEG images were not migrated/)
  assert.match(docsSource, /built-in `imagegen` workflow/)
  assert.match(docsSource, /project-generated PNG samples/)
  assert.match(referenceSource, /REF-CNN-EXPLAINER/)
})

test('CNN explainer lab is browser-local, lazy, and wired only into the CNN route', () => {
  const packageSource = read('package.json')
  const utilitySource = read('src/utils/cnnExplainer.ts')
  const componentSource = read('src/components/CnnExplainerLab.vue')
  const algorithmViewSource = read('src/views/AlgorithmView.vue')
  const routerSource = read('src/router/index.ts')
  const moduleSource = read('src/data/cnnVisualizationModule.ts')
  const stylesheetSource = read('src/styles/modules/cnn-explainer.css')
  const reluMatricesStyle = stylesheetSource.match(/\.cnn-relu-detail__matrices\s*\{[^}]+\}/)?.[0] ?? ''

  assert.match(packageSource, /"@tensorflow\/tfjs": "\^4\.22\.0"/)
  assert.match(utilitySource, /await import\('@tensorflow\/tfjs'\)/)
  assert.match(utilitySource, /withPublicBase\(tinyVggModelPath\)/)
  assert.doesNotMatch(utilitySource, /for \(const tensor of weights\) tensor\.dispose\(\)/)
  assert.match(utilitySource, /interface CnnReceptiveFieldSnapshot/)
  assert.match(utilitySource, /calculateReceptiveField/)
  assert.match(utilitySource, /traceReceptiveField/)
  assert.match(utilitySource, /strongestDenseInputIndex/)
  assert.match(componentSource, /accept="image\/png,image\/jpeg,image\/webp"/)
  assert.match(componentSource, /maxUploadBytes = 5 \* 1024 \* 1024/)
  assert.match(componentSource, /URL\.createObjectURL/)
  assert.match(componentSource, /URL\.revokeObjectURL/)
  assert.match(componentSource, /prefers-reduced-motion/)
  assert.match(componentSource, /MarkdownMathContent/)
  assert.match(componentSource, /type CnnScaleMode = 'local' \| 'module' \| 'global'/)
  assert.match(componentSource, /mapPanelTitle/)
  assert.match(componentSource, /selectedKernelChannels/)
  assert.match(componentSource, /denseWeightPreview/)
  assert.match(componentSource, /interface CnnDenseLedgerItem/)
  assert.match(componentSource, /interface CnnDenseWaterfallStep/)
  assert.match(componentSource, /interface CnnDenseWaterfall/)
  assert.match(componentSource, /interface CnnDenseSourceLocator/)
  assert.match(componentSource, /interface CnnDenseContributionAtlasCell/)
  assert.match(componentSource, /interface CnnDenseContributionAtlasMap/)
  assert.match(componentSource, /denseContributionTerms/)
  assert.match(componentSource, /denseLedgerItems = computed<CnnDenseLedgerItem/)
  assert.match(componentSource, /denseWaterfall = computed<CnnDenseWaterfall \| undefined>/)
  assert.match(componentSource, /denseContributorLocator = computed<CnnDenseSourceLocator \| undefined>/)
  assert.match(componentSource, /denseContributionAtlasAllMaps = computed<CnnDenseContributionAtlasMap\[]>/)
  assert.match(componentSource, /denseContributionAtlasMaps/)
  assert.match(componentSource, /denseContributionAtlasMapCount = 6/)
  assert.match(componentSource, /activeDenseSourceIndex/)
  assert.match(componentSource, /focusedDenseSourceIndex/)
  assert.match(componentSource, /denseWaterfallContributionCount = 6/)
  assert.match(componentSource, /denseLedgerEquation/)
  assert.match(componentSource, /denseLedgerHiddenCount/)
  assert.match(componentSource, /logitPreviewRows/)
  assert.match(componentSource, /selectDenseWeightSource/)
  assert.match(componentSource, /interface CnnLayerInspector/)
  assert.match(componentSource, /interface CnnLayerFunctionGuide/)
  assert.match(componentSource, /type CnnFormulaTraceTarget/)
  assert.match(componentSource, /interface CnnFormulaTraceTerm/)
  assert.match(componentSource, /layerFunctionGuide = computed<CnnLayerFunctionGuide \| undefined>/)
  assert.match(componentSource, /formulaTraceTerms = computed<CnnFormulaTraceTerm\[]>/)
  assert.match(componentSource, /layerFunctionEyebrow: '层功能说明'/)
  assert.match(componentSource, /layerFunctionEyebrow: 'Layer function'/)
  assert.match(componentSource, /layerFunctionOpenChapter: '打开对应章节'/)
  assert.match(componentSource, /layerFunctionOpenChapter: 'Open chapter'/)
  assert.match(componentSource, /formulaTrace: '公式变量映射'/)
  assert.match(componentSource, /formulaTrace: 'Formula variable map'/)
  assert.match(componentSource, /'channels-feature-maps'/)
  assert.match(componentSource, /'pooling-classifier-head'/)
  assert.match(componentSource, /route: `\/learn\/cnn-visualization\/\$\{guide\.chapterId\}`/)
  assert.match(componentSource, /layerInspector/)
  assert.match(componentSource, /layerRoleDescription/)
  assert.match(componentSource, /layerParameterFormula/)
  assert.match(componentSource, /connectionSummaries/)
  assert.match(componentSource, /selectConnectionNode/)
  assert.match(componentSource, /kernelSizeForNode/)
  assert.match(componentSource, /buildCnnHyperparameterSnapshot/)
  assert.match(componentSource, /hyperInputSize/)
  assert.match(componentSource, /hyperPadding/)
  assert.match(componentSource, /hyperKernelSize/)
  assert.match(componentSource, /hyperStride/)
  assert.match(componentSource, /hyperOutputSize/)
  assert.match(componentSource, /hyperFormulaMarkdown/)
  assert.match(componentSource, /hyperWindowNarration/)
  assert.match(componentSource, /selectHyperOutputCell/)
  assert.match(componentSource, /clampHyperparameterControls/)
  assert.match(componentSource, /class="cnn-hyperparameter-lab"/)
  assert.match(componentSource, /class="cnn-hyperparameter-lab__controls"/)
  assert.match(componentSource, /class="cnn-hyper-grid cnn-hyper-grid--input"/)
  assert.match(componentSource, /class="cnn-hyper-grid cnn-hyper-grid--kernel"/)
  assert.match(componentSource, /class="cnn-hyper-grid cnn-hyper-grid--output"/)
  assert.match(componentSource, /@mouseenter="selectHyperOutputCell\(cell\.row, cell\.col\)"/)
  assert.match(componentSource, /copy\.hyperparameterLab/)
  assert.match(componentSource, /copy\.shapeLayerNote/)
  assert.match(componentSource, /copy\.hoverOutputCell/)
  assert.match(componentSource, /interface CnnConvMathFocus/)
  assert.match(componentSource, /interface CnnConvAnimatorAnchor/)
  assert.match(componentSource, /interface CnnConvAnimatorDetail/)
  assert.match(componentSource, /focusedConvMathTerm/)
  assert.match(componentSource, /activeConvContribution/)
  assert.match(componentSource, /convAnimatorAnchor/)
  assert.match(componentSource, /convAnimatorWindowCenter/)
  assert.match(componentSource, /convAnimatorDetail/)
  assert.match(componentSource, /convMathNarration/)
  assert.match(componentSource, /focusConvMathCell/)
  assert.match(componentSource, /focusConvAnimatorMathCell/)
  assert.match(componentSource, /pinConvAnimatorWindow/)
  assert.match(componentSource, /clearConvAnimatorWindowAnchor/)
  assert.match(componentSource, /clearConvAnimatorWindowAnchorIfFocusLeaves/)
  assert.match(componentSource, /selectConvInputMatrixCell/)
  assert.match(componentSource, /selectConvOutputMatrixCell/)
  assert.match(componentSource, /convInputWindowAround/)
  assert.match(componentSource, /isFocusedConvMathCell/)
  assert.match(componentSource, /highlightedSoftmaxIndex/)
  assert.match(componentSource, /activeSoftmaxIndex/)
  assert.match(componentSource, /activeSoftmaxRow/)
  assert.match(componentSource, /interface CnnSoftmaxCompetitionRow extends CnnSoftmaxContributionRow/)
  assert.match(componentSource, /softmaxCompetitionRows = computed<CnnSoftmaxCompetitionRow/)
  assert.match(componentSource, /logitGapFromTop/)
  assert.match(componentSource, /probabilityGapFromTop/)
  assert.match(componentSource, /focusSoftmaxClass/)
  assert.match(componentSource, /focusSoftmaxCompetitionRow\(row\)/)
  assert.match(componentSource, /selectSoftmaxCompetitionRow\(row\)/)
  assert.match(componentSource, /clearSoftmaxFocus/)
  assert.match(componentSource, /focusScore/)
  assert.match(componentSource, /isScoreHighlighted/)
  assert.match(componentSource, /is-softmax-highlighted/)
  assert.match(componentSource, /is-highlighted': score\.highlighted/)
  assert.match(componentSource, /copy\.softmaxCompetition/)
  assert.match(componentSource, /softmaxRankingTitle: '类别竞争排名'/)
  assert.match(componentSource, /softmaxTopGap: '距 top logit'/)
  assert.match(componentSource, /probabilityMass: '概率质量'/)
  assert.match(componentSource, /copy\.hoverLogitTerm/)
  assert.match(componentSource, /colorForLogitValue/)
  assert.match(componentSource, /denseWeightBarWidth/)
  assert.match(componentSource, /focusDenseLedgerItem/)
  assert.match(componentSource, /focusDenseWaterfallStep\(step\)/)
  assert.match(componentSource, /class="cnn-dense-ledger"/)
  assert.match(componentSource, /class="cnn-dense-ledger__items"/)
  assert.match(componentSource, /class="cnn-dense-waterfall"/)
  assert.match(componentSource, /class="cnn-dense-waterfall__steps"/)
  assert.match(componentSource, /class="cnn-dense-waterfall__bar"/)
  assert.match(componentSource, /class="cnn-dense-waterfall__scale"/)
  assert.match(componentSource, /:style="\{ '--axis-left': denseWaterfall\.axisPosition \}"/)
  assert.match(componentSource, /:style="step\.barStyle"/)
  assert.match(componentSource, /:style="step\.markerStyle"/)
  assert.match(componentSource, /copy\.denseLedgerTitle/)
  assert.match(componentSource, /copy\.denseLedgerHint/)
  assert.match(componentSource, /copy\.denseWaterfallTitle/)
  assert.match(componentSource, /copy\.denseWaterfallHint/)
  assert.match(componentSource, /copy\.denseContributionAtlasTitle/)
  assert.match(componentSource, /copy\.denseContributionAtlasHint/)
  assert.match(componentSource, /copy\.netContribution/)
  assert.match(componentSource, /copy\.absoluteContribution/)
  assert.match(componentSource, /copy\.denseSourceLocatorTitle/)
  assert.match(componentSource, /copy\.denseSourceLocatorHint/)
  assert.match(componentSource, /copy\.sourceFeatureCell/)
  assert.match(componentSource, /copy\.selectedContribution/)
  assert.match(componentSource, /copy\.value\.denseRemainingTerms/)
  assert.match(componentSource, /copy\.value\.runningSum/)
  assert.match(componentSource, /copy\.value\.denseBiasTerm/)
  assert.match(componentSource, /copy\.value\.denseLogitTerm/)
  assert.match(componentSource, /@mouseenter="focusDenseLedgerItem\(item\)"/)
  assert.match(componentSource, /@mouseenter="focusDenseWaterfallStep\(step\)"/)
  assert.match(componentSource, /@mouseenter="focusDenseAtlasCell\(map, cell\)"/)
  assert.match(componentSource, /class="cnn-dense-contribution-atlas"/)
  assert.match(componentSource, /class="cnn-dense-contribution-atlas__grid"/)
  assert.match(componentSource, /colorForDenseContributionValue\(cell\.contribution, map\.maxMagnitude\)/)
  assert.match(componentSource, /selectDenseAtlasCell\(cell\)/)
  assert.match(componentSource, /class="cnn-dense-source-locator"/)
  assert.match(componentSource, /class="cnn-dense-source-locator__grid"/)
  assert.match(componentSource, /matrixWindowAround\(sourceMatrix, sourceRow, sourceCol, 2, sourceRow, sourceCol\)/)
  assert.match(componentSource, /selectDenseWeightSource\(denseContributorLocator\.sourceIndex\)/)
  assert.match(componentSource, /clearDenseSourceFocus/)
  assert.match(componentSource, /colorMode === 'weights' && selectedKernelChannels\.length/)
  assert.match(componentSource, /colorMode === 'weights' && denseWeightPreview\.length/)
  assert.match(componentSource, /colorMode === 'logits'/)
  assert.match(componentSource, /copy\.value\.kernelBank/)
  assert.match(componentSource, /copy\.value\.denseWeightMap/)
  assert.match(componentSource, /copy\.value\.logitMap/)
  assert.match(componentSource, /interface CnnInputChannelPreview/)
  assert.match(componentSource, /interface CnnInputPixelPreview/)
  assert.match(componentSource, /inputDataView: '输入数据视图'/)
  assert.match(componentSource, /rgbChannels: 'RGB 三通道'/)
  assert.match(componentSource, /inputChannelPreviews = computed<CnnInputChannelPreview/)
  assert.match(componentSource, /selectedInputPixel = computed<CnnInputPixelPreview/)
  assert.match(componentSource, /sampleMatrixWithSelected\(matrix, 10, 10, row, col\)/)
  assert.match(componentSource, /function sampleMatrixWithSelected\(matrix: number\[\]\[\]/)
  assert.match(componentSource, /type CnnReceptiveFieldSnapshot/)
  assert.match(componentSource, /receptiveField = computed<CnnReceptiveFieldSnapshot \| undefined>/)
  assert.match(componentSource, /calculateReceptiveField\(layers\.value/)
  assert.match(componentSource, /receptiveFieldOverlayStyle/)
  assert.match(componentSource, /receptiveFieldRegionLabel/)
  assert.match(componentSource, /receptiveFieldNarration/)
  assert.match(componentSource, /class="cnn-input-preview"/)
  assert.match(componentSource, /class="cnn-input-preview__receptive-field"/)
  assert.match(componentSource, /class="cnn-receptive-field"/)
  assert.match(componentSource, /class="cnn-receptive-field__chips"/)
  assert.match(componentSource, /receptiveField: '输入感受野'/)
  assert.match(componentSource, /receptiveField: 'Input receptive field'/)
  assert.match(componentSource, /inputChannelLabel\(channelIndex/)
  assert.match(componentSource, /normalizedToRawPixel\(value/)
  assert.match(componentSource, /colorForInputChannelValue\(value/)
  assert.match(componentSource, /interface CnnInputPreprocessStep/)
  assert.match(componentSource, /inputPreprocessSteps = computed<CnnInputPreprocessStep\[]>/)
  assert.match(componentSource, /focusInputPreprocessStep\(step: CnnInputPreprocessStep\)/)
  assert.match(componentSource, /inputPreprocessTitle: '浏览器输入预处理'/)
  assert.match(componentSource, /inputPreprocessTitle: 'Browser input preprocessing'/)
  assert.match(componentSource, /inputPreprocessCrop: '中心裁剪'/)
  assert.match(componentSource, /inputPreprocessResize: '缩放成 tensor'/)
  assert.match(componentSource, /inputPreprocessNormalize: '像素归一化'/)
  assert.match(componentSource, /class="cnn-input-preprocess"/)
  assert.match(componentSource, /class="cnn-input-preprocess__step"/)
  assert.match(componentSource, /class="cnn-input-preprocess__crop-frame"/)
  assert.match(componentSource, /class="cnn-input-preprocess__tensor-grid"/)
  assert.match(componentSource, /focusInputChannelCellReadout\(preview, cell\)/)
  assert.match(componentSource, /class="cnn-input-data-view"/)
  assert.match(componentSource, /class="cnn-input-data-view__channels"/)
  assert.match(componentSource, /class="cnn-input-data-view__grid"/)
  assert.match(componentSource, /class="cnn-input-data-view__pixel"/)
  assert.match(componentSource, /copy\.inputDataHint/)
  assert.match(componentSource, /copy\.centerCropResize/)
  assert.match(componentSource, /interface CnnReluMaskCell extends CnnMatrixCell/)
  assert.match(componentSource, /interface CnnReluMaskSummary/)
  assert.match(componentSource, /reluMaskSummary = computed<CnnReluMaskSummary/)
  assert.match(componentSource, /reluMaskTitle: 'ReLU 截断 mask'/)
  assert.match(componentSource, /reluClippedRatio: '截断比例'/)
  assert.match(componentSource, /focusReluMaskCell\(cell\)/)
  assert.match(componentSource, /class="cnn-relu-mask-panel"/)
  assert.match(componentSource, /class="cnn-relu-mask-panel__metrics"/)
  assert.match(componentSource, /class="cnn-relu-mask-panel__grid"/)
  assert.match(componentSource, /interface CnnPipelineStep/)
  assert.match(componentSource, /interface CnnForwardStoryStep/)
  assert.match(componentSource, /pipelineSteps/)
  assert.match(componentSource, /pipelineProgress/)
  assert.match(componentSource, /currentPipelineLabel/)
  assert.match(componentSource, /forwardStorySteps = computed<CnnForwardStoryStep\[]>/)
  assert.match(componentSource, /currentForwardStoryStep/)
  assert.match(componentSource, /selectPipelineStep/)
  assert.match(componentSource, /selectForwardStoryStep\(step: CnnForwardStoryStep\)/)
  assert.match(componentSource, /focusForwardStoryStep\(step: CnnForwardStoryStep\)/)
  assert.match(componentSource, /forwardStoryNode\(layer: CnnLayerSnapshot\)/)
  assert.match(componentSource, /forwardStoryValue\(layer: CnnLayerSnapshot, node: CnnNodeSnapshot\)/)
  assert.match(componentSource, /class="cnn-pipeline-rail"/)
  assert.match(componentSource, /class="cnn-pipeline-rail__step"/)
  assert.match(componentSource, /class="cnn-forward-storyboard"/)
  assert.match(componentSource, /class="cnn-forward-storyboard__step"/)
  assert.match(componentSource, /:aria-current="step\.state === 'current' \? 'step' : undefined"/)
  assert.match(componentSource, /copy\.pipeline/)
  assert.match(componentSource, /copy\.currentStage/)
  assert.match(componentSource, /forwardStoryboard: '传播讲解时间线'/)
  assert.match(componentSource, /forwardStoryboard: 'Forward-pass teaching timeline'/)
  assert.match(componentSource, /forwardStoryboardHint: '播放或单步时/)
  assert.match(componentSource, /cnn-sample-strip/)
  assert.match(componentSource, /interface CnnSampleClassCard extends CnnSampleImage/)
  assert.match(componentSource, /isPending: boolean/)
  assert.match(componentSource, /pendingImageName = ref\(''\)/)
  assert.match(componentSource, /let inferenceRequestId = 0/)
  assert.match(componentSource, /const requestId = \+\+inferenceRequestId/)
  assert.match(componentSource, /if \(requestId !== inferenceRequestId\) return/)
  assert.match(componentSource, /pendingImageName\.value = imageName/)
  assert.match(componentSource, /pendingImageName\.value = ''/)
  assert.match(componentSource, /sampleClassCards = computed<CnnSampleClassCard/)
  assert.match(componentSource, /isPending: sample\.label === pendingImageName\.value/)
  assert.match(componentSource, /selectedSamplePredictionMatches/)
  assert.match(componentSource, /selectedSampleScore/)
  assert.match(componentSource, /classGallery: '类别图库'/)
  assert.match(componentSource, /expectedClass: '目标类别'/)
  assert.match(componentSource, /predictedClass: '预测类别'/)
  assert.match(componentSource, /samplePredictionMatch: '当前 top-1 与样例标签一致'/)
  assert.match(componentSource, /sampleClassAriaLabel\(sample\)/)
  assert.match(componentSource, /focusSampleClassCard\(sample\)/)
  assert.match(componentSource, /:aria-label="sampleClassAriaLabel\(sample\)"/)
  assert.match(componentSource, /function scorePanelAriaLabel\(score: CnnClassScore\)/)
  assert.match(componentSource, /:aria-label="scorePanelAriaLabel\(score\)"/)
  assert.match(componentSource, /sampleInferenceLoading: '正在推理'/)
  assert.match(componentSource, /sampleInferenceLoading: 'Running inference'/)
  assert.match(componentSource, /'is-pending': sample\.isPending/)
  assert.match(componentSource, /:disabled="sample\.isPending"/)
  assert.match(componentSource, /class="cnn-score-panel__match"/)
  assert.match(componentSource, /preloadedSampleDefinitions/)
  assert.match(componentSource, /withPublicBase\(sample\.path\)/)
  assert.match(componentSource, /\/cnn-explainer\/samples\/lifeboat\.png/)
  assert.doesNotMatch(componentSource, /\/cnn-explainer\/samples\/[a-z-]+\.svg/)
  assert.match(componentSource, /loading="eager" decoding="async"/)
  assert.doesNotMatch(componentSource, /function createSampleImage\(/)
  assert.match(componentSource, /overviewCells\(layer, node\)/)
  assert.match(componentSource, /overviewNodeTransform\(layer, nodeDisplayIndex, visibleNodes\(layer\)\.length\)/)
  assert.match(componentSource, /overviewStackPlates\(layer, nodeDisplayIndex\)/)
  assert.match(componentSource, /overviewLayerTrackPath\(layer\)/)
  assert.match(componentSource, /overviewNodeAnchor/)
  assert.match(componentSource, /interface CnnOverviewFlowPacket/)
  assert.match(componentSource, /overviewFlowPackets = computed<CnnOverviewFlowPacket/)
  assert.match(componentSource, /interface CnnOverviewLocalWindow/)
  assert.match(componentSource, /overviewLocalWindows\(layer, node\)/)
  assert.match(componentSource, /overviewSourceWindow/)
  assert.match(componentSource, /overviewOutputWindow/)
  assert.match(componentSource, /overviewWindowBox/)
  assert.match(componentSource, /interface CnnOverviewWindowFocus/)
  assert.match(componentSource, /focusedOverviewWindow/)
  assert.match(componentSource, /activeOverviewWindow/)
  assert.match(componentSource, /interface CnnOverviewNodeFocus/)
  assert.match(componentSource, /focusedOverviewNode = ref<CnnOverviewNodeFocus \| undefined>/)
  assert.match(componentSource, /overviewNodeFromFocus\(focus: CnnOverviewNodeFocus\)/)
  assert.match(componentSource, /activeOverviewNodeFocus = computed<CnnOverviewNodeFocus>/)
  assert.match(componentSource, /activeOverviewNodeKey/)
  assert.match(componentSource, /activeOverviewNode = computed/)
  assert.match(componentSource, /interface CnnOverviewTraceStep/)
  assert.match(componentSource, /interface CnnOverviewTraceSummary/)
  assert.match(componentSource, /overviewTraceLinks = computed/)
  assert.match(componentSource, /overviewTraceNodeKeys = computed/)
  assert.match(componentSource, /overviewTraceBackwardEdgeKeys = computed/)
  assert.match(componentSource, /overviewTraceForwardEdgeKeys = computed/)
  assert.match(componentSource, /overviewTraceSummary = computed<CnnOverviewTraceSummary \| undefined>/)
  assert.match(componentSource, /preferredTraceInputLink\(node: CnnNodeSnapshot, focus: CnnOverviewNodeFocus\)/)
  assert.match(componentSource, /preferredTraceOutputLink\(node: CnnNodeSnapshot, focus: CnnOverviewNodeFocus\)/)
  assert.match(componentSource, /strongestLink\(links: CnnLinkSnapshot\[\], direction: 'input' \| 'output'\)/)
  assert.match(componentSource, /preferredLayerIndexForSection/)
  assert.match(componentSource, /preferredNodeIndexForSection/)
  assert.match(componentSource, /sectionId === 'pooling-classifier-head'/)
  assert.match(componentSource, /sectionId === 'transfer-learning-review'/)
  assert.match(componentSource, /scores\.value\.findIndex\(\(score\) => score\.id === topPrediction\.value\?\.id\)/)
  assert.match(componentSource, /overviewEdgeKey\(link\.sourceLayerIndex/)
  assert.match(componentSource, /isTraceOverviewNode\(layer: CnnLayerSnapshot, node: CnnNodeSnapshot\)/)
  assert.match(componentSource, /overviewTraceStepToneLabel\(tone: CnnOverviewTraceStep\['tone'\]\)/)
  assert.match(componentSource, /focusOverviewTraceStep\(step: CnnOverviewTraceStep\)/)
  assert.match(componentSource, /selectOverviewTraceStep\(step: CnnOverviewTraceStep\)/)
  assert.match(componentSource, /overviewInteractionHint/)
  assert.match(componentSource, /focusOverviewWindow/)
  assert.match(componentSource, /commitOverviewWindow/)
  assert.match(componentSource, /overviewWindowTitle/)
  assert.match(componentSource, /overviewWindowDescription/)
  assert.match(componentSource, /overviewWindowAriaLabel/)
  assert.match(componentSource, /isFocusedOverviewWindow/)
  assert.match(componentSource, /interface CnnOverviewLens/)
  assert.match(componentSource, /overviewLens = computed<CnnOverviewLens/)
  assert.match(componentSource, /overviewLens: '概览镜头'/)
  assert.match(componentSource, /overviewLens: 'Overview lens'/)
  assert.match(componentSource, /overviewTraceTitle: '主路径追踪'/)
  assert.match(componentSource, /overviewTraceTitle: 'Main path trace'/)
  assert.match(componentSource, /inputTrace: '输入侧'/)
  assert.match(componentSource, /outputTrace: '输出侧'/)
  assert.match(componentSource, /currentTrace: '当前焦点'/)
  assert.match(componentSource, /expandLayer: '展开层节点'/)
  assert.match(componentSource, /expandLayer: 'Expand layer nodes'/)
  assert.match(componentSource, /collapseLayer: '收起层节点'/)
  assert.match(componentSource, /collapseLayer: 'Collapse layer nodes'/)
  assert.match(componentSource, /hiddenFeatureMaps: '隐藏 feature maps'/)
  assert.match(componentSource, /hiddenFeatureMaps: 'hidden feature maps'/)
  assert.match(componentSource, /overviewExpandHint: '点击 \+N 查看这一层更多 feature maps/)
  assert.match(componentSource, /overviewExpandHint: 'Click \+N to reveal more feature maps/)
  assert.match(componentSource, /intermediateLayerView: '中间层展开视图'/)
  assert.match(componentSource, /intermediateLayerView: 'Intermediate layer view'/)
  assert.match(componentSource, /stripHint: '这条展开带把当前层的 feature maps 横向铺开/)
  assert.match(componentSource, /stripHint: 'This strip lays out feature maps from the current layer/)
  assert.match(componentSource, /graphFocus: '当前图节点'/)
  assert.match(componentSource, /graphFocus: 'Current graph node'/)
  assert.match(componentSource, /featureMaps: '特征图'/)
  assert.match(componentSource, /channels: '通道'/)
  assert.match(componentSource, /classes: '类别'/)
  assert.match(componentSource, /downsample: '下采样'/)
  assert.match(componentSource, /overviewLayerRecipe\(layer/)
  assert.match(componentSource, /overviewLayerParameterLabel\(layer/)
  assert.match(componentSource, /overviewLayerAriaLabel\(layer/)
  assert.match(componentSource, /Math\.max\(1320, layers\.value\.length \* 118 \+ 190\)/)
  assert.match(componentSource, /return 72 \+ index \* 118/)
  assert.match(componentSource, /const top = 82/)
  assert.match(componentSource, /const bottom = 242/)
  assert.match(componentSource, /expandedOverviewLayerIndex = ref<number \| undefined>\(\)/)
  assert.match(componentSource, /const overviewCollapsedNodeCount = 10/)
  assert.match(componentSource, /const overviewExpandedNodeCount = 18/)
  assert.match(componentSource, /const overviewFlattenCollapsedNodeCount = 12/)
  assert.match(componentSource, /const overviewFlattenExpandedNodeCount = 24/)
  assert.match(componentSource, /overviewCollapsedVisibleLimit\(layer: CnnLayerSnapshot\)/)
  assert.match(componentSource, /overviewExpandedVisibleLimit\(layer: CnnLayerSnapshot\)/)
  assert.match(componentSource, /overviewVisibleLimit\(layer: CnnLayerSnapshot\)/)
  assert.match(componentSource, /isOverviewLayerExpanded\(layer: CnnLayerSnapshot\)/)
  assert.match(componentSource, /overviewCollapsedHiddenNodeCount\(layer: CnnLayerSnapshot\)/)
  assert.match(componentSource, /overviewHasExpandableNodes\(layer: CnnLayerSnapshot\)/)
  assert.match(componentSource, /overviewLayerExpansionTitle\(layer: CnnLayerSnapshot\)/)
  assert.match(componentSource, /overviewLayerExpansionGlyph\(layer: CnnLayerSnapshot\)/)
  assert.match(componentSource, /overviewLayerExpansionAriaLabel\(layer: CnnLayerSnapshot\)/)
  assert.match(componentSource, /focusOverviewLayerExpansion\(layer: CnnLayerSnapshot\)/)
  assert.match(componentSource, /toggleOverviewLayerExpansion\(layer: CnnLayerSnapshot\)/)
  assert.match(componentSource, /interface CnnOverviewLayerStripItem/)
  assert.match(componentSource, /interface CnnOverviewLayerStrip/)
  assert.match(componentSource, /const overviewLayerStripNodeCount = 48/)
  assert.match(componentSource, /overviewLayerStrip = computed<CnnOverviewLayerStrip \| undefined>/)
  assert.match(componentSource, /overviewLayerStripDescription\(startIndex/)
  assert.match(componentSource, /overviewLayerStripNodeLabel\(layer/)
  assert.match(componentSource, /overviewLayerStripNodeValue\(layer/)
  assert.match(componentSource, /overviewLayerStripNodeValueLabel\(layer/)
  assert.match(componentSource, /overviewLayerStripCellStyle\(node/)
  assert.match(componentSource, /overviewLayerStripCellLabel = computed/)
  assert.match(componentSource, /overviewLayerStripProgressStyle = computed/)
  assert.match(componentSource, /overviewLayerStripItemAriaLabel\(item/)
  assert.match(componentSource, /focusOverviewLayerStripItem\(item/)
  assert.match(componentSource, /selectOverviewLayerStripItem\(item/)
  assert.match(componentSource, /expandedOverviewLayerIndex\.value = undefined/)
  assert.match(componentSource, /return layer\.nodes\.slice\(0, Math\.min\(layer\.nodes\.length, overviewVisibleLimit\(layer\)\)\)/)
  assert.match(componentSource, /:width="svgWidth" height="318"/)
  assert.match(componentSource, /<title>{{ overviewLayerAriaLabel\(layer\) }}<\/title>/)
  assert.match(componentSource, /class="cnn-overview__recipe"/)
  assert.match(componentSource, /class="cnn-overview__params"/)
  assert.match(componentSource, /overviewLayerRecipe\(layer\)/)
  assert.match(componentSource, /overviewLayerParameterLabel\(layer\)/)
  assert.match(componentSource, /class="cnn-overview__tile-depth"/)
  assert.match(componentSource, /class="cnn-overview__layer-track"/)
  assert.match(componentSource, /class="cnn-overview__flow-packets"/)
  assert.match(componentSource, /class="cnn-overview__flow-packet"/)
  assert.match(componentSource, /'is-trace-backward': edge\.traceBackward/)
  assert.match(componentSource, /'is-trace-forward': edge\.traceForward/)
  assert.match(componentSource, /'is-trace': isTraceOverviewNode\(layer, node\)/)
  assert.match(componentSource, /<animateMotion/)
  assert.match(componentSource, /v-if="!reducedMotion"/)
  assert.match(componentSource, /:cx="reducedMotion \? packet\.x : 0"/)
  assert.match(componentSource, /overviewThumbnailCache = new Map<string, string>/)
  assert.match(componentSource, /overviewThumbnailHref/)
  assert.match(componentSource, /renderOverviewThumbnailPng/)
  assert.match(componentSource, /context\.createImageData/)
  assert.match(componentSource, /canvas\.toDataURL\('image\/png'\)/)
  assert.match(componentSource, /overviewThumbnailCache\.clear\(\)/)
  assert.match(componentSource, /class="cnn-overview__tile-image"/)
  assert.match(componentSource, /preserveAspectRatio="none"/)
  assert.match(componentSource, /:href="overviewThumbnailHref\(layer, node\)"/)
  assert.match(componentSource, /id="cnn-overview-gradient"/)
  assert.match(componentSource, /v-for="stop in overviewColorLegend\.stops"/)
  assert.match(componentSource, /class="cnn-overview__legend-ramp"/)
  assert.match(componentSource, /class="cnn-overview__legend-marker"/)
  assert.match(componentSource, /class="cnn-overview__legend-tick"/)
  assert.match(componentSource, /class="cnn-overview__legend-current"/)
  assert.match(componentSource, /overviewColorLegend\.minLabel/)
  assert.match(componentSource, /overviewColorLegend\.midLabel/)
  assert.match(componentSource, /overviewColorLegend\.maxLabel/)
  assert.doesNotMatch(componentSource, /fill="#b2182b"/)
  assert.match(componentSource, /denseOverviewBarWidth/)
  assert.match(componentSource, /denseOverviewProbability\(node\)/)
  assert.match(componentSource, /denseOverviewBarWidthValue\(node\)/)
  assert.match(componentSource, /denseOverviewProbabilityLabel\(node\)/)
  assert.match(componentSource, /isTopOverviewScore\(node\)/)
  assert.match(componentSource, /denseLabelPadding = layer\.kind === 'dense' && side === 'out' \? 112 : 0/)
  assert.match(componentSource, /'is-top-output': layer\.kind === 'dense' && isTopOverviewScore\(node\)/)
  assert.match(componentSource, /class="cnn-overview__dense-score"/)
  assert.match(componentSource, /class="cnn-overview__dense-rail"/)
  assert.match(componentSource, /class="cnn-overview__dense-bar"/)
  assert.match(componentSource, /class="cnn-overview__dense-prob"/)
  assert.match(componentSource, /class="cnn-overview__tile-cell"/)
  assert.match(componentSource, /class="cnn-overview__local-window"/)
  assert.match(componentSource, /class="cnn-overview__more"/)
  assert.match(componentSource, /v-if="overviewHasExpandableNodes\(layer\)"/)
  assert.match(componentSource, /:class="\{ 'is-expanded': isOverviewLayerExpanded\(layer\) \}"/)
  assert.match(componentSource, /:aria-label="overviewLayerExpansionAriaLabel\(layer\)"/)
  assert.match(componentSource, /@mouseenter="focusOverviewLayerExpansion\(layer\)"/)
  assert.match(componentSource, /@click="toggleOverviewLayerExpansion\(layer\)"/)
  assert.match(componentSource, /@keydown\.enter\.prevent="toggleOverviewLayerExpansion\(layer\)"/)
  assert.match(componentSource, /overviewLayerExpansionGlyph\(layer\)/)
  assert.match(componentSource, /class="cnn-overview-trace"/)
  assert.match(componentSource, /class="cnn-overview-trace__counts"/)
  assert.match(componentSource, /class="cnn-overview-trace__steps"/)
  assert.match(componentSource, /class="cnn-overview-trace__step"/)
  assert.match(componentSource, /overviewTraceSummary\.steps/)
  assert.match(componentSource, /overviewTraceStepToneLabel\(step\.tone\)/)
  assert.match(componentSource, /@mouseenter="focusOverviewTraceStep\(step\)"/)
  assert.match(componentSource, /@click="selectOverviewTraceStep\(step\)"/)
  assert.match(componentSource, /class="cnn-overview-strip"/)
  assert.match(componentSource, /v-if="overviewLayerStrip"/)
  assert.match(componentSource, /class="cnn-overview-strip__meta"/)
  assert.match(componentSource, /class="cnn-overview-strip__items"/)
  assert.match(componentSource, /class="cnn-overview-strip__item"/)
  assert.match(componentSource, /'has-cell-marker': item\.cellStyle/)
  assert.match(componentSource, /class="cnn-overview-strip__media"/)
  assert.match(componentSource, /class="cnn-overview-strip__scan-progress"/)
  assert.match(componentSource, /class="cnn-overview-strip__cell-marker"/)
  assert.match(componentSource, /:style="overviewLayerStripProgressStyle"/)
  assert.match(componentSource, /:style="item\.cellStyle"/)
  assert.match(componentSource, /overviewThumbnailHref\(overviewLayerStrip\.layer, item\.node\)/)
  assert.match(componentSource, /@mouseenter="focusOverviewLayerStripItem\(item, overviewLayerStrip\.layer\)"/)
  assert.match(componentSource, /@click="selectOverviewLayerStripItem\(item, overviewLayerStrip\.layer\)"/)
  assert.match(componentSource, /role="button"/)
  assert.match(componentSource, /focusable="true"/)
  assert.match(componentSource, /:aria-label="overviewWindowAriaLabel\(window\)"/)
  assert.match(componentSource, /@click\.stop="commitOverviewWindow\(window\)"/)
  assert.match(componentSource, /<title>{{ overviewWindowTitle\(window\) }}<\/title>/)
  assert.match(componentSource, /class="cnn-overview-lens"/)
  assert.match(componentSource, /class="cnn-overview-node-lens"/)
  assert.match(componentSource, /class="cnn-overview-node-lens__flow"/)
  assert.match(componentSource, /class="cnn-overview-node-lens__facts"/)
  assert.match(componentSource, /class="cnn-overview-node-lens__connections"/)
  assert.match(componentSource, /copy\.feedsThisNode/)
  assert.match(componentSource, /copy\.passesToNext/)
  assert.match(componentSource, /copy\.focusPosition/)
  assert.match(componentSource, /overviewLens\.incoming/)
  assert.match(componentSource, /overviewLens\.outgoing/)
  assert.match(componentSource, /@click="selectConnectionNode\(connection\)"/)
  assert.match(componentSource, /interface CnnConvIntermediateCard/)
  assert.match(componentSource, /convIntermediateCards = computed<CnnConvIntermediateCard/)
  assert.match(componentSource, /convIntermediateStack: '输入通道中间结果'/)
  assert.match(componentSource, /convIntermediateStack: 'Input-channel intermediate results'/)
  assert.match(componentSource, /focusConvIntermediateCard/)
  assert.match(componentSource, /class="cnn-conv-intermediate-stack"/)
  assert.match(componentSource, /class="cnn-conv-intermediate-stack__cards"/)
  assert.match(componentSource, /class="cnn-conv-intermediate-stack__equation"/)
  assert.match(componentSource, /class="cnn-conv-intermediate-stack__mini-grid"/)
  assert.match(componentSource, /card\.patch/)
  assert.match(componentSource, /card\.kernel/)
  assert.match(componentSource, /card\.products/)
  assert.match(componentSource, /card\.formattedSum/)
  assert.match(componentSource, /interface CnnDetailScanCell/)
  assert.match(componentSource, /detailScanRows = computed<CnnDetailScanCell\[\]\[\]/)
  assert.match(componentSource, /layer\.kind === 'input'/)
  assert.match(componentSource, /scanMap: '扫描网格'/)
  assert.match(componentSource, /scanMap: 'Scan grid'/)
  assert.match(componentSource, /scanPathHint/)
  assert.match(componentSource, /focusDetailScanCell/)
  assert.match(componentSource, /setDetailStep\(cell\.stepIndex\)/)
  assert.match(componentSource, /class="cnn-detail-scan-map"/)
  assert.match(componentSource, /class="cnn-detail-scan-map__legend"/)
  assert.match(componentSource, /class="cnn-detail-scan-map__grid"/)
  assert.match(componentSource, /scanGridStyle\(detailScanRows\)/)
  assert.match(componentSource, /@mouseenter="focusDetailScanCell\(cell\)"/)
  assert.match(componentSource, /interface CnnPropagationBridge/)
  assert.match(componentSource, /interface CnnPropagationChip/)
  assert.match(componentSource, /propagationBridge = computed<CnnPropagationBridge/)
  assert.match(componentSource, /copy\.propagationBridge/)
  assert.match(componentSource, /copy\.operatorLabel/)
  assert.match(componentSource, /class="cnn-propagation-bridge"/)
  assert.match(componentSource, /class="cnn-propagation-bridge__flow"/)
  assert.match(componentSource, /class="cnn-propagation-bridge__formula"/)
  assert.match(componentSource, /class="cnn-propagation-bridge__chips"/)
  assert.match(componentSource, /<MarkdownMathContent :source="propagationBridge\.formulaMarkdown" \/>/)
  assert.match(componentSource, /patch × kernel \+ bias/)
  assert.match(componentSource, /dense logits → softmax/)
  assert.match(componentSource, /class="cnn-layer-inspector"/)
  assert.match(componentSource, /class="cnn-layer-inspector__metrics"/)
  assert.match(componentSource, /class="cnn-layer-inspector__formula"/)
  assert.match(componentSource, /class="cnn-layer-inspector__connections"/)
  assert.match(componentSource, /@click="selectConnectionNode\(connection\)"/)
  assert.match(componentSource, /\(k_h×k_w×C_in \+ bias\)×C_out/)
  assert.match(componentSource, /copy\.layerInspector/)
  assert.match(componentSource, /copy\.incomingConnections/)
  assert.match(componentSource, /buildScaleRanges/)
  assert.match(componentSource, /cnn-conv-detail__flow/)
  assert.match(componentSource, /cnn-conv-detail__intro/)
  assert.match(componentSource, /cnn-conv-animator/)
  assert.match(componentSource, /cnn-conv-animator__grid/)
  assert.match(componentSource, /cnn-conv-animator__kernel-math/)
  assert.match(componentSource, /cnn-conv-animator__math-grid/)
  assert.match(componentSource, /@mouseleave="clearConvAnimatorWindowAnchor"/)
  assert.match(componentSource, /@focusout="clearConvAnimatorWindowAnchorIfFocusLeaves"/)
  assert.match(componentSource, /cnn-conv-detail__math-lens/)
  assert.match(componentSource, /cnn-conv-detail__channels/)
  assert.match(componentSource, /interface CnnConvLedgerItem/)
  assert.match(componentSource, /convLedgerItems = computed<CnnConvLedgerItem/)
  assert.match(componentSource, /convLedgerEquation/)
  assert.match(componentSource, /ledgerTone/)
  assert.match(componentSource, /focusConvLedgerItem/)
  assert.match(componentSource, /convLedgerItemDescription/)
  assert.match(componentSource, /class="cnn-conv-ledger"/)
  assert.match(componentSource, /class="cnn-conv-ledger__items"/)
  assert.match(componentSource, /copy\.convLedgerTitle/)
  assert.match(componentSource, /copy\.convLedgerHint/)
  assert.match(componentSource, /@mouseenter="focusConvLedgerItem\(item\)"/)
  assert.match(componentSource, /copy\.allChannels/)
  assert.match(componentSource, /copy\.convChannelSummary/)
  assert.match(componentSource, /copy\.convAnimatorTitle/)
  assert.match(componentSource, /copy\.convAnimatorHint/)
  assert.match(componentSource, /copy\.convInputMatrix/)
  assert.match(componentSource, /copy\.convOutputMatrix/)
  assert.match(componentSource, /copy\.kernelMath/)
  assert.match(componentSource, /copy\.inspectMathCell/)
  assert.match(componentSource, /convContributions/)
  assert.match(componentSource, /isFocusedContribution/)
  assert.match(componentSource, /:class="\{ 'is-focused': isFocusedContribution\(contribution\.channelIndex\) \}"/)
  assert.match(componentSource, /@mouseenter="selectConvInputMatrixCell\(cell\)"/)
  assert.match(componentSource, /@focus="selectConvInputMatrixCell\(cell\)"/)
  assert.match(componentSource, /@click="selectConvOutputMatrixCell\(cell\)"/)
  assert.match(componentSource, /@mouseenter="focusConvAnimatorMathCell\(rowIndex, colIndex\)"/)
  assert.match(componentSource, /@click="focusConvMathCell\(contribution, rowIndex, colIndex\)"/)
  assert.match(componentSource, /class="cnn-matrix-cell"/)
  assert.match(componentSource, /'is-math-focused': isFocusedConvMathCell/)
  assert.doesNotMatch(componentSource, /channelContributions\?\.slice\(0, 3\)/)
  assert.match(componentSource, /colorForKernelValue/)
  assert.match(componentSource, /cnn-relu-detail/)
  assert.match(componentSource, /type CnnReluOperatorTerm/)
  assert.match(componentSource, /interface CnnHoverReadout/)
  assert.match(componentSource, /interface CnnColorLegend/)
  assert.match(componentSource, /interface CnnLegendStop/)
  assert.match(componentSource, /interface CnnSoftmaxContributionRow/)
  assert.match(componentSource, /hoverReadout/)
  assert.match(componentSource, /activeHoverReadout/)
  assert.match(componentSource, /activeColorLegend/)
  assert.match(componentSource, /overviewColorLegend = computed<CnnColorLegend/)
  assert.match(componentSource, /copy\.value\.colorLegendActivation/)
  assert.match(componentSource, /copy\.value\.colorLegendWeight/)
  assert.match(componentSource, /copy\.value\.colorLegendLogit/)
  assert.match(componentSource, /legendGradient/)
  assert.match(componentSource, /legendStops/)
  assert.match(componentSource, /legendMarkerPosition/)
  assert.match(componentSource, /overviewLegendMarkerX/)
  assert.match(componentSource, /copy\.value\.hoverInfo/)
  assert.match(componentSource, /copy\.value\.hoverMatrixCell/)
  assert.match(componentSource, /copy\.value\.hoverSoftmaxTerm/)
  assert.match(componentSource, /setFormulaTraceReadout\(term: CnnFormulaTraceTerm\)/)
  assert.match(componentSource, /function focusFormulaTraceTerm\(term: CnnFormulaTraceTerm\)/)
  assert.match(componentSource, /if \(term\.target === 'pool-winner'\)/)
  assert.match(componentSource, /if \(term\.target === 'dense-ledger'\)/)
  assert.match(componentSource, /focusOverviewNode/)
  assert.match(componentSource, /selectOverviewNode/)
  assert.match(componentSource, /@click="selectOverviewNode\(layer, node\)"/)
  assert.match(componentSource, /focusMatrixCellReadout/)
  assert.match(componentSource, /focusKernelWeightReadout/)
  assert.match(componentSource, /focusDenseWeightReadout/)
  assert.match(componentSource, /focusSoftmaxReadout/)
  assert.match(componentSource, /focusFlattenSourceReadout/)
  assert.match(componentSource, /focusFlattenVectorReadout/)
  assert.match(componentSource, /class="cnn-hover-readout"/)
  assert.match(componentSource, /aria-live="polite"/)
  assert.match(componentSource, /class="cnn-color-legend"/)
  assert.match(componentSource, /class="cnn-color-legend__scale"/)
  assert.match(componentSource, /:style="\{ background: activeColorLegend\.gradient \}"/)
  assert.match(componentSource, /:style="\{ left: activeColorLegend\.markerPosition \}"/)
  assert.match(componentSource, /reluMatrixPair/)
  assert.match(componentSource, /reluFocusedTerm/)
  assert.match(componentSource, /activeReluOperatorTerm/)
  assert.match(componentSource, /reluOperatorNarration/)
  assert.match(componentSource, /matrixWindowAround/)
  assert.match(componentSource, /selectReluMatrixCell/)
  assert.match(componentSource, /focusReluOperatorTerm/)
  assert.match(componentSource, /clearReluOperatorFocus/)
  assert.match(componentSource, /cnn-relu-detail__matrices/)
  assert.match(componentSource, /cnn-relu-detail__grid/)
  assert.match(componentSource, /cnn-relu-detail__operator-flow/)
  assert.match(componentSource, /cnn-relu-detail__term/)
  assert.match(componentSource, /cnn-relu-detail__output-cell/)
  assert.match(componentSource, /copy\.reluMatrixHint/)
  assert.match(componentSource, /copy\.reluOperatorTitle/)
  assert.match(componentSource, /copy\.reluOperatorHint/)
  assert.match(componentSource, /copy\.reluCandidate/)
  assert.match(componentSource, /copy\.reluSelectedInput/)
  assert.match(componentSource, /copy\.zeroThreshold/)
  assert.match(componentSource, /@mouseenter="selectReluMatrixCell\(cell\)"/)
  assert.match(componentSource, /@mouseenter="focusReluOperatorTerm\('zero'\)"/)
  assert.match(componentSource, /@mouseenter="focusReluOperatorTerm\('input'\)"/)
  assert.match(componentSource, /@mouseenter="focusReluOperatorTerm\('output'\)"/)
  assert.match(componentSource, /@mouseleave="clearReluOperatorFocus"/)
  assert.match(componentSource, /@focus="selectReluMatrixCell\(cell\)"/)
  assert.match(componentSource, /@click="selectReluMatrixCell\(cell\)"/)
  assert.match(componentSource, /@mouseenter="selectReluMatrixCell\(cell, copy\.reluOutputMatrix\)"/)
  assert.match(componentSource, /@keydown\.enter\.prevent="selectReluMatrixCell\(cell\)"/)
  assert.match(componentSource, /@keydown\.space\.prevent="selectReluMatrixCell\(cell\)"/)
  assert.match(componentSource, /cnn-flatten-detail__map/)
  assert.match(componentSource, /interface CnnFlattenLedgerItem/)
  assert.match(componentSource, /flattenLedgerItems = computed<CnnFlattenLedgerItem/)
  assert.match(componentSource, /flattenLedgerEquation/)
  assert.match(componentSource, /focusFlattenLedgerItem/)
  assert.match(componentSource, /class="cnn-flatten-ledger"/)
  assert.match(componentSource, /class="cnn-flatten-ledger__items"/)
  assert.match(componentSource, /copy\.flattenLedgerTitle/)
  assert.match(componentSource, /copy\.flattenLedgerHint/)
  assert.match(componentSource, /copy\.value\.channelOffset/)
  assert.match(componentSource, /copy\.value\.rowOffset/)
  assert.match(componentSource, /copy\.value\.colOffset/)
  assert.match(componentSource, /@mouseenter="focusFlattenLedgerItem\(item\)"/)
  assert.match(componentSource, /softmaxDenominator/)
  assert.match(componentSource, /softmaxContributionRows/)
  assert.match(componentSource, /expShare/)
  assert.match(componentSource, /expScore/)
  assert.match(componentSource, /cnn-softmax-detail__denominator/)
  assert.match(componentSource, /cnn-softmax-detail__equation/)
  assert.match(componentSource, /cnn-softmax-detail__fraction-stack/)
  assert.match(componentSource, /cnn-softmax-detail__contributions/)
  assert.match(componentSource, /cnn-softmax-detail__fraction/)
  assert.match(componentSource, /class="cnn-softmax-rank-panel"/)
  assert.match(componentSource, /class="cnn-softmax-rank-panel__rows"/)
  assert.match(componentSource, /@mouseenter="focusSoftmaxCompetitionRow\(row\)"/)
  assert.match(componentSource, /@click="selectSoftmaxCompetitionRow\(row\)"/)
  assert.match(componentSource, /@keydown\.enter\.prevent="selectSoftmaxCompetitionRow\(row\)"/)
  assert.match(componentSource, /copy\.softmaxFraction/)
  assert.match(componentSource, /copy\.softmaxExpTerms/)
  assert.match(componentSource, /copy\.denominatorShare/)
  assert.match(componentSource, /interface CnnPoolFocusedCell/)
  assert.match(componentSource, /interface CnnPoolOperatorCell/)
  assert.match(componentSource, /interface CnnPoolRetentionCell extends CnnMatrixCell/)
  assert.match(componentSource, /interface CnnPoolRetentionSummary/)
  assert.match(componentSource, /interface CnnPoolLedgerItem/)
  assert.match(componentSource, /isPoolMaxCell/)
  assert.match(componentSource, /poolWindowWinner\(matrix: number\[\]\[\]/)
  assert.match(componentSource, /poolWindowCellCount\(matrix: number\[\]\[\]/)
  assert.match(componentSource, /poolFocusedCell/)
  assert.match(componentSource, /poolMatrixPair/)
  assert.match(componentSource, /poolOperatorCells/)
  assert.match(componentSource, /activePoolOperatorCell/)
  assert.match(componentSource, /poolLedgerItems = computed<CnnPoolLedgerItem/)
  assert.match(componentSource, /poolLedgerEquation/)
  assert.match(componentSource, /poolRetentionSummary = computed<CnnPoolRetentionSummary/)
  assert.match(componentSource, /poolInputWindowAround/)
  assert.match(componentSource, /focusPoolOperatorCell/)
  assert.match(componentSource, /focusPoolLedgerItem/)
  assert.match(componentSource, /focusPoolRetentionCell\(cell\)/)
  assert.match(componentSource, /clearPoolOperatorFocus/)
  assert.match(componentSource, /selectPoolInputMatrixCell/)
  assert.match(componentSource, /selectPoolOutputMatrixCell/)
  assert.match(componentSource, /cnn-pool-detail__matrices/)
  assert.match(componentSource, /cnn-pool-detail__grid/)
  assert.match(componentSource, /cnn-pool-detail__operator-grid/)
  assert.match(componentSource, /cnn-pool-detail__output-cell/)
  assert.match(componentSource, /class="cnn-pool-ledger"/)
  assert.match(componentSource, /class="cnn-pool-ledger__items"/)
  assert.match(componentSource, /class="cnn-pool-retention-panel"/)
  assert.match(componentSource, /class="cnn-pool-retention-panel__metrics"/)
  assert.match(componentSource, /class="cnn-pool-retention-panel__grid"/)
  assert.match(componentSource, /copy\.poolOperatorTitle/)
  assert.match(componentSource, /copy\.poolOperatorHint/)
  assert.match(componentSource, /copy\.poolCandidate/)
  assert.match(componentSource, /copy\.poolWinner/)
  assert.match(componentSource, /poolRetentionTitle: 'MaxPool 保留 mask'/)
  assert.match(componentSource, /poolRetentionRatio: '保留比例'/)
  assert.match(componentSource, /poolDownsampleRatio: '空间缩小'/)
  assert.match(componentSource, /copy\.poolLedgerTitle/)
  assert.match(componentSource, /copy\.poolLedgerHint/)
  assert.match(componentSource, /copy\.poolMatrixHint/)
  assert.match(componentSource, /copy\.poolWindow/)
  assert.match(componentSource, /'is-window-source': cell\.isWindow/)
  assert.match(componentSource, /'is-source': cell\.isMax/)
  assert.match(componentSource, /'is-source': cell\.isMax, 'is-selected': cell\.isSelected/)
  assert.match(componentSource, /@mouseenter="selectPoolInputMatrixCell\(cell\)"/)
  assert.match(componentSource, /@mouseenter="focusPoolOperatorCell\(cell\)"/)
  assert.match(componentSource, /@mouseenter="focusPoolLedgerItem\(item\)"/)
  assert.match(componentSource, /@mouseenter="focusPoolRetentionCell\(cell\)"/)
  assert.match(componentSource, /@keydown\.enter\.prevent="focusPoolRetentionCell\(cell\)"/)
  assert.match(componentSource, /@mouseleave="clearPoolOperatorFocus"/)
  assert.match(componentSource, /@focus="selectPoolOutputMatrixCell\(cell\)"/)
  assert.match(componentSource, /@click="selectPoolOutputMatrixCell\(cell\)"/)
  assert.match(componentSource, /isFlattenSourceCell/)
  assert.match(componentSource, /detailStepCount/)
  assert.match(componentSource, /detailStepIndex/)
  assert.match(componentSource, /isDetailPlaying/)
  assert.match(componentSource, /detailAutoplayActive/)
  assert.match(componentSource, /toggleDetailPlayback/)
  assert.match(componentSource, /pauseDetailPlaybackFromInteraction/)
  assert.match(componentSource, /startDetailPlaybackTimer/)
  assert.match(componentSource, /stopDetailPlayback/)
  assert.match(componentSource, /window\.setInterval\(stepDetailForward, 250\)/)
  assert.match(componentSource, /class="cnn-detail-panel__controls"/)
  assert.match(componentSource, /copy\.playDetail/)
  assert.match(componentSource, /copy\.pauseDetail/)
  assert.match(componentSource, /copy\.closeDetail/)
  assert.match(componentSource, /copy\.detailAutoplayHint/)
  assert.match(componentSource, /@click="toggleDetailPlayback"/)
  assert.match(componentSource, /@click="closeDetailPanel"/)
  assert.match(componentSource, /'is-detail-playing': isDetailPlaying/)
  assert.match(componentSource, /selectActivationCell/)
  assert.match(componentSource, /@click="selectActivationCell\(cell\.row, cell\.col\)"/)
  assert.match(componentSource, /stepDetailWithinLayer/)
  assert.match(componentSource, /stepDetailBackward/)
  assert.match(componentSource, /stepDetailForward/)
  assert.match(componentSource, /onDetailScrub/)
  assert.match(componentSource, /setDetailStep/)
  assert.match(componentSource, /@input="onDetailScrub"/)
  assert.match(componentSource, /copy\.previousDetail/)
  assert.match(componentSource, /copy\.nextDetail/)
  assert.doesNotMatch(componentSource, /if \(showDetails\.value && stepDetailWithinLayer\(\)\) return/)
  assert.match(componentSource, /detailProgress/)
  assert.match(componentSource, /spatialBridge/)
  assert.match(componentSource, /operationNarration/)
  assert.match(componentSource, /stepExplanation/)
  assert.match(componentSource, /cnn-operation-narration/)
  assert.match(componentSource, /class="cnn-formula-trace"/)
  assert.match(componentSource, /class="cnn-formula-trace__terms"/)
  assert.match(componentSource, /class="cnn-formula-trace__term"/)
  assert.match(componentSource, /focusFormulaTraceTerm\(term\)/)
  assert.match(componentSource, /clearFormulaTraceFocus/)
  assert.match(componentSource, /target: 'conv-product'/)
  assert.match(componentSource, /target: 'softmax-term'/)
  assert.match(componentSource, /class="cnn-layer-function-guide"/)
  assert.match(componentSource, /'is-current-chapter': layerFunctionGuide\.isCurrentChapter/)
  assert.match(componentSource, /class="cnn-layer-function-guide__link"/)
  assert.match(componentSource, /:to="layerFunctionGuide\.route"/)
  assert.match(componentSource, /copy\.layerFunctionCurrent/)
  assert.match(componentSource, /Input 层/)
  assert.match(componentSource, /Dense\/Softmax layer/)
  assert.match(componentSource, /selectedOverviewNodeKey/)
  assert.match(componentSource, /activeOverviewNodeFocus/)
  assert.match(componentSource, /clearFocusedOverviewNode/)
  assert.match(componentSource, /clearOverviewNodeHover/)
  assert.match(componentSource, /isFocusedOverviewNode\(layer: CnnLayerSnapshot, node: CnnNodeSnapshot\)/)
  assert.match(componentSource, /@mouseover="focusOverviewNode\(layer, node\)"/)
  assert.match(componentSource, /@pointerenter="focusOverviewNode\(layer, node\)"/)
  assert.match(componentSource, /@focusin="focusOverviewNode\(layer, node\)"/)
  assert.match(componentSource, /@mouseleave="clearOverviewNodeHover"/)
  assert.match(componentSource, /@pointerleave="clearOverviewNodeHover"/)
  assert.match(componentSource, /@blur="clearOverviewNodeHover"/)
  assert.match(componentSource, /@focusout="clearOverviewNodeHover"/)
  assert.match(componentSource, /'is-focused': isFocusedOverviewNode\(layer, node\)/)
  assert.match(componentSource, /relatedOverviewNodeKeys/)
  assert.match(componentSource, /isMutedOverviewNode/)
  assert.match(componentSource, /cnn-spatial-bridge/)
  assert.match(componentSource, /cnn-spatial-bridge__window/)
  assert.match(componentSource, /cnn-spatial-bridge__cell/)
  assert.match(componentSource, /cnn-spatial-bridge__packet/)
  assert.match(componentSource, /cnn-spatial-bridge__rail/)
  assert.match(componentSource, /bridgeOverlayStyle/)
  assert.match(componentSource, /sampleGridStyle/)
  assert.match(componentSource, /previewBridgeSourceCell/)
  assert.match(componentSource, /commitBridgeOutputCell/)
  assert.match(componentSource, /endBridgePreviewIfFocusLeaves/)
  assert.match(componentSource, /isBridgeSourceSampleSelected/)
  assert.match(componentSource, /inspectSourceCell/)
  assert.match(componentSource, /@mouseenter="previewBridgeSourceCell/)
  assert.match(componentSource, /@focus="previewBridgeOutputCell/)
  assert.match(componentSource, /@click="commitBridgeSourceCell/)
  assert.doesNotMatch(componentSource, /Math\.min\(\.\.\.values\)/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /@keyframes cnn-detail-pulse/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /@keyframes cnn-overview-flow/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /@keyframes cnn-bridge-packet/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /@keyframes cnn-bridge-dash/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__node\.is-muted/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__node\.is-focused:not\(\.is-selected\) \.cnn-overview__tile-border/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__node\.is-focused:not\(\.is-selected\) \.cnn-overview__tile-depth/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__node\.is-trace:not\(\.is-selected\) \.cnn-overview__tile-border/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__node\.is-trace:not\(\.is-selected\) \.cnn-overview__tile-depth/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__node\.is-top-output/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__edge\.is-selected/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__edge\.is-trace-backward/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__edge\.is-trace-forward/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__flow-packets/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__flow-packet/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__flow-packet\.is-incoming/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__flow-packet\.is-outgoing/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__flow-packet\.is-trace/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__tile-depth/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__tile-image/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /pointer-events: none/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__dense-score/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__dense-rail/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__dense-bar/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__dense-prob/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__legend-ramp/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__legend-marker/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__legend-current/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__legend-tick/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__recipe/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__params/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__more circle/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__more text/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__more:hover circle/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__more:focus-visible circle/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__more\.is-expanded circle/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-trace/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-trace__counts/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-trace__steps/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-trace__step/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-trace__step\.is-current/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-trace__step\.is-output/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-strip/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-strip__meta/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-strip__items/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /grid-auto-flow: column/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-strip__item\.is-selected/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-strip__media/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-strip__scan-progress/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-strip__cell-marker/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-strip__item\.is-selected \.cnn-overview-strip__cell-marker/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-strip__item img/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__layer\.is-selected \.cnn-overview__recipe/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__layer-track/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__local-window/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__local-window\.is-source/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__local-window\.is-output/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview__local-window\.is-source\.is-focused/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-lens/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-node-lens/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-node-lens__flow/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-node-lens__facts/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-overview-node-lens__connections/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-intermediate-stack/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-intermediate-stack__cards/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-intermediate-stack__equation/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-intermediate-stack__mini-grid/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-layer-inspector/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-layer-inspector__metrics/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-layer-inspector__connections/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-layer-inspector__chips button:focus-visible/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-hyperparameter-lab/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-hyperparameter-lab__controls/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-hyperparameter-lab__stage/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-hyper-grid--input/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-hyper-grid--kernel/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-hyper-grid--output button:hover/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-hyper-grid--output button:focus-visible/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-hyperparameter-lab__explain/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pipeline-rail/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pipeline-rail__steps/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pipeline-rail__step\.is-current/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pipeline-rail__step\.is-done/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-forward-storyboard/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-forward-storyboard__steps/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-forward-storyboard__step\.is-current/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-forward-storyboard__step\.is-dense\.is-current/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-operation-narration/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-formula-trace/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-formula-trace__terms/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-formula-trace__term\.is-logit/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-formula-trace__term:hover em/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-layer-function-guide/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-layer-function-guide__link:focus-visible/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-layer-function-guide__link\s*\{\s*width: 100%;/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-data-view/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-preprocess/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-preprocess__steps/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-preprocess__step\.is-crop/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-preprocess__step\.is-resize/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-preprocess__crop-frame/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-preprocess__tensor-grid/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-data-view__channels/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-data-view__grid/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-data-view__pixel/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-data-view__channels,\s*\n\s*\.cnn-conv-animator/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-detail-panel__controls/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-detail-panel\.is-detail-playing/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-detail-panel__timeline-controls/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-detail-scan-map/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-detail-scan-map__legend/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-detail-scan-map__grid/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-detail-scan-map__grid button\.is-current/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-detail-scan-map__grid button\.is-pending/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /overscroll-behavior-x: contain/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-hover-readout/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-hover-readout\.is-weight::before/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-hover-readout\.is-logit::before/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-color-legend/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-color-legend__scale/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-color-legend__scale i/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-color-legend__scale b/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-color-legend em strong/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-preview/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-preview__receptive-field/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-input-preview__receptive-field::after/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-receptive-field/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-receptive-field__chips/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-propagation-bridge/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-propagation-bridge__flow/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-propagation-bridge__formula/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-propagation-bridge__chips/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-propagation-bridge__flow > div::before/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-propagation-bridge__formula > div/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-detail__grid button\.is-selected/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-detail__grid button\.is-source/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-detail__channels/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-detail article\.is-focused/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-ledger/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-ledger__items/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-ledger__items button\.is-weighted/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-ledger__items button\.is-positive i/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-ledger__items button\.is-negative i/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-animator/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-animator__grid/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-animator__grid button\.is-window-source/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-animator__kernel-math/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-animator__math-grid/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-animator__math-grid button\.is-math-focused/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-conv-detail__math-lens/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-matrix-grid button\.is-math-focused/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-detail__matrices/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-detail__grid/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-detail__grid button\.is-window-source/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-detail__grid button\.is-source/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-detail__operator-grid/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-detail__operator-grid button\.is-source/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-detail__output-cell/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-ledger/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-ledger__items/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-ledger__items button\.is-winner/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-ledger__items button\.is-selected/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-ledger__items button\.is-winner i/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-retention-panel/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-retention-panel__metrics/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-retention-panel__grid/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-retention-panel__grid button\.is-winner/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-retention-panel__grid button\.is-suppressed/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-retention-panel__metrics,\s*\.cnn-relu-mask-panel__metrics,\s*\.cnn-dense-source-locator__factors {\s*grid-template-columns: 1fr/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-pool-detail__value-flow/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-detail__matrices/)
  assert.match(reluMatricesStyle, /grid-template-columns: minmax\(9\.8rem, 1fr\) minmax\(8rem, 0\.75fr\) minmax\(9\.8rem, 1fr\)/)
  assert.doesNotMatch(reluMatricesStyle, /grid-template-columns: minmax\(0, 1fr\) auto minmax\(0, 1fr\)/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-detail__grid/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-detail__grid button\.is-negative/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-detail__grid button\.is-zero/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-detail__operator-flow/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-detail__term/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-detail__term\.is-source/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-detail__output-cell/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-detail__value-flow/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-mask-panel/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-mask-panel__metrics/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-mask-panel__grid/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-mask-panel__grid button\.is-clipped/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-mask-panel__grid button\.is-retained/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-relu-mask-panel__metrics,\s*\.cnn-dense-source-locator__factors {\s*grid-template-columns: 1fr/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /max-height: min\(56vh, 44rem\)/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-flatten-ledger/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-flatten-ledger__items/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-flatten-ledger__items button\.is-channel i/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-flatten-ledger__items button\.is-row i/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-flatten-ledger__items button\.is-col i/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-flatten-ledger__items button\.is-index/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-weight-kernel-bank/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-weight-map/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-ledger/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-ledger__items/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-ledger__items button\.is-positive/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-ledger__items button\.is-negative/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-ledger__items button\.is-bias/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-ledger__items button\.is-logit/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-waterfall/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-waterfall__steps/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /--axis-left: 50%/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-waterfall__bar::before/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-waterfall__steps button\.is-negative \.cnn-dense-waterfall__bar i/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-waterfall__steps button\.is-bias \.cnn-dense-waterfall__bar i/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-waterfall__scale/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-contribution-atlas/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-contribution-atlas__maps/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-contribution-atlas article\.is-focused/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-contribution-atlas__grid button\.is-focused/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-source-locator/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-source-locator__body/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-source-locator__grid button\.is-selected/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-dense-source-locator__factors/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-logit-map/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-sample-strip button\.is-top/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-sample-strip button\.is-expected/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-sample-strip button\.is-pending/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-sample-strip button\.is-pending::before/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /@keyframes cnn-sample-loading/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-score-panel__match/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-score-panel__match\.is-match/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-score-panel__match\.is-miss/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-score-panel__row\.is-softmax-highlighted/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-logit-map button\.is-highlighted/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-softmax-detail article\.is-highlighted/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-softmax-detail__terms button\.is-highlighted/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-softmax-detail__equation/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-softmax-detail__fraction-stack/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-softmax-detail__contributions/)
  assert.match(componentSource, /function selectSoftmaxClass\(classIndex: number\)/)
  assert.match(componentSource, /function softmaxTermAriaLabel\(score: CnnSoftmaxContributionRow\)/)
  assert.match(componentSource, /:aria-label="`\$\{copy\.numerator\}: \$\{softmaxTermAriaLabel\(activeSoftmaxRow\)\}`"/)
  assert.match(componentSource, /:aria-label="softmaxTermAriaLabel\(score\)"/)
  assert.match(componentSource, /@click="selectSoftmaxClass\(score\.classIndex\)"/)
  assert.match(componentSource, /@keydown\.enter\.prevent="selectSoftmaxClass\(score\.classIndex\)"/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-softmax-rank-panel/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-softmax-rank-panel__rows/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-softmax-rank-panel__rows button\.is-top b/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-softmax-rank-panel__rows button\.is-active/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-softmax-rank-panel__rows button\.is-highlighted/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-softmax-detail \.cnn-softmax-rank-panel__rows i/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-activation-map__empty/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-spatial-bridge__arrow/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /cnn-spatial-bridge__map button/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /is-window-source/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /is-output-cell/)
  assert.match(read('src/styles/modules/cnn-explainer.css'), /prefers-reduced-motion: reduce/)
  assert.match(algorithmViewSource, /import CnnExplainerLab/)
  assert.match(algorithmViewSource, /route\.path\.startsWith\('\/learn\/cnn-visualization'\)/)
  assert.match(algorithmViewSource, /const routeChapterLock = ref\(''\)/)
  assert.match(algorithmViewSource, /function syncRouteChapterIntoView\(chapterId: string\)/)
  assert.match(algorithmViewSource, /if \(routeChapterLock\.value && nextChapter !== routeChapterLock\.value\) return/)
  assert.match(algorithmViewSource, /document\.getElementById\(chapterId\)\?\.scrollIntoView/)
  assert.match(
    algorithmViewSource,
    /<CnnExplainerLab v-if="isCnnVisualizationPage && section\.id === activeChapter"/,
  )
  assert.match(algorithmViewSource, /route\.params\.lessonId/)
  assert.match(algorithmViewSource, /syncRouteChapterIntoView\(matchedChapter\.id\)/)
  assert.match(algorithmViewSource, /router\.replace\(`\/learn\/\$\{nextSlug\}\/\$\{firstChapterId\}`\)/)
  assert.match(routerSource, /path: '\/learn\/cnn-visualization\/:chapterId'/)
  assert.match(routerSource, /name: 'cnn-visualization-chapter'/)

  const cnnChapterIndex = routerSource.indexOf("path: '/learn/cnn-visualization/:chapterId'")
  const canonicalLessonIndex = routerSource.indexOf("path: '/learn/:moduleId/:lessonId'")
  assert.ok(cnnChapterIndex > -1 && cnnChapterIndex < canonicalLessonIndex)

  assert.match(moduleSource, /Tiny VGG/)
  assert.match(moduleSource, /browser-side forward pass/)
  assert.match(moduleSource, /REF-CNN-EXPLAINER/)
})
