import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const root = new URL('../', import.meta.url)
const read = (path: string) => readFileSync(new URL(path, root), 'utf8')

test('home page combines the new course progress layer with existing learning records', () => {
  const source = read('src/views/HomeView.vue')
  assert.match(source, /loadCourseProgress/)
  assert.match(source, /selectCourseContinueTarget/)
  assert.match(source, /summarizeCourseCompletion/)
  assert.match(source, /migrateLearningProgressV2/)
  assert.match(source, /courseProgressV1StorageKey/)
  assert.match(source, /learningProgressV2StorageKey/)
  assert.match(source, /algorithmProgressStorageKey/)
  assert.match(source, /mathLabProgressStorageKey/)
  assert.match(source, /dataLabProgressStorageKey/)
  assert.match(source, /window\.addEventListener\('focus', refreshProgress\)/)
  assert.match(source, /document\.addEventListener\('visibilitychange', handleVisibility\)/)
  assert.match(source, /window\.addEventListener\('storage', handleStorage\)/)
  assert.match(source, /window\.removeEventListener\('focus', refreshProgress\)/)
})

test('home page makes AI foundations the default path while retaining support and legacy entries', () => {
  const source = read('src/views/HomeView.vue')
  const routerSource = read('src/router/index.ts')
  assert.match(source, /aiFoundationCourse/)
  assert.match(source, /courseOverviewRoute/)
  assert.match(source, /courseUnitRoute/)
  assert.match(source, /course\.totalUnits/)
  assert.match(source, /course\.totalHours/)
  assert.match(source, /publishedStages/)
  assert.match(source, /featuredStage/)
  assert.match(source, /featuredUnits/)
  assert.match(source, /allPublishedUnits/)
  assert.match(source, /home-course-hero/)
  assert.match(source, /home-unit-grid/)
  assert.match(source, /home-stage-map/)
  assert.match(source, /home-support-grid/)
  assert.doesNotMatch(source, /<main class="course-page/)
  for (const route of ['/math-lab', '/data-lab', '/library/model', '/tracks/project-practice', '/progress', '/spine']) {
    assert.ok(source.includes(`route: '${route}'`), `${route} should remain reachable from home`)
  }
  assert.match(source, /旧知识地图（兼容入口）/)
  assert.match(source, /Legacy knowledge map/)
  assert.match(routerSource, /if \(savedPosition\) return savedPosition/)
  assert.match(routerSource, /if \(to\.hash\) return \{ el: to\.hash, top: 96, behavior: 'smooth' \}/)
  assert.doesNotMatch(source, /module-gallery|module-teaser/)
})

test('home and catalog show planned stages without creating unfinished unit links', () => {
  const homeSource = read('src/views/HomeView.vue')
  const overviewSource = read('src/views/CourseOverviewView.vue')
  const styles = read('src/styles/views/course.css')
  assert.match(homeSource, /stage\.publicationStatus === 'published'/)
  assert.match(homeSource, /整编建设中/)
  assert.match(homeSource, /Fourteen units across Parts A and B now form one continuous path/)
  assert.match(homeSource, /Parts C–D still show goals only/)
  assert.match(overviewSource, /v-if="stage\.publicationStatus === 'published'"/)
  assert.match(overviewSource, /v-else class="course-stage-card__planned"/)
  assert.match(overviewSource, /courseUnitsForStage/)
  assert.match(styles, /@media \(max-width: 620px\)/)
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)/)
  assert.match(styles, /:focus-visible/)
})
