import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = (path: string) => readFile(new URL(path, import.meta.url), 'utf8')

test('dedicated page renders one supplied chapter with an eight-entry bilingual navigation', async () => {
  const source = await read('../src/components/PythonDataToolsPagedLesson.vue')

  assert.match(source, /chapter: PythonDataToolsRuntimeChapter/)
  assert.match(source, /locale: AppLocale/)
  assert.match(source, /routeBase: string/)
  assert.match(source, /pythonDataToolsRuntimeChapters/)
  assert.match(source, /v-for="\(chapterEntry, index\) in pythonDataToolsRuntimeChapters"/)
  assert.match(source, /data-testid="python-data-tools-current-chapter"/)
  assert.match(source, /v-for="block in chapter\.blocks"/)
  assert.match(source, /currentIndex \+ 1/)
  assert.match(source, /pythonDataToolsRuntimeChapters\.length/)
  assert.match(source, /mobileMenuOpen/)
  assert.match(source, /closeMobileMenu/)
  assert.match(source, /previousChapter/)
  assert.match(source, /nextChapter/)
  assert.doesNotMatch(source, /progressPercent|mastery|pass(ed)?|gatesChapter/i)
})

test('every generated teaching code block exposes localized clipboard feedback', async () => {
  const source = await read('../src/components/PythonDataToolsPagedLesson.vue')
  const styles = await read('../src/styles/modules/python-data-tools.css')

  assert.match(source, /block\.kind === 'code'/)
  assert.match(source, /class="python-data-tools-page__copy-button"/)
  assert.match(source, /@click="copyCode\(block\.id, block\.code\)"/)
  assert.match(source, /navigator\.clipboard\.writeText\(code\)/)
  assert.match(source, /复制代码/)
  assert.match(source, /已复制/)
  assert.match(source, /复制失败/)
  assert.match(source, /Copy code/)
  assert.match(source, /Copied/)
  assert.match(source, /Copy failed/)
  assert.match(source, /aria-live="polite"/)
  assert.match(styles, /\.python-data-tools-page__copy-button/)
  assert.match(styles, /\.python-data-tools-page__copy-button\.is-copied/)
  assert.match(styles, /\.python-data-tools-page__copy-button\.is-failed/)
})

test('page exposes local dataset downloads and executed output previews beside course code', async () => {
  const page = await read('../src/components/PythonDataToolsPagedLesson.vue')
  const output = await read('../src/components/PythonDataToolsNotebookOutput.vue')
  const plotly = await read('../src/components/PythonDataToolsNotebookPlotlyPreview.vue')
  const styles = await read('../src/styles/modules/python-data-tools.css')

  assert.match(page, /pythonDataToolsContract\.datasetPath/)
  assert.match(page, /下载课程数据 CSV/)
  assert.match(page, /Download the course CSV/)
  assert.match(page, /data-dictionary\.json/)
  assert.match(page, /requirements\.txt/)
  assert.match(page, /<PythonDataToolsNotebookOutput/)
  assert.match(page, /outputSession\.cellOutputFor\(block\.id\)/)
  assert.match(page, /v-if="!block\.outputId"/)

  assert.match(output, /代码运行输出/)
  assert.match(output, /Code output/)
  assert.match(output, /运行成功；这个单元格只完成设置或写入文件，没有直接显示输出。/)
  assert.match(output, /Ran successfully; this cell only performs setup or writes a file/)
  assert.match(output, /item\.kind === 'success'/)
  assert.match(output, /item\.kind === 'text'/)
  assert.match(output, /item\.kind === 'image'/)
  assert.match(output, /<PythonDataToolsNotebookPlotlyPreview/)
  assert.doesNotMatch(output, /v-html|innerHTML/)

  assert.match(plotly, /await import\('plotly\.js-basic-dist-min'\)/)
  assert.match(plotly, /Plotly\.react/)
  assert.match(plotly, /Plotly\.purge/)
  assert.match(plotly, /ResizeObserver/)
  assert.doesNotMatch(plotly, /v-html|innerHTML|text\/html/)
  assert.match(styles, /\.python-data-tools-cell-output/)
})

test('generated blocks remain inline and forward presentation plus typed session state', async () => {
  const source = await read('../src/components/PythonDataToolsPagedLesson.vue')

  assert.match(source, /<MarkdownMathContent/)
  assert.match(source, /block\.kind === 'code'/)
  assert.match(source, /<PythonDataToolsResultBlock/)
  assert.match(source, /:presentation="block"/)
  assert.match(source, /:state="outputSession\.stateFor\(block\.outputId\)"/)
  assert.match(source, /:fallback-results="fallbackResultsFor\(block\.outputId\)"/)
  assert.match(source, /@fallback-needed="loadFallbackResults\(block\.outputId\)"/)
  assert.match(source, /usePythonDataToolsOutputSession\(\{ outputIds: chapterOutputIds \}\)/)
  assert.match(source, /<PythonDataToolsTeachingPrompt/)
  assert.match(source, /:prompt="block"/)
  assert.match(source, /:route-base="routeBase"/)
  assert.doesNotMatch(source, /dataset-shape-schema\s*:/)
  assert.doesNotMatch(source, /<[^>]+>[^<{]*(证据|manifest)[^<{]*<\//i)
})

test('page exposes two base-safe Notebook placements and one session-level reload action', async () => {
  const source = await read('../src/components/PythonDataToolsPagedLesson.vue')
  const styles = await read('../src/styles/modules/python-data-tools.css')
  const styleIndex = await read('../src/styles/index.css')

  assert.match(source, /usePythonDataToolsOutputSession/)
  assert.match(source, /withPublicBase/)
  assert.match(source, /manifest\.notebook\.publicPath/)
  assert.match(source, /manifest\.environment\.path/)
  assert.equal((source.match(/class="python-data-tools-page__download"/g) ?? []).length, 2)
  assert.match(source, /下载完整中文 Notebook/)
  assert.match(source, /Download the complete Chinese Notebook/)
  assert.match(source, /已执行并包含运行结果/)
  assert.match(source, /executed and contains its runtime results/i)
  assert.match(source, /本地 Python 环境/)
  assert.match(source, /local Python environment/i)
  assert.match(source, /重新加载运行结果/)
  assert.match(source, /Reload runtime results/)
  assert.equal((source.match(/outputSession\.reloadRuntimeResults/g) ?? []).length, 1)
  assert.doesNotMatch(source, /setTimeout|setInterval|watchEffect/)

  assert.match(styleIndex, /modules\/python-data-tools\.css/)
  assert.match(styles, /position:\s*sticky/)
  assert.match(styles, /:focus-visible/)
  assert.match(styles, /overflow-wrap:\s*anywhere/)
  assert.match(styles, /@media \(max-width:\s*1080px\)/)
  assert.match(styles, /@media \(max-width:\s*720px\)/)
  assert.match(styles, /prefers-reduced-motion:\s*reduce/)
})
