import type { CurriculumV3ModuleBlueprint } from '../types.ts'

type Definition<Id extends string> = Omit<CurriculumV3ModuleBlueprint, 'id' | 'contentEvidence' | 'authoring'> & {
  id: Id
  formulaVocabulary: string[]
  checkpointEvidence: CurriculumV3ModuleBlueprint['contentEvidence']['checkpointEvidence']
  hasScratchCode?: boolean
  hasFrameworkCode?: boolean
}

const copy = (zhCN: string, en: string) => ({ 'zh-CN': zhCN, en })

const defineModule = <const Id extends string>(
  definition: Definition<Id>,
): CurriculumV3ModuleBlueprint & { id: Id } => {
  const { formulaVocabulary, checkpointEvidence, hasScratchCode, hasFrameworkCode, ...module } = definition
  return {
    ...module,
    contentEvidence: {
      intuitionId: `${module.id}-intuition`,
      formulaVocabulary,
      workedExampleId: `${module.id}-worked-example`,
      scratchCodeId: hasScratchCode ? `${module.id}-scratch-code` : undefined,
      frameworkCodeId: hasFrameworkCode ? `${module.id}-framework-code` : undefined,
      experimentId: `${module.id}-experiment`,
      failureCaseId: `${module.id}-failure-case`,
      exerciseKinds: ['concept', 'calculation-code', 'open-experiment'],
      checkpointEvidence,
    },
    authoring: { zhCN: 'planned', review: 'planned', en: 'planned', runtime: 'planned' },
  }
}

export const v3DeepLearningOrder = [
  ['neuron-activation-foundations', ['linear-regression', 'calculus-partial-derivatives-gradients']],
  ['mlp', ['neuron-activation-foundations', 'classification']],
  ['backpropagation-mechanism', ['mlp', 'chain-rule-local-approximation']],
  ['matrix-calculus-autodiff', ['backpropagation-mechanism', 'linear-algebra-matrix-transformations']],
  ['initialization-normalization', ['matrix-calculus-autodiff', 'probability-expectation-variance']],
  ['optimizer-comparison', ['gradient-descent', 'backpropagation-mechanism']],
  ['deep-architecture-math', ['initialization-normalization', 'optimizer-comparison']],
  ['tensor-shapes-vectorization', ['linear-algebra-matrix-transformations', 'python-notebook']],
  ['cnn-visualization', ['tensor-shapes-vectorization', 'mlp']],
  ['sequence-models-rnn', ['tensor-shapes-vectorization', 'mlp']],
  ['sequence-embedding-bridge', ['sequence-models-rnn', 'linear-algebra-distance-similarity']],
  ['tokenization-language-modeling', ['sequence-embedding-bridge', 'probability-likelihood-entropy']],
  ['attention-qkv-multihead', ['tokenization-language-modeling', 'linear-algebra-matrix-transformations']],
  ['transformer-blocks', ['attention-qkv-multihead', 'matrix-calculus-autodiff', 'initialization-normalization']],
  ['small-transformer-training', ['transformer-blocks', 'optimizer-comparison']],
  ['decoding-sampling', ['small-transformer-training', 'probability-expectation-variance']],
  ['llm-inference-context', ['decoding-sampling']],
  ['peft-lora', ['llm-inference-context', 'linear-algebra-matrix-transformations']],
  ['retrieval-rag-systems', ['llm-inference-context', 'linear-algebra-distance-similarity']],
  ['llm-evaluation-reliability', ['retrieval-rag-systems', 'model-selection']],
] as const

const base = {
  projectIds: [] as string[],
}

export const curriculumV3DeepLearningModules = [
  defineModule({ ...base, id: 'neuron-activation-foundations', arcId: 'neural-network-foundations', order: 1, role: 'required-core',
    title: copy('神经元与激活函数', 'Neurons and Activation Functions'),
    learnerQuestion: copy('线性预测器加上非线性激活后，为什么能表示弯曲的决策边界？', 'Why can a linear predictor represent curved decision boundaries after adding nonlinear activations?'),
    outcomes: [copy('能逐样本计算仿射变换与 ReLU、sigmoid 输出，并用饱和区和零梯度解释训练失败。', 'Compute affine, ReLU, and sigmoid outputs per example and explain training failures using saturation and zero-gradient regions.')],
    prerequisiteIds: ['linear-regression', 'calculus-partial-derivatives-gradients'], introduces: ['artificial-neuron', 'activation-function'], revisits: ['linear-prediction', 'partial-derivative'],
    mathCapabilities: ['compose-affine-maps-with-nonlinear-activations'], pythonCapabilities: ['implement-and-plot-activation-functions'],
    formulaVocabulary: ['x', 'w', 'b', 'z=w^T x+b', 'a=φ(z)', 'ReLU', 'sigmoid'], hasScratchCode: true, checkpointEvidence: 'calculation', sourceModuleIds: [], migrationAction: 'add' }),
  defineModule({ ...base, id: 'mlp', arcId: 'neural-network-foundations', order: 2, role: 'required-core',
    title: copy('多层感知机：组合可学习变换', 'MLPs: Composing Learnable Transformations'), learnerQuestion: copy('隐藏层宽度、激活与输出层怎样共同把特征映射成预测？', 'How do hidden width, activations, and the output layer jointly map features to predictions?'),
    outcomes: [copy('能追踪两层 MLP 中 x、W、b、z、a、yHat 与 loss 的形状和值，并实现一次前向传播。', 'Trace shapes and values of x, W, b, z, a, yHat, and loss through a two-layer MLP and implement one forward pass.')],
    prerequisiteIds: ['neuron-activation-foundations', 'classification'], introduces: ['hidden-layer', 'mlp-forward-pass'], revisits: ['activation-function', 'decision-boundary'], mathCapabilities: ['calculate-layerwise-affine-and-activation-maps'], pythonCapabilities: ['implement-vectorized-mlp-forward-pass', 'numpy-mlp-from-scratch', 'pytorch-mlp-training'],
    formulaVocabulary: ['x', 'W', 'b', 'z', 'a', 'yHat', 'loss'], hasScratchCode: true, hasFrameworkCode: true, checkpointEvidence: 'code', sourceModuleIds: ['mlp'], migrationAction: 'rebuild' }),
  defineModule({ ...base, id: 'backpropagation-mechanism', arcId: 'neural-network-foundations', order: 3, role: 'required-core',
    title: copy('反向传播：局部导数传递责任', 'Backpropagation: Passing Credit Through Local Derivatives'), learnerQuestion: copy('损失的变化如何沿计算图反向分配到每个权重和偏置？', 'How is a loss change propagated backward through a computation graph to every weight and bias?'),
    outcomes: [copy('能为两层网络计算 dLossDyHat、dLossDz、dLossDW 与 dLossDb，并用有限差分核验梯度。', 'Compute dLossDyHat, dLossDz, dLossDW, and dLossDb for a two-layer network and verify them with finite differences.')],
    prerequisiteIds: ['mlp', 'chain-rule-local-approximation'], introduces: ['backpropagation', 'gradient-flow'], revisits: ['chain-rule', 'mlp-forward-pass'], mathCapabilities: ['apply-vector-chain-rule-on-computation-graphs'], pythonCapabilities: ['implement-and-gradient-check-backpropagation'],
    formulaVocabulary: ['dLossDyHat', 'dLossDz', 'dLossDW', 'dLossDb'], hasScratchCode: true, checkpointEvidence: 'calculation', sourceModuleIds: [], migrationAction: 'add' }),
  defineModule({ ...base, id: 'matrix-calculus-autodiff', arcId: 'neural-network-foundations', order: 4, role: 'required-core',
    title: copy('矩阵微积分与自动微分', 'Matrix Calculus and Automatic Differentiation'), learnerQuestion: copy('自动微分如何用向量—雅可比积得到批量参数梯度，而不显式存储完整雅可比矩阵？', 'How does autodiff obtain batched parameter gradients with vector–Jacobian products without storing full Jacobians?'),
    outcomes: [copy('能标注矩阵运算的梯度形状，手算一个向量—雅可比积，并与框架 autograd 结果对照。', 'Annotate matrix-gradient shapes, hand-calculate a vector–Jacobian product, and compare it with framework autograd.')],
    prerequisiteIds: ['backpropagation-mechanism', 'linear-algebra-matrix-transformations'], introduces: ['jacobian', 'vector-jacobian-product', 'autodiff'], revisits: ['matrix-multiplication', 'backpropagation'], mathCapabilities: ['derive-matrix-gradient-shapes-and-vjps'], pythonCapabilities: ['inspect-autograd-graphs-and-gradients', 'pytorch-autograd'],
    formulaVocabulary: ['J_f', 'v^T J_f', '∂L/∂W', 'W^T'], hasFrameworkCode: true, checkpointEvidence: 'code', sourceModuleIds: ['matrix-calculus-autodiff'], migrationAction: 'rebuild' }),
  defineModule({ ...base, id: 'initialization-normalization', arcId: 'neural-network-foundations', order: 5, role: 'required-core',
    title: copy('初始化与归一化', 'Initialization and Normalization'), learnerQuestion: copy('权重方差和层归一化怎样控制深层网络中激活与梯度的尺度？', 'How do weight variance and normalization control activation and gradient scale in deep networks?'),
    outcomes: [copy('能比较零初始化、Xavier 与 He 初始化的层间方差，并解释 normalization 的训练/推理统计。', 'Compare layerwise variance under zero, Xavier, and He initialization and explain normalization statistics during training and inference.')],
    prerequisiteIds: ['matrix-calculus-autodiff', 'probability-expectation-variance'], introduces: ['weight-initialization', 'normalization'], revisits: ['variance', 'gradient-flow'], mathCapabilities: ['propagate-activation-variance-across-layers'], pythonCapabilities: ['measure-activation-and-gradient-statistics'],
    formulaVocabulary: ['Var(W)', 'fanIn', 'fanOut', 'μ', 'σ²', 'xNorm'], hasFrameworkCode: true, checkpointEvidence: 'experiment', sourceModuleIds: [], migrationAction: 'add' }),
  defineModule({ ...base, id: 'optimizer-comparison', arcId: 'neural-network-foundations', order: 6, role: 'required-core',
    title: copy('优化器比较：SGD、动量与 Adam', 'Optimizer Comparison: SGD, Momentum, and Adam'), learnerQuestion: copy('相同梯度序列为什么会被 SGD、动量和 Adam 转化为不同参数轨迹？', 'Why does the same gradient sequence produce different parameter trajectories under SGD, momentum, and Adam?'),
    outcomes: [copy('能逐步计算三种更新，在病态损失面比较收敛、震荡和发散，并说明学习率敏感性。', 'Calculate each update step, compare convergence, oscillation, and divergence on an ill-conditioned surface, and explain learning-rate sensitivity.')],
    prerequisiteIds: ['gradient-descent', 'backpropagation-mechanism'], introduces: ['optimizer', 'momentum-optimizer', 'adam-optimizer'], revisits: ['gradient', 'learning-rate', 'optimization-trajectory', 'gradient-flow'], mathCapabilities: ['calculate-momentum-and-adaptive-updates'], pythonCapabilities: ['compare-optimizer-trajectories-with-fixed-seeds'],
    formulaVocabulary: ['g_t', 'v_t', 'm_t', 's_t', 'learningRate', 'epsilon'], hasScratchCode: true, checkpointEvidence: 'experiment', sourceModuleIds: ['optimizer-comparison'], migrationAction: 'rebuild' }),
  defineModule({ ...base, id: 'deep-architecture-math', arcId: 'deep-learning-structures', order: 7, role: 'depth-topic',
    title: copy('深层架构数学', 'Mathematics of Deep Architectures'), learnerQuestion: copy('网络加深时，复合雅可比的谱如何导致梯度消失或爆炸？', 'How does the spectrum of composed Jacobians cause vanishing or exploding gradients as networks deepen?'),
    outcomes: [copy('能用雅可比范数估计梯度尺度，并比较普通堆叠与跳连结构的传播路径。', 'Estimate gradient scale with Jacobian norms and compare propagation paths in plain stacks and skip-connected structures.')],
    prerequisiteIds: ['initialization-normalization', 'optimizer-comparison'], introduces: ['deep-jacobian-product', 'skip-connection'], revisits: ['jacobian', 'gradient-flow'], mathCapabilities: ['analyze-products-of-layer-jacobians'], pythonCapabilities: ['measure-depth-versus-gradient-norm'],
    formulaVocabulary: ['Π_l J_l', 'spectralNorm', 'gradientNorm', 'x+F(x)'], hasFrameworkCode: true, checkpointEvidence: 'explanation', sourceModuleIds: ['deep-architecture-math'], migrationAction: 'rebuild' }),
  defineModule({ ...base, id: 'tensor-shapes-vectorization', arcId: 'deep-learning-structures', order: 8, role: 'required-core',
    title: copy('张量形状与向量化', 'Tensor Shapes and Vectorization'), learnerQuestion: copy('批次、时间、通道和特征轴怎样在不写样本循环的情况下安全变换？', 'How can batch, time, channel, and feature axes be transformed safely without per-example loops?'),
    outcomes: [copy('能标注 B/T/C/H/W/D 轴，使用 reshape、transpose 与 broadcasting，并检测 silent shape bugs。', 'Label B/T/C/H/W/D axes, use reshape, transpose, and broadcasting, and detect silent shape bugs.')],
    prerequisiteIds: ['linear-algebra-matrix-transformations', 'python-notebook'], introduces: ['tensor-axis', 'vectorization', 'broadcasting'], revisits: ['shape', 'matrix-multiplication'], mathCapabilities: ['verify-tensor-contraction-dimensions'], pythonCapabilities: ['vectorize-batched-tensor-operations'],
    formulaVocabulary: ['B', 'T', 'C', 'H', 'W', 'D', 'reshape', 'transpose'], hasScratchCode: true, checkpointEvidence: 'code', sourceModuleIds: ['tensor-shapes-vectorization'], migrationAction: 'rebuild' }),
  defineModule({ ...base, id: 'cnn-visualization', arcId: 'deep-learning-structures', order: 9, role: 'required-core',
    title: copy('卷积网络可视化', 'Visualizing Convolutional Networks'), learnerQuestion: copy('局部卷积核如何共享参数并逐层扩大感受野？', 'How do local convolution kernels share parameters and expand receptive fields layer by layer?'),
    outcomes: [copy('能手算小型二维卷积的输出形状与参数量，并用特征图定位 padding、stride 和通道错误。', 'Hand-calculate output shapes and parameter counts for a small 2D convolution and use feature maps to locate padding, stride, and channel errors.')],
    prerequisiteIds: ['tensor-shapes-vectorization', 'mlp'], introduces: ['convolution-kernel', 'feature-map', 'weight-sharing', 'receptive-field'], revisits: ['tensor-axis'], mathCapabilities: ['calculate-convolution-output-shape-and-parameters'], pythonCapabilities: ['visualize-kernels-and-feature-maps', 'pytorch-convolution-cnn'],
    formulaVocabulary: ['kernel', 'stride', 'padding', 'C_in', 'C_out', 'receptiveField'], hasFrameworkCode: true, checkpointEvidence: 'calculation', sourceModuleIds: ['cnn-visualization'], migrationAction: 'rebuild' }),
  defineModule({ ...base, id: 'sequence-models-rnn', arcId: 'deep-learning-structures', order: 10, role: 'required-core',
    title: copy('序列模型与循环网络', 'Sequence Models and Recurrent Networks'), learnerQuestion: copy('循环状态怎样把先前 token 的信息带到当前预测，又为何难以保留长程依赖？', 'How does recurrent state carry earlier-token information into the current prediction, and why is long-range memory difficult?'),
    outcomes: [copy('能展开 RNN 时间图，追踪 B×T×D 输入和隐藏状态，并用梯度范数说明长程依赖失败。', 'Unroll an RNN through time, trace B×T×D inputs and hidden states, and explain long-range failures with gradient norms.')],
    prerequisiteIds: ['tensor-shapes-vectorization', 'mlp'], introduces: ['recurrent-state', 'sequence-model'], revisits: ['tensor-axis', 'gradient-flow'], mathCapabilities: ['calculate-recurrent-state-updates'], pythonCapabilities: ['implement-and-unroll-a-small-rnn'],
    formulaVocabulary: ['x_t', 'h_t', 'W_xh', 'W_hh', 'y_t'], hasScratchCode: true, checkpointEvidence: 'code', sourceModuleIds: [], migrationAction: 'add' }),
  defineModule({ ...base, id: 'sequence-embedding-bridge', arcId: 'deep-learning-structures', order: 11, role: 'required-core',
    title: copy('序列到嵌入的桥梁', 'The Sequence-to-Embedding Bridge'), learnerQuestion: copy('离散 token 怎样变成可比较的连续向量序列，并保留顺序信息？', 'How do discrete tokens become comparable continuous vector sequences while retaining order?'),
    outcomes: [copy('能执行 embedding lookup、加入位置表示，并比较 token 与序列向量的余弦相似度。', 'Perform embedding lookup, add positional representations, and compare cosine similarities of token and sequence vectors.')],
    prerequisiteIds: ['sequence-models-rnn', 'linear-algebra-distance-similarity'], introduces: ['token-embedding', 'positional-representation'], revisits: ['recurrent-state', 'vector-similarity'], mathCapabilities: ['interpret-embedding-lookup-and-similarity'], pythonCapabilities: ['build-and-inspect-sequence-embedding-tensors'],
    formulaVocabulary: ['tokenId', 'E', 'embedding', 'position', 'cosineSimilarity'], hasFrameworkCode: true, checkpointEvidence: 'code', sourceModuleIds: ['sequence-embedding-bridge'], migrationAction: 'keep' }),
  defineModule({ ...base, id: 'tokenization-language-modeling', arcId: 'transformers-language-models', order: 12, role: 'required-core',
    title: copy('分词与语言建模目标', 'Tokenization and the Language-Modeling Objective'), learnerQuestion: copy('文本怎样变成 token 序列，next-token 目标又如何把每个位置变成监督样本？', 'How does text become a token sequence, and how does the next-token objective turn each position into a supervised example?'),
    outcomes: [copy('能比较字符与子词分词，构造移位输入/目标，并计算一个序列的负对数似然。', 'Compare character and subword tokenization, construct shifted inputs and targets, and calculate sequence negative log-likelihood.')],
    prerequisiteIds: ['sequence-embedding-bridge', 'probability-likelihood-entropy'], introduces: ['tokenization', 'causal-language-modeling'], revisits: ['token-embedding', 'likelihood', 'entropy'], mathCapabilities: ['factor-sequence-probability-autoregressively'], pythonCapabilities: ['encode-text-and-build-shifted-targets'],
    formulaVocabulary: ['tokenIds', 'vocabulary', 'p(x_t|x_{<t})', 'negativeLogLikelihood'], hasScratchCode: true, checkpointEvidence: 'calculation', sourceModuleIds: [], migrationAction: 'add' }),
  defineModule({ ...base, id: 'attention-qkv-multihead', arcId: 'transformers-language-models', order: 13, role: 'required-core',
    title: copy('Q/K/V 与多头注意力', 'Q/K/V and Multi-Head Attention'), learnerQuestion: copy('每个 token 如何用 query 与所有 key 匹配，再把 value 汇聚为上下文表示？', 'How does each token match its query against all keys and aggregate values into a contextual representation?'),
    outcomes: [copy('能从 B×T×H hidden states 投影 Q/K/V，核对 dK 缩放、mask 与 attentionWeights 形状，并组合多头输出。', 'Project Q/K/V from B×T×H hidden states, verify dK scaling, masks, and attentionWeights shapes, and combine multi-head outputs.')],
    prerequisiteIds: ['tokenization-language-modeling', 'linear-algebra-matrix-transformations'], introduces: ['query-key-value', 'self-attention', 'multi-head-attention'], revisits: ['matrix-multiplication', 'token-embedding'], mathCapabilities: ['derive-scaled-dot-product-attention-shapes'], pythonCapabilities: ['implement-masked-multi-head-attention', 'numpy-attention-math', 'pytorch-multihead-attention'],
    formulaVocabulary: ['B', 'T', 'H', 'Q', 'K', 'V', 'dK', 'attentionWeights'], hasScratchCode: true, hasFrameworkCode: true, checkpointEvidence: 'code', sourceModuleIds: ['attention-transformer'], migrationAction: 'split' }),
  defineModule({ ...base, id: 'transformer-blocks', arcId: 'transformers-language-models', order: 14, role: 'required-core',
    title: copy('Transformer 块：残差、归一化与 MLP', 'Transformer Blocks: Residuals, Normalization, and MLPs'), learnerQuestion: copy('注意力、残差连接、层归一化和逐位置 MLP 应按什么顺序组合，形状为何保持不变？', 'In what order should attention, residual connections, layer normalization, and position-wise MLPs compose, and why is shape preserved?'),
    outcomes: [copy('能组装 pre-norm Transformer block，逐步追踪 hiddenStates、residual、layerNorm 与 mlpOutput，并诊断遗漏残差或错误归一化轴。', 'Assemble a pre-norm Transformer block, trace hiddenStates, residual, layerNorm, and mlpOutput, and diagnose missing residuals or an incorrect normalization axis.')],
    prerequisiteIds: ['attention-qkv-multihead', 'matrix-calculus-autodiff', 'initialization-normalization'], introduces: ['transformer-block', 'pre-norm'], revisits: ['self-attention', 'normalization', 'skip-connection'], mathCapabilities: ['analyze-residual-and-layernorm-composition'], pythonCapabilities: ['assemble-and-test-a-transformer-block'],
    formulaVocabulary: ['hiddenStates', 'residual', 'layerNorm', 'mlpOutput'], hasFrameworkCode: true, checkpointEvidence: 'code', sourceModuleIds: ['attention-transformer'], migrationAction: 'split' }),
  defineModule({ ...base, id: 'small-transformer-training', arcId: 'transformers-language-models', order: 15, role: 'required-core',
    title: copy('训练一个小型 Transformer', 'Training a Small Transformer'), learnerQuestion: copy('tokenIds 如何经模型变成词表 logits，并与右移 targets 对齐计算交叉熵？', 'How do tokenIds become vocabulary logits, and how are they aligned with shifted targets for cross-entropy?'),
    outcomes: [copy('能训练可复现的小型因果 Transformer，核对 B×T×V logits 与 B×T targets 对齐，并区分训练/验证损失。', 'Train a reproducible small causal Transformer, verify alignment of B×T×V logits with B×T targets, and distinguish training from validation loss.')],
    prerequisiteIds: ['transformer-blocks', 'optimizer-comparison'], introduces: ['causal-transformer-training'], revisits: ['objective-function', 'cross-entropy', 'optimizer'], mathCapabilities: ['calculate-token-level-cross-entropy'], pythonCapabilities: ['train-and-checkpoint-a-small-transformer', 'pytorch-transformer-training'],
    formulaVocabulary: ['tokenIds', 'logits', 'targets', 'crossEntropy'], hasFrameworkCode: true, checkpointEvidence: 'experiment', sourceModuleIds: ['attention-transformer'], migrationAction: 'split' }),
  defineModule({ ...base, id: 'decoding-sampling', arcId: 'transformers-language-models', order: 16, role: 'required-core',
    title: copy('解码与采样', 'Decoding and Sampling'), learnerQuestion: copy('temperature、top-k 与随机种子怎样把同一组 logits 变成不同的 nextToken 分布和文本？', 'How do temperature, top-k, and random seeds turn the same logits into different nextToken distributions and texts?'),
    outcomes: [copy('能由 logits 计算 temperature-scaled probabilities，执行 greedy、top-k 与抽样，并比较多样性和重复失败。', 'Compute temperature-scaled probabilities from logits, perform greedy, top-k, and sampling decoding, and compare diversity and repetition failures.')],
    prerequisiteIds: ['small-transformer-training', 'probability-expectation-variance'], introduces: ['autoregressive-decoding', 'temperature-sampling'], revisits: ['probability-distribution', 'random-seed'], mathCapabilities: ['transform-logits-into-sampling-distributions'], pythonCapabilities: ['implement-reproducible-decoding-strategies'],
    formulaVocabulary: ['logits', 'temperature', 'probabilities', 'nextToken'], hasScratchCode: true, checkpointEvidence: 'experiment', sourceModuleIds: ['attention-transformer'], migrationAction: 'split' }),
  defineModule({ ...base, id: 'llm-inference-context', arcId: 'llm-adaptation-retrieval', order: 17, role: 'required-core',
    title: copy('LLM 推理与上下文窗口', 'LLM Inference and Context Windows'), learnerQuestion: copy('prompt token、KV cache、上下文上限与生成长度如何共同决定延迟和内存？', 'How do prompt tokens, the KV cache, context limits, and generation length jointly determine latency and memory?'),
    outcomes: [copy('能核算 prefill/decoding token 数与 KV cache 形状，并用截断实验识别上下文丢失。', 'Account for prefill/decoding token counts and KV-cache shapes and identify context loss with truncation experiments.')],
    prerequisiteIds: ['decoding-sampling'], introduces: ['context-window', 'kv-cache', 'prefill'], revisits: ['autoregressive-decoding', 'query-key-value'], mathCapabilities: ['estimate-kv-cache-memory-and-token-cost'], pythonCapabilities: ['measure-prefill-and-decoding-latency'],
    formulaVocabulary: ['contextLength', 'promptTokens', 'generatedTokens', 'kvCache', 'latency'], hasFrameworkCode: true, checkpointEvidence: 'calculation', sourceModuleIds: ['llm-rag'], migrationAction: 'split' }),
  defineModule({ ...base, id: 'peft-lora', arcId: 'llm-adaptation-retrieval', order: 18, role: 'required-core',
    title: copy('参数高效微调与 LoRA', 'Parameter-Efficient Fine-Tuning with LoRA'), learnerQuestion: copy('冻结基础权重 W 后，低秩 A、B 怎样用更少可训练参数改变模型行为？', 'After freezing base weight W, how do low-rank A and B alter behavior with fewer trainable parameters?'),
    outcomes: [copy('能核对 W、A、B 的矩阵形状，计算 rank 与 alpha 缩放后的更新，并比较全量微调参数量。', 'Verify matrix shapes of W, A, and B, calculate the rank- and alpha-scaled update, and compare parameter counts with full fine-tuning.')],
    prerequisiteIds: ['llm-inference-context', 'linear-algebra-matrix-transformations'], introduces: ['parameter-efficient-finetuning', 'lora'], revisits: ['matrix-multiplication', 'rank'], mathCapabilities: ['derive-lora-shapes-and-parameter-counts'], pythonCapabilities: ['implement-and-train-a-lora-linear-layer', 'peft-lora-adaptation'],
    formulaVocabulary: ['W', 'A', 'B', 'rank', 'alpha'], hasFrameworkCode: true, checkpointEvidence: 'code', sourceModuleIds: ['llm-rag'], migrationAction: 'split' }),
  defineModule({ ...base, id: 'retrieval-rag-systems', arcId: 'llm-adaptation-retrieval', order: 19, role: 'required-core',
    title: copy('检索增强生成系统', 'Retrieval-Augmented Generation Systems'), learnerQuestion: copy('queryEmbedding 如何与 documentEmbedding 比较，并让 topK 证据可追踪地进入生成上下文？', 'How is queryEmbedding compared with documentEmbedding so topK evidence enters generation context traceably?'),
    outcomes: [copy('能计算 queryEmbedding/documentEmbedding similarity、执行 topK 检索，并用无答案与错误检索案例区分检索和生成失败。', 'Compute queryEmbedding/documentEmbedding similarity, perform topK retrieval, and separate retrieval from generation failures using unanswerable and misretrieval cases.')],
    prerequisiteIds: ['llm-inference-context', 'linear-algebra-distance-similarity'], introduces: ['retrieval-augmented-generation', 'retrieval-evidence'], revisits: ['vector-similarity', 'context-window'], mathCapabilities: ['rank-documents-by-embedding-similarity'], pythonCapabilities: ['build-and-audit-a-small-rag-pipeline', 'python-vector-index-retrieval'],
    formulaVocabulary: ['queryEmbedding', 'documentEmbedding', 'similarity', 'topK'], hasFrameworkCode: true, checkpointEvidence: 'experiment', sourceModuleIds: ['llm-rag'], migrationAction: 'split' }),
  defineModule({ ...base, id: 'llm-evaluation-reliability', arcId: 'llm-adaptation-retrieval', order: 20, role: 'required-core',
    title: copy('LLM 评估与可靠性', 'LLM Evaluation and Reliability'), learnerQuestion: copy('怎样用可复现任务、检索指标、引用核验和失败切片判断系统是否可靠？', 'How can reproducible tasks, retrieval metrics, citation checks, and failure slices determine whether a system is reliable?'),
    outcomes: [copy('能建立锁定数据集与评分量表，分别报告 retrieval recall、回答正确性、引用支持率及不确定性，并记录失败案例。', 'Build a locked dataset and rubric, separately report retrieval recall, answer correctness, citation support rate, and uncertainty, and record failure cases.')],
    prerequisiteIds: ['retrieval-rag-systems', 'model-selection'], introduces: ['llm-evaluation-rubric', 'groundedness', 'reliability-report'], revisits: ['retrieval-evidence', 'selection-bias', 'slice-evaluation'], mathCapabilities: ['estimate-metric-uncertainty-and-retrieval-recall'], pythonCapabilities: ['run-versioned-llm-evaluation-suites'],
    formulaVocabulary: ['retrievalRecallAtK', 'answerAccuracy', 'citationSupportRate', 'confidenceInterval'], hasFrameworkCode: true, checkpointEvidence: 'explanation', sourceModuleIds: ['llm-rag'], migrationAction: 'split' }),
] satisfies CurriculumV3ModuleBlueprint[]
