import type { CurriculumV3ModuleBlueprint } from '../types.ts'

type FoundationModuleDefinition<Id extends string> = Omit<
  CurriculumV3ModuleBlueprint,
  'id' | 'contentEvidence' | 'authoring'
> & {
  id: Id
  formulaVocabulary: string[]
  scratchCode: boolean
  frameworkCode: boolean
  checkpointEvidence: CurriculumV3ModuleBlueprint['contentEvidence']['checkpointEvidence']
}

const copy = (zhCN: string, en: string) => ({ 'zh-CN': zhCN, en })

const defineModule = <const Id extends string>(
  definition: FoundationModuleDefinition<Id>,
): CurriculumV3ModuleBlueprint & { id: Id } => {
  const { formulaVocabulary, scratchCode, frameworkCode, checkpointEvidence, ...module } =
    definition
  const { id } = module

  return {
    ...module,
    contentEvidence: {
      intuitionId: `${id}-intuition`,
      formulaVocabulary,
      workedExampleId: `${id}-worked-example`,
      scratchCodeId: scratchCode ? `${id}-scratch-code` : undefined,
      frameworkCodeId: frameworkCode ? `${id}-framework-code` : undefined,
      experimentId: `${id}-experiment`,
      failureCaseId: `${id}-failure-case`,
      exerciseKinds: ['concept', 'calculation-code', 'open-experiment'],
      checkpointEvidence,
    },
    authoring: {
      zhCN: 'planned',
      review: 'planned',
      en: 'planned',
      runtime: 'planned',
    },
  }
}

export const curriculumV3FoundationModules = [
  defineModule({
    id: 'ai-overview',
    arcId: 'math-language',
    order: 1,
    role: 'required-core',
    title: copy('AI 学习地图：从数据、数学到模型', 'AI Learning Map: From Data and Mathematics to Models'),
    learnerQuestion: copy('一个 AI 系统怎样把数据变成可检查的预测？', 'How does an AI system turn data into an inspectable prediction?'),
    outcomes: [copy('能用数据、特征、模型、预测、损失和训练串起一个最小学习闭环。', 'Connect data, features, a model, predictions, loss, and training into one minimal learning loop.')],
    prerequisiteIds: [],
    introduces: ['sample', 'feature', 'label', 'prediction', 'loss', 'training-loop'],
    revisits: [],
    mathCapabilities: ['trace-values-through-a-learning-system', 'distinguish-inputs-parameters-and-outputs'],
    pythonCapabilities: ['read-a-minimal-prediction-script', 'inspect-named-intermediate-values'],
    formulaVocabulary: ['x', 'y', '\u0177', '\u03b8', 'L(y, \u0177)'],
    scratchCode: true,
    frameworkCode: false,
    checkpointEvidence: 'explanation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['ai-overview'],
    migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'python-notebook',
    arcId: 'math-language',
    order: 2,
    role: 'required-core',
    title: copy('Python Notebook 与可复现实验', 'Python Notebooks and Reproducible Experiments'),
    learnerQuestion: copy('怎样让一次数值实验既可重复运行，又能暴露每一步的形状和结果？', 'How can a numerical experiment be rerun while exposing every intermediate shape and result?'),
    outcomes: [copy('能在 notebook 中固定随机种子、操作 NumPy 数组，并记录输入、形状、参数和输出。', 'Use a notebook to seed randomness, manipulate NumPy arrays, and record inputs, shapes, parameters, and outputs.')],
    prerequisiteIds: ['ai-overview'],
    introduces: ['notebook-state', 'array', 'reproducibility', 'random-seed'],
    revisits: ['sample', 'feature', 'prediction'],
    mathCapabilities: ['read-indexed-values', 'track-scalar-vector-and-matrix-shapes'],
    pythonCapabilities: ['run-notebook-cells-in-order', 'create-and-inspect-numpy-arrays', 'control-random-seeds'],
    formulaVocabulary: ['x_i', 'X \u2208 \u211d^{n\u00d7d}', 'shape(X) = (n, d)', 'seed'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'code',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['python-notebook'],
    migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'calculus-functions-rate-change',
    arcId: 'math-language',
    order: 3,
    role: 'required-core',
    title: copy('函数、变量与变化率', 'Functions, Variables, and Rates of Change'),
    learnerQuestion: copy('输入改变时，怎样描述输出改变了多少以及改变得多快？', 'When an input changes, how do we describe how much and how quickly the output changes?'),
    outcomes: [copy('能从表格、图像和公式识别自变量、因变量，并计算区间平均变化率。', 'Identify independent and dependent variables in tables, graphs, and formulas and calculate an average rate of change.')],
    prerequisiteIds: ['python-notebook'],
    introduces: ['function', 'variable', 'rate-of-change'],
    revisits: ['array', 'feature', 'prediction'],
    mathCapabilities: ['evaluate-functions', 'compare-average-rates-from-values-and-graphs'],
    pythonCapabilities: ['define-and-sample-python-functions', 'plot-tabulated-function-values'],
    formulaVocabulary: ['y = f(x)', '\u0394x', '\u0394y', '\u0394y/\u0394x'],
    scratchCode: true,
    frameworkCode: false,
    checkpointEvidence: 'calculation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['calculus-functions-rate-change'],
    migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'beginner-linear-algebra',
    arcId: 'math-language',
    order: 4,
    role: 'required-core',
    title: copy('向量、矩阵与形状入门', 'An Introduction to Vectors, Matrices, and Shapes'),
    learnerQuestion: copy('多个特征怎样组成一个对象，多个对象又怎样组成模型可读的批次？', 'How do several features form one example, and how do examples form a model-ready batch?'),
    outcomes: [copy('能区分标量、向量和矩阵，解释轴的含义，并验证常见形状是否兼容。', 'Distinguish scalars, vectors, and matrices, explain each axis, and verify common shape compatibility.')],
    prerequisiteIds: ['calculus-functions-rate-change'],
    introduces: ['vector', 'matrix', 'shape'],
    revisits: ['variable', 'array', 'sample', 'feature'],
    mathCapabilities: ['represent-examples-as-vectors', 'read-matrix-rows-columns-and-dimensions'],
    pythonCapabilities: ['construct-vectors-and-matrices-with-numpy', 'check-array-shapes-and-axes'],
    formulaVocabulary: ['x \u2208 \u211d^d', 'X \u2208 \u211d^{n\u00d7d}', 'x_i', 'X_{ij}'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'code',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['beginner-linear-algebra'],
    migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'calculus-derivatives-local-change',
    arcId: 'math-language',
    order: 5,
    role: 'required-core',
    title: copy('导数与局部变化', 'Derivatives and Local Change'),
    learnerQuestion: copy('为什么曲线在一个点附近可以用一条斜率明确的直线来理解？', 'Why can a curve near one point be understood through a line with a definite slope?'),
    outcomes: [copy('能用割线逼近切线，解释导数的符号与大小，并估计小步输入变化造成的输出变化。', 'Approximate a tangent with secants, interpret derivative sign and magnitude, and estimate output change from a small input step.')],
    prerequisiteIds: ['calculus-functions-rate-change'],
    introduces: ['derivative', 'local-change'],
    revisits: ['function', 'variable', 'rate-of-change'],
    mathCapabilities: ['interpret-derivatives-as-local-slopes', 'form-local-linear-estimates'],
    pythonCapabilities: ['approximate-slopes-with-small-steps', 'compare-secant-and-analytic-slopes'],
    formulaVocabulary: ["f'(x)", 'lim_{h\u21920}(f(x+h)-f(x))/h', 'f(x+h) \u2248 f(x) + f\u2032(x)h'],
    scratchCode: true,
    frameworkCode: false,
    checkpointEvidence: 'calculation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['calculus-derivatives-local-change'],
    migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'beginner-probability-distributions',
    arcId: 'math-language',
    order: 6,
    role: 'required-core',
    title: copy('随机变量与概率分布入门', 'An Introduction to Random Variables and Probability Distributions'),
    learnerQuestion: copy('结果不确定时，怎样描述可能取值及每种取值出现的可能性？', 'When outcomes are uncertain, how do we describe possible values and how likely each is?'),
    outcomes: [copy('能定义离散随机变量、检查概率归一化，并从分布读取事件概率。', 'Define a discrete random variable, check probability normalization, and read event probabilities from a distribution.')],
    prerequisiteIds: ['calculus-functions-rate-change'],
    introduces: ['random-variable', 'probability-distribution'],
    revisits: ['function', 'variable'],
    mathCapabilities: ['represent-discrete-uncertainty', 'check-probability-axioms-and-normalization'],
    pythonCapabilities: ['encode-a-discrete-distribution', 'sample-and-compare-empirical-frequencies'],
    formulaVocabulary: ['X', 'P(X=x)', '0 \u2264 P(X=x) \u2264 1', '\u03a3_x P(X=x)=1'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'calculation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['beginner-probability-distributions'],
    migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'linear-algebra-feature-space',
    arcId: 'linear-algebra',
    order: 7,
    role: 'required-core',
    title: copy('特征空间与向量几何', 'Feature Space and Vector Geometry'),
    learnerQuestion: copy('把样本放进特征空间后，坐标、方向和尺度分别表达什么？', 'Once examples enter feature space, what do coordinates, directions, and scale represent?'),
    outcomes: [copy('能把样本解释为特征向量，并用加法、缩放和线性组合描述特征空间中的变化。', 'Interpret examples as feature vectors and use addition, scaling, and linear combinations to describe changes in feature space.')],
    prerequisiteIds: ['beginner-linear-algebra'],
    introduces: ['feature-space', 'linear-combination', 'span'],
    revisits: ['vector', 'shape', 'sample', 'feature'],
    mathCapabilities: ['form-and-interpret-linear-combinations', 'reason-about-directions-in-feature-space'],
    pythonCapabilities: ['compute-vector-combinations-with-numpy', 'visualize-low-dimensional-feature-vectors'],
    formulaVocabulary: ['x = [x_1,\u2026,x_d]^T', '\u03b1u+\u03b2v', 'span(v_1,\u2026,v_k)'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'explanation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['linear-algebra-feature-space'],
    migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'linear-algebra-distance-similarity',
    arcId: 'linear-algebra',
    order: 8,
    role: 'required-core',
    title: copy('距离、范数与方向相似度', 'Distance, Norms, and Directional Similarity'),
    learnerQuestion: copy('两个样本“接近”或“相似”时，模型究竟比较的是长度、距离还是方向？', 'When two examples are close or similar, is the model comparing length, distance, or direction?'),
    outcomes: [copy('能计算范数、欧氏距离、点积和余弦相似度，并说明特征缩放如何改变结论。', 'Calculate norms, Euclidean distance, dot products, and cosine similarity and explain how feature scaling changes the conclusion.')],
    prerequisiteIds: ['linear-algebra-feature-space'],
    introduces: ['norm', 'distance', 'dot-product', 'cosine-similarity'],
    revisits: ['vector', 'feature-space'],
    mathCapabilities: ['compare-distance-and-directional-similarity', 'diagnose-scale-sensitive-geometry'],
    pythonCapabilities: ['implement-vector-metrics-with-numpy', 'test-similarity-under-rescaling'],
    formulaVocabulary: ['\u2016x\u2016_2', 'd(x,y)=\u2016x-y\u2016_2', 'x\u00b7y', 'cos(x,y)=(x\u00b7y)/(\u2016x\u2016\u2016y\u2016)'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'calculation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['linear-algebra-distance-similarity'],
    migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'linear-algebra-matrix-transformations',
    arcId: 'linear-algebra',
    order: 9,
    role: 'required-core',
    title: copy('矩阵乘法与特征变换', 'Matrix Multiplication and Feature Transformations'),
    learnerQuestion: copy('矩阵怎样把输入坐标混合成新的特征方向？', 'How does a matrix mix input coordinates into new feature directions?'),
    outcomes: [copy('能按列解释矩阵向量乘法，验证乘法形状，并区分线性变换与带偏置的仿射变换。', 'Explain matrix-vector multiplication by columns, verify multiplication shapes, and distinguish linear from bias-shifted affine transformations.')],
    prerequisiteIds: ['beginner-linear-algebra'],
    introduces: ['matrix-multiplication', 'linear-map'],
    revisits: ['vector', 'matrix', 'shape', 'linear-combination'],
    mathCapabilities: ['interpret-matrix-products-as-column-mixtures', 'verify-linear-map-dimensions'],
    pythonCapabilities: ['implement-matrix-vector-products', 'compare-manual-products-with-numpy-matmul'],
    formulaVocabulary: ['A \u2208 \u211d^{m\u00d7d}', 'Ax=\u03a3_j x_j a_j', 'y=Ax', 'y=Wx+b'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'code',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['linear-algebra-matrix-transformations'],
    migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'linear-algebra-rank-null-space',
    arcId: 'linear-algebra',
    order: 10,
    role: 'depth-topic',
    title: copy('秩、列空间与零空间', 'Rank, Column Space, and Null Space'),
    learnerQuestion: copy('一个矩阵真正保留多少独立方向，又会把哪些输入差异完全抹掉？', 'How many independent directions does a matrix preserve, and which input differences does it erase?'),
    outcomes: [copy('能用列空间、秩和零空间解释信息保留、方程可解性与欠定解。', 'Use column space, rank, and null space to explain information preservation, solvability, and underdetermined solutions.')],
    prerequisiteIds: ['linear-algebra-matrix-transformations'],
    introduces: ['column-space', 'rank', 'null-space'],
    revisits: ['matrix-multiplication', 'linear-map', 'span'],
    mathCapabilities: ['identify-independent-output-directions', 'interpret-null-space-as-lost-information'],
    pythonCapabilities: ['estimate-rank-numerically', 'verify-null-space-vectors'],
    formulaVocabulary: ['Col(A)', 'rank(A)', 'N(A)={x:Ax=0}', 'rank(A)+nullity(A)=d'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'explanation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['linear-algebra-rank-null-space'],
    migrationAction: 'keep',
  }),
  defineModule({
    id: 'least-squares-fitting',
    arcId: 'linear-algebra',
    order: 11,
    role: 'required-core',
    title: copy('最小二乘与投影拟合', 'Least Squares and Projection-Based Fitting'),
    learnerQuestion: copy('方程没有精确解时，怎样找到整体误差最小且几何意义清楚的近似解？', 'When equations have no exact solution, how do we find an approximation with minimal total error and clear geometric meaning?'),
    outcomes: [copy('能把最小二乘解释为投影，计算残差，并验证正规方程中的正交条件。', 'Interpret least squares as projection, calculate residuals, and verify the orthogonality condition in the normal equations.')],
    prerequisiteIds: ['linear-algebra-feature-space', 'linear-algebra-matrix-transformations'],
    introduces: ['least-squares', 'projection', 'residual'],
    revisits: ['matrix-multiplication', 'feature-space', 'dot-product', 'norm'],
    mathCapabilities: ['formulate-and-solve-small-least-squares-problems', 'interpret-residual-orthogonality'],
    pythonCapabilities: ['implement-squared-error-fitting', 'compare-solutions-with-numpy-lstsq'],
    formulaVocabulary: ['min_w \u2016Xw-y\u2016_2^2', 'r=y-Xw', 'X^T r=0', 'X^T Xw=X^T y'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'calculation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['least-squares-fitting'],
    migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'eigenvalues-eigenvectors',
    arcId: 'linear-algebra',
    order: 12,
    role: 'depth-topic',
    title: copy('特征值、特征向量与稳定方向', 'Eigenvalues, Eigenvectors, and Stable Directions'),
    learnerQuestion: copy('矩阵作用后，哪些方向只改变尺度而不改变方向？', 'Which directions keep their orientation under a matrix and change only in scale?'),
    outcomes: [copy('能验证特征向量关系，并用特征值解释重复变换下方向的放大、缩小或翻转。', 'Verify an eigenvector relation and use eigenvalues to explain amplification, contraction, or reversal under repeated transformations.')],
    prerequisiteIds: ['linear-algebra-matrix-transformations'],
    introduces: ['eigenvalue', 'eigenvector', 'eigendirection'],
    revisits: ['matrix-multiplication', 'linear-map'],
    mathCapabilities: ['verify-eigenpairs', 'reason-about-repeated-linear-transformations'],
    pythonCapabilities: ['compute-eigenpairs-with-numpy', 'compare-iterated-transform-directions'],
    formulaVocabulary: ['Av=\u03bbv', 'det(A-\u03bbI)=0', 'A^k v=\u03bb^k v'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'calculation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['eigenvalues-eigenvectors'],
    migrationAction: 'keep',
  }),
  defineModule({
    id: 'svd-pca-representation',
    arcId: 'linear-algebra',
    order: 13,
    role: 'depth-topic',
    title: copy('SVD、PCA 与低维表征', 'SVD, PCA, and Low-Dimensional Representations'),
    learnerQuestion: copy('怎样用少量方向保留数据中最重要的变化，同时看见压缩丢失了什么？', 'How can a few directions preserve the most important variation in data while revealing what compression loses?'),
    outcomes: [copy('能连接 SVD 与 PCA，选择主成分，并用重建误差和解释方差评估低维表征。', 'Connect SVD to PCA, select principal components, and assess a low-dimensional representation using reconstruction error and explained variance.')],
    prerequisiteIds: ['least-squares-fitting', 'eigenvalues-eigenvectors'],
    introduces: ['singular-value', 'principal-component', 'explained-variance', 'low-rank-approximation'],
    revisits: ['projection', 'rank', 'eigenvector', 'feature-space'],
    mathCapabilities: ['interpret-singular-directions-and-values', 'quantify-low-rank-reconstruction-quality'],
    pythonCapabilities: ['center-data-and-compute-svd', 'reconstruct-data-from-selected-components'],
    formulaVocabulary: ['X=U\u03a3V^T', 'X_k=U_k\u03a3_kV_k^T', 'Z=XV_k', '\u03c3_i^2/\u03a3_j\u03c3_j^2'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'experiment',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['svd', 'pca'],
    migrationAction: 'merge',
  }),
  defineModule({
    id: 'numerical-linear-algebra',
    arcId: 'linear-algebra',
    order: 14,
    role: 'depth-topic',
    title: copy('数值线性代数：分解、稀疏性与条件数', 'Numerical Linear Algebra: Factorization, Sparsity, and Conditioning'),
    learnerQuestion: copy('数学上可解的线性系统，为什么在计算机中仍可能缓慢、昂贵或不稳定？', 'Why can a mathematically solvable linear system still be slow, expensive, or unstable on a computer?'),
    outcomes: [copy('能依据矩阵结构选择 LU 或稀疏表示，并用条件数预测输入误差的放大。', 'Choose LU or sparse representations based on matrix structure and use condition numbers to predict amplification of input error.')],
    prerequisiteIds: ['linear-algebra-rank-null-space'],
    introduces: ['lu-factorization', 'sparsity', 'condition-number', 'numerical-stability'],
    revisits: ['rank', 'matrix-multiplication', 'linear-map'],
    mathCapabilities: ['factor-small-linear-systems', 'relate-conditioning-to-solution-sensitivity'],
    pythonCapabilities: ['compare-dense-and-sparse-solves', 'measure-residuals-and-condition-numbers'],
    formulaVocabulary: ['A=LU', 'Ax=b', '\u03ba(A)=\u2016A\u2016\u2016A^{-1}\u2016', '\u2016\u03b4x\u2016/\u2016x\u2016'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'experiment',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['lu-decomposition', 'sparse-matrices', 'condition-numbers'],
    migrationAction: 'merge',
  }),
  defineModule({
    id: 'calculus-partial-derivatives-gradients',
    arcId: 'calculus-probability-optimization',
    order: 15,
    role: 'required-core',
    title: copy('偏导数、梯度与多变量变化', 'Partial Derivatives, Gradients, and Multivariable Change'),
    learnerQuestion: copy('损失依赖许多参数时，怎样分别衡量每个方向的局部影响并组合成一个更新方向？', 'When loss depends on many parameters, how do we measure each direction\u2019s local effect and combine them into one update direction?'),
    outcomes: [copy('能计算小型多变量函数的偏导数与梯度，并用方向导数解释最陡上升方向。', 'Calculate partial derivatives and gradients of a small multivariable function and use directional derivatives to explain steepest ascent.')],
    prerequisiteIds: ['calculus-derivatives-local-change', 'beginner-linear-algebra'],
    introduces: ['partial-derivative', 'gradient'],
    revisits: ['derivative', 'local-change', 'vector', 'shape'],
    mathCapabilities: ['compute-partial-derivatives', 'interpret-gradients-as-vectors-of-local-sensitivity'],
    pythonCapabilities: ['evaluate-multivariable-functions-on-grids', 'compare-coordinate-slopes-with-a-gradient'],
    formulaVocabulary: ['\u2202f/\u2202x_i', '\u2207f(x)=[\u2202f/\u2202x_1,\u2026,\u2202f/\u2202x_d]^T', 'D_u f=\u2207f\u00b7u'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'calculation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['calculus-partial-derivatives-gradients'],
    migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'chain-rule-local-approximation',
    arcId: 'calculus-probability-optimization',
    order: 16,
    role: 'required-core',
    title: copy('链式法则与局部近似', 'The Chain Rule and Local Approximation'),
    learnerQuestion: copy('多个函数串联时，一个早期变量的微小变化怎样传到最终输出？', 'When functions are composed, how does a small change in an early variable reach the final output?'),
    outcomes: [copy('能沿计算链应用链式法则，并用一阶 Taylor 近似检验导数预测的小步变化。', 'Apply the chain rule along a computation chain and use a first-order Taylor approximation to test derivative predictions for small steps.')],
    prerequisiteIds: ['calculus-derivatives-local-change'],
    introduces: ['chain-rule', 'local-linearization', 'taylor-approximation'],
    revisits: ['function', 'derivative', 'local-change'],
    mathCapabilities: ['differentiate-scalar-compositions', 'construct-and-check-first-order-approximations'],
    pythonCapabilities: ['trace-intermediate-values-and-local-slopes', 'measure-linearization-error-across-step-sizes'],
    formulaVocabulary: ['d(f\u2218g)/dx=f\u2032(g(x))g\u2032(x)', 'f(x+h)\u2248f(x)+f\u2032(x)h', 'O(h^2)'],
    scratchCode: true,
    frameworkCode: false,
    checkpointEvidence: 'calculation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['taylor-series'],
    migrationAction: 'merge',
  }),
  defineModule({
    id: 'numerical-differentiation-root-finding',
    arcId: 'calculus-probability-optimization',
    order: 17,
    role: 'depth-topic',
    title: copy('数值微分与非线性方程求根', 'Numerical Differentiation and Nonlinear Root Finding'),
    learnerQuestion: copy('没有符号导数或闭式解时，怎样用有限精度计算可靠地估计斜率并寻找根？', 'Without a symbolic derivative or closed-form solution, how can finite-precision computation reliably estimate slopes and find roots?'),
    outcomes: [copy('能比较前向差分与中心差分误差，并诊断 Newton 迭代对步长、初值和小导数的敏感性。', 'Compare forward- and central-difference error and diagnose Newton iteration sensitivity to step size, initialization, and small derivatives.')],
    prerequisiteIds: ['calculus-derivatives-local-change', 'python-notebook'],
    introduces: ['finite-difference', 'root-finding', 'truncation-error', 'roundoff-error'],
    revisits: ['derivative', 'rate-of-change', 'reproducibility'],
    mathCapabilities: ['derive-finite-difference-estimates', 'analyze-newton-update-failure-modes'],
    pythonCapabilities: ['implement-difference-formulas', 'run-and-instrument-newton-iterations'],
    formulaVocabulary: ["f'(x)\u2248(f(x+h)-f(x))/h", "f'(x)\u2248(f(x+h)-f(x-h))/(2h)", 'x_{k+1}=x_k-f(x_k)/f\u2032(x_k)'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'experiment',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['finite-difference-methods', 'nonlinear-equations'],
    migrationAction: 'merge',
  }),
  defineModule({
    id: 'probability-expectation-variance',
    arcId: 'calculus-probability-optimization',
    order: 18,
    role: 'required-core',
    title: copy('期望、方差与随机结果的尺度', 'Expectation, Variance, and the Scale of Random Outcomes'),
    learnerQuestion: copy('一个分布的典型结果在哪里，它的随机波动又有多大？', 'Where is a distribution\u2019s typical outcome, and how large is its random variation?'),
    outcomes: [copy('能从离散分布计算期望与方差，并用模拟均值和样本方差检验理论结果。', 'Calculate expectation and variance from a discrete distribution and verify them with simulated means and sample variances.')],
    prerequisiteIds: ['beginner-probability-distributions'],
    introduces: ['expectation', 'variance', 'standard-deviation'],
    revisits: ['random-variable', 'probability-distribution'],
    mathCapabilities: ['compute-weighted-expectations', 'interpret-variance-as-squared-spread'],
    pythonCapabilities: ['calculate-distribution-moments', 'estimate-moments-from-repeated-samples'],
    formulaVocabulary: ['E[X]=\u03a3_x xP(X=x)', 'Var(X)=E[(X-\u03bc)^2]', '\u03c3=\u221aVar(X)'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'calculation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: [],
    migrationAction: 'add',
  }),
  defineModule({
    id: 'conditional-probability-markov',
    arcId: 'calculus-probability-optimization',
    order: 19,
    role: 'depth-topic',
    title: copy('条件概率、Bayes 更新与 Markov 转移', 'Conditional Probability, Bayesian Updating, and Markov Transitions'),
    learnerQuestion: copy('获得新条件或进入新状态后，应该怎样更新对下一结果的概率判断？', 'After observing new evidence or entering a new state, how should probabilities for the next outcome be updated?'),
    outcomes: [copy('能计算条件概率与 Bayes 更新，并用转移矩阵模拟和解释有限状态 Markov 链。', 'Calculate conditional probabilities and Bayesian updates and use a transition matrix to simulate and interpret a finite-state Markov chain.')],
    prerequisiteIds: ['probability-expectation-variance'],
    introduces: ['conditional-probability', 'bayes-rule', 'markov-property', 'transition-matrix'],
    revisits: ['probability-distribution', 'matrix-multiplication', 'expectation'],
    mathCapabilities: ['update-probabilities-under-conditions', 'propagate-state-distributions'],
    pythonCapabilities: ['compute-bayesian-updates', 'simulate-and-propagate-markov-chains'],
    formulaVocabulary: ['P(A|B)=P(A\u2229B)/P(B)', 'P(A|B)=P(B|A)P(A)/P(B)', 'p_{t+1}=p_tT', '\u03a3_j T_{ij}=1'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'calculation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['markov-chains'],
    migrationAction: 'merge',
  }),
  defineModule({
    id: 'probability-likelihood-entropy',
    arcId: 'calculus-probability-optimization',
    order: 20,
    role: 'required-core',
    title: copy('似然、熵与交叉熵', 'Likelihood, Entropy, and Cross-Entropy'),
    learnerQuestion: copy('模型给出一组概率后，怎样衡量观测数据是否支持它，以及预测分布付出了多少信息代价？', 'After a model outputs probabilities, how do we measure support from observed data and the information cost of its predictive distribution?'),
    outcomes: [copy('能区分概率与似然，计算小型离散分布的熵和交叉熵，并解释低概率真值为何受到更大惩罚。', 'Distinguish probability from likelihood, calculate entropy and cross-entropy for small discrete distributions, and explain why low probability on the truth receives a larger penalty.')],
    prerequisiteIds: ['probability-expectation-variance'],
    introduces: ['likelihood', 'entropy', 'cross-entropy'],
    revisits: ['probability-distribution', 'expectation', 'loss'],
    mathCapabilities: ['form-likelihoods-from-observations', 'compute-and-interpret-information-measures'],
    pythonCapabilities: ['implement-log-likelihood-and-cross-entropy', 'test-numerical-stability-near-zero-probability'],
    formulaVocabulary: ['L(\u03b8|D)=\u220f_i p_\u03b8(y_i)', '\u2113(\u03b8)=\u03a3_i log p_\u03b8(y_i)', 'H(p)=-\u03a3_i p_i log p_i', 'H(p,q)=-\u03a3_i p_i log q_i'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'calculation',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['probability-likelihood-entropy'],
    migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'monte-carlo',
    arcId: 'calculus-probability-optimization',
    order: 21,
    role: 'depth-topic',
    title: copy('Monte Carlo 模拟与估计', 'Monte Carlo Simulation and Estimation'),
    learnerQuestion: copy('无法精确求和或积分时，重复随机采样怎样产生可量化误差的近似答案？', 'When exact sums or integrals are unavailable, how can repeated random sampling produce an approximate answer with quantifiable error?'),
    outcomes: [copy('能设计可复现的 Monte Carlo 估计，报告标准误差，并用样本量实验验证收敛趋势。', 'Design a reproducible Monte Carlo estimate, report standard error, and verify convergence trends with a sample-size experiment.')],
    prerequisiteIds: ['probability-expectation-variance', 'python-notebook'],
    introduces: ['monte-carlo-estimator', 'standard-error', 'sampling-convergence'],
    revisits: ['random-variable', 'expectation', 'variance', 'random-seed'],
    mathCapabilities: ['express-targets-as-expectations', 'relate-sample-size-to-estimation-error'],
    pythonCapabilities: ['implement-vectorized-random-simulation', 'repeat-seeded-estimates-and-plot-error'],
    formulaVocabulary: ['E[f(X)]\u2248(1/N)\u03a3_i f(X_i)', 'SE(\u0305X)=\u03c3/\u221aN', 'N'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'experiment',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['monte-carlo'],
    migrationAction: 'keep',
  }),
  defineModule({
    id: 'gradient-descent',
    arcId: 'calculus-probability-optimization',
    order: 22,
    role: 'required-core',
    title: copy('梯度下降：从局部斜率到训练行为', 'Gradient Descent: From Local Slopes to Training Behavior'),
    learnerQuestion: copy('模型怎样利用局部梯度逐步降低损失，又为什么会下降缓慢、震荡或发散？', 'How does a model use local gradients to reduce loss step by step, and why can training be slow, oscillatory, or divergent?'),
    outcomes: [copy('能从零实现批量梯度下降，把更新式连接到矩阵计算，并通过学习率实验诊断收敛、震荡和发散。', 'Implement batch gradient descent from scratch, connect its update to matrix computation, and diagnose convergence, oscillation, and divergence through a learning-rate experiment.')],
    prerequisiteIds: ['calculus-partial-derivatives-gradients', 'chain-rule-local-approximation'],
    introduces: ['learning-rate', 'optimization-trajectory', 'convergence'],
    revisits: ['derivative', 'gradient', 'matrix-multiplication'],
    mathCapabilities: ['derive-gradient-based-parameter-updates', 'analyze-step-size-and-curvature-effects'],
    pythonCapabilities: ['implement-and-log-a-gradient-descent-loop', 'compare-learning-rate-trajectories-reproducibly'],
    formulaVocabulary: ['\u03b8_{t+1}=\u03b8_t-\u03b7\u2207_\u03b8L(\u03b8_t)', '\u03b7', '\u2207_\u03b8L', 'X^T(Xw-y)'],
    scratchCode: true,
    frameworkCode: true,
    checkpointEvidence: 'experiment',
    projectIds: ['project-math-to-code'],
    sourceModuleIds: ['gradient-descent', 'calculus-gradient-descent', 'optimization'],
    migrationAction: 'merge',
  }),
] satisfies CurriculumV3ModuleBlueprint[]
