import type { CurriculumV3ModuleBlueprint } from '../types.ts'

type MachineLearningModuleDefinition<Id extends string> = Omit<
  CurriculumV3ModuleBlueprint,
  'id' | 'contentEvidence' | 'authoring'
> & {
  id: Id
  formulaVocabulary: string[]
  scratchCodeId?: string
  frameworkCodeId?: string
  checkpointEvidence: CurriculumV3ModuleBlueprint['contentEvidence']['checkpointEvidence']
}

const copy = (zhCN: string, en: string) => ({ 'zh-CN': zhCN, en })

const defineModule = <const Id extends string>(
  definition: MachineLearningModuleDefinition<Id>,
): CurriculumV3ModuleBlueprint & { id: Id } => {
  const { formulaVocabulary, scratchCodeId, frameworkCodeId, checkpointEvidence, ...module } =
    definition
  return {
    ...module,
    contentEvidence: {
      intuitionId: `${module.id}-intuition`,
      formulaVocabulary,
      workedExampleId: `${module.id}-worked-example`,
      scratchCodeId,
      frameworkCodeId,
      experimentId: `${module.id}-experiment`,
      failureCaseId: `${module.id}-failure-case`,
      exerciseKinds: ['concept', 'calculation-code', 'open-experiment'],
      checkpointEvidence,
    },
    authoring: {
      zhCN: 'planned',
      review: 'planned',
      en: 'planned',
      runtime: 'planned',
    },
  }
}

export const v3MachineLearningOrder = [
  ['numerical-data', ['python-notebook', 'linear-algebra-feature-space']],
  ['categorical-data', ['numerical-data']],
  ['dataset-quality', ['numerical-data']],
  ['splits-generalization', ['dataset-quality']],
  ['data-exploration-pipelines', ['categorical-data', 'splits-generalization']],
  ['loss-functions', ['gradient-descent', 'probability-likelihood-entropy']],
  ['linear-regression', ['least-squares-fitting', 'loss-functions', 'data-exploration-pipelines']],
  ['logistic-regression', ['linear-regression', 'probability-likelihood-entropy']],
  ['classification', ['logistic-regression', 'categorical-data']],
  ['tree-forest', ['classification', 'dataset-quality']],
  ['ensemble-learning', ['tree-forest']],
  ['complexity-regularization', ['linear-regression', 'classification']],
  ['model-selection', ['splits-generalization', 'complexity-regularization']],
  ['training-diagnostics', ['model-selection', 'tree-forest']],
] as const

export const curriculumV3MachineLearningModules = [
  defineModule({
    id: 'numerical-data', arcId: 'data-to-features', order: 1, role: 'required-core',
    title: copy('数值数据：从测量到特征矩阵', 'Numerical Data: From Measurements to Feature Matrices'),
    learnerQuestion: copy('带单位、量纲和缺失值的测量，怎样变成形状正确且可比较的模型输入？', 'How do measurements with units, scales, and missing values become shape-correct, comparable model inputs?'),
    outcomes: [copy('能构造样本×特征矩阵，审计 dtype、单位与缺失值，并用仅在训练集拟合的标准化变换数值列。', 'Build a sample-by-feature matrix, audit dtypes, units, and missingness, and standardize numeric columns using training-fitted statistics only.')],
    prerequisiteIds: ['python-notebook', 'linear-algebra-feature-space'],
    introduces: ['numeric-feature', 'feature-matrix'], revisits: ['array', 'shape', 'feature-space'],
    mathCapabilities: ['interpret-feature-matrix-axes-and-units', 'compute-column-location-and-scale'],
    pythonCapabilities: ['validate-numeric-dtypes-and-finite-values', 'standardize-columns-with-training-statistics'],
    formulaVocabulary: ['X ∈ ℝ^{n×d}', 'x_{ij}', 'z_{ij}=(x_{ij}-μ_j)/σ_j'],
    scratchCodeId: 'numerical-data-scratch-code', checkpointEvidence: 'code', projectIds: ['project-tabular-regression', 'project-classification-evaluation'],
    sourceModuleIds: ['numerical-data'], migrationAction: 'keep',
  }),
  defineModule({
    id: 'categorical-data', arcId: 'data-to-features', order: 2, role: 'required-core',
    title: copy('类别数据：词表、编码与未知值', 'Categorical Data: Vocabularies, Encoding, and Unknown Values'),
    learnerQuestion: copy('无天然大小关系的类别怎样编码，才不会虚构顺序并能处理部署时的新取值？', 'How can unordered categories be encoded without inventing rank while handling unseen values at deployment?'),
    outcomes: [copy('能从训练集建立类别词表与 OOV 策略，生成 one-hot 特征，并解释高基数和伪序数编码的风险。', 'Build a training-only vocabulary and OOV policy, produce one-hot features, and explain high-cardinality and false-ordinal risks.')],
    prerequisiteIds: ['numerical-data'],
    introduces: ['categorical-vocabulary', 'one-hot-encoding', 'oov-value'], revisits: ['feature-matrix'],
    mathCapabilities: ['represent-categories-as-basis-vectors', 'calculate-encoded-feature-dimension'],
    pythonCapabilities: ['fit-vocabulary-on-training-data', 'encode-unseen-categories-with-an-oov-policy'],
    formulaVocabulary: ['V={c_1,…,c_k}', 'onehot(c_i)=e_i', 'X_cat ∈ {0,1}^{n×k}'],
    scratchCodeId: 'categorical-data-scratch-code', checkpointEvidence: 'code', projectIds: ['project-tabular-regression', 'project-classification-evaluation'],
    sourceModuleIds: ['categorical-data'], migrationAction: 'keep',
  }),
  defineModule({
    id: 'dataset-quality', arcId: 'data-to-features', order: 3, role: 'required-core',
    title: copy('数据集质量：缺失、异常与标签审计', 'Dataset Quality: Missingness, Outliers, and Label Audits'),
    learnerQuestion: copy('如何区分真实信号、测量异常和标注错误，并量化它们对训练样本的影响？', 'How do we distinguish real signal, measurement anomalies, and label errors and quantify their impact on training examples?'),
    outcomes: [copy('能生成缺失率、重复率、异常范围和标签一致性报告，并为修复规则保留可追踪的前后样本计数。', 'Produce missingness, duplication, range, and label-consistency reports while retaining traceable before-and-after sample counts for each repair.')],
    prerequisiteIds: ['numerical-data'], introduces: ['missingness-profile', 'data-quality-rule', 'label-noise'], revisits: ['numeric-feature'],
    mathCapabilities: ['calculate-quality-rates-and-robust-summaries', 'compare-distributions-before-and-after-cleaning'],
    pythonCapabilities: ['profile-null-duplicate-and-range-violations', 'apply-auditable-cleaning-rules'],
    formulaVocabulary: ['r_missing(j)=n_missing(j)/n', 'IQR=Q_3-Q_1', 'x∉[Q_1-1.5IQR,Q_3+1.5IQR]'],
    scratchCodeId: 'dataset-quality-scratch-code', checkpointEvidence: 'experiment', projectIds: ['project-tabular-regression', 'project-classification-evaluation'],
    sourceModuleIds: ['dataset-quality'], migrationAction: 'keep',
  }),
  defineModule({
    id: 'splits-generalization', arcId: 'generalization-evaluation', order: 4, role: 'required-core',
    title: copy('数据划分与泛化', 'Data Splits and Generalization'),
    learnerQuestion: copy('怎样划分有限数据，才能调参而不偷看最终测试答案，并让评估代表真实部署？', 'How should finite data be split so we can tune without peeking at final test answers and still represent deployment?'),
    outcomes: [copy('能按随机、分层、分组或时间策略建立互斥 train/validation/test，并识别预处理、重复实体和未来信息造成的数据泄漏。', 'Create disjoint train/validation/test sets using random, stratified, grouped, or temporal strategies and detect leakage from preprocessing, repeated entities, or future information.')],
    prerequisiteIds: ['dataset-quality'], introduces: ['train-validation-test', 'data-leakage', 'generalization-gap'], revisits: ['reproducibility', 'random-seed'],
    mathCapabilities: ['estimate-generalization-gap', 'reason-about-sampling-and-deployment-distributions'],
    pythonCapabilities: ['construct-reproducible-disjoint-splits', 'assert-entity-and-time-boundary-integrity'],
    formulaVocabulary: ['D=D_train ⊔ D_val ⊔ D_test', 'gap=L_test-L_train', 'D_train∩D_test=∅'],
    scratchCodeId: 'splits-generalization-scratch-code', checkpointEvidence: 'explanation', projectIds: ['project-tabular-regression', 'project-classification-evaluation'],
    sourceModuleIds: ['splits-generalization'], migrationAction: 'keep',
  }),
  defineModule({
    id: 'data-exploration-pipelines', arcId: 'data-to-features', order: 5, role: 'required-core',
    title: copy('探索性分析与防泄漏管线', 'Exploratory Analysis and Leakage-Safe Pipelines'),
    learnerQuestion: copy('怎样用训练数据发现分布与关系，同时把相同预处理可靠地复用于验证和测试数据？', 'How can training data reveal distributions and relationships while the same preprocessing is reliably reused on validation and test data?'),
    outcomes: [copy('能建立按目标类型分层的 EDA 清单，并把插补、编码和缩放封装为只对训练集 fit、对其他集合 transform 的管线。', 'Build a target-aware EDA checklist and package imputation, encoding, and scaling into a pipeline fitted only on training data and reused for transformation.')],
    prerequisiteIds: ['categorical-data', 'splits-generalization'], introduces: ['eda-profile', 'fit-transform-pipeline'], revisits: ['feature-matrix', 'data-leakage', 'one-hot-encoding'],
    mathCapabilities: ['compare-conditional-feature-distributions', 'interpret-correlation-without-causal-claims'],
    pythonCapabilities: ['build-column-wise-preprocessing-pipelines', 'fit-transform-without-validation-leakage'],
    formulaVocabulary: ['p(x_j|y)', 'ρ_{jk}=cov(X_j,X_k)/(σ_jσ_k)', 'T_val=T_fit(D_train)(D_val)'],
    frameworkCodeId: 'scikit-learn-data-pipeline', checkpointEvidence: 'code', projectIds: ['project-tabular-regression', 'project-classification-evaluation'],
    sourceModuleIds: [], migrationAction: 'add',
  }),
  defineModule({
    id: 'loss-functions', arcId: 'classical-supervised-learning', order: 6, role: 'required-core',
    title: copy('损失函数：把预测误差变成训练目标', 'Loss Functions: Turning Prediction Error into a Training Objective'),
    learnerQuestion: copy('为什么平方误差和二元交叉熵会惩罚不同类型的错误，并产生不同梯度？', 'Why do squared error and binary cross-entropy penalize different errors and produce different gradients?'),
    outcomes: [copy('能从逐样本损失构造经验目标，计算 MSE 与稳定 BCE，并用误差尺度和梯度解释异常值或自信误判的影响。', 'Construct an empirical objective from per-example losses, calculate MSE and stable BCE, and explain outlier or confident-error effects through scale and gradients.')],
    prerequisiteIds: ['gradient-descent', 'probability-likelihood-entropy'], introduces: ['objective-function', 'mse', 'binary-cross-entropy'], revisits: ['loss', 'gradient', 'likelihood'],
    mathCapabilities: ['derive-and-compare-mse-and-bce-gradients', 'aggregate-example-losses-into-an-objective'],
    pythonCapabilities: ['implement-vectorized-mse-and-clipped-bce', 'check-loss-gradients-by-finite-differences'],
    formulaVocabulary: ['J(θ)=n^{-1}Σ_iℓ_i(θ)', 'MSE=n^{-1}Σ_i(y_i-ŷ_i)^2', 'BCE=-n^{-1}Σ_i[y_i log p_i+(1-y_i)log(1-p_i)]'],
    scratchCodeId: 'loss-functions-scratch-code', checkpointEvidence: 'calculation', projectIds: ['project-tabular-regression', 'project-classification-evaluation'],
    sourceModuleIds: ['loss-functions'], migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'linear-regression', arcId: 'classical-supervised-learning', order: 7, role: 'required-core',
    title: copy('线性回归：从矩阵预测到残差诊断', 'Linear Regression: From Matrix Predictions to Residual Diagnostics'),
    learnerQuestion: copy('如何从零训练线性预测器，并验证库模型的系数、预测和误差与自己的实现一致？', 'How do we train a linear predictor from scratch and verify that a library model agrees on coefficients, predictions, and errors?'),
    outcomes: [copy('能用 NumPy 实现批量梯度下降拟合 w、b，与 scikit-learn LinearRegression 对照，并通过残差图识别非线性和异方差。', 'Fit w and b with batch gradient descent in NumPy, compare against scikit-learn LinearRegression, and use residual plots to detect nonlinearity and heteroscedasticity.')],
    prerequisiteIds: ['least-squares-fitting', 'loss-functions', 'data-exploration-pipelines'], introduces: ['linear-regression-model', 'linear-prediction', 'regression-residual'], revisits: ['matrix-multiplication', 'least-squares', 'objective-function'],
    mathCapabilities: ['derive-linear-regression-mse-gradients', 'interpret-coefficients-and-residual-structure'],
    pythonCapabilities: ['train-linear-regression-from-scratch-with-numpy', 'compare-numpy-fit-with-scikit-learn-linear-regression'],
    formulaVocabulary: ['ŷ=Xw+b', 'J(w,b)=n^{-1}‖Xw+b-y‖_2^2', '∇_wJ=2X^T(ŷ-y)/n'],
    scratchCodeId: 'linear-regression-numpy-from-scratch', frameworkCodeId: 'scikit-learn-linear-regression', checkpointEvidence: 'code', projectIds: ['project-tabular-regression'],
    sourceModuleIds: ['linear-regression'], migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'logistic-regression', arcId: 'classical-supervised-learning', order: 8, role: 'required-core',
    title: copy('逻辑回归：分数、概率与决策边界', 'Logistic Regression: Scores, Probabilities, and Decision Boundaries'),
    learnerQuestion: copy('线性分数怎样变成类别概率，为什么最大似然训练等价于最小化二元交叉熵？', 'How does a linear score become a class probability, and why is maximum-likelihood training equivalent to minimizing binary cross-entropy?'),
    outcomes: [copy('能用 NumPy 实现 sigmoid、稳定 BCE 和梯度训练，与 scikit-learn LogisticRegression 对照概率，并解释系数对 log-odds 的影响。', 'Implement sigmoid, stable BCE, and gradient training in NumPy, compare probabilities with scikit-learn LogisticRegression, and interpret coefficient effects on log-odds.')],
    prerequisiteIds: ['linear-regression', 'probability-likelihood-entropy'], introduces: ['logit', 'sigmoid', 'decision-boundary'], revisits: ['likelihood', 'binary-cross-entropy'],
    mathCapabilities: ['connect-log-odds-likelihood-and-bce', 'derive-logistic-regression-gradients'],
    pythonCapabilities: ['train-logistic-regression-from-scratch-with-numpy', 'compare-numpy-probabilities-with-scikit-learn-logistic-regression'],
    formulaVocabulary: ['z=Xw+b', 'p(y=1|x)=σ(z)=1/(1+e^{-z})', 'log(p/(1-p))=z', '∇_wJ=X^T(p-y)/n'],
    scratchCodeId: 'logistic-regression-numpy-from-scratch', frameworkCodeId: 'scikit-learn-logistic-regression', checkpointEvidence: 'code', projectIds: ['project-classification-evaluation'],
    sourceModuleIds: ['logistic-regression'], migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'classification', arcId: 'classical-supervised-learning', order: 9, role: 'required-core',
    title: copy('分类评估：阈值与混淆矩阵', 'Classification Evaluation: Thresholds and Confusion Matrices'),
    learnerQuestion: copy('同一组概率为何会因阈值和业务代价不同得到完全不同的分类结论？', 'Why can the same probabilities produce very different classification conclusions under different thresholds and business costs?'),
    outcomes: [copy('能由概率与阈值计算混淆矩阵、precision、recall 和 F1，并依据假阳性与假阴性代价选择和说明阈值。', 'Compute a confusion matrix, precision, recall, and F1 from probabilities and a threshold, then select and justify a threshold using false-positive and false-negative costs.')],
    prerequisiteIds: ['logistic-regression', 'categorical-data'], introduces: ['threshold', 'confusion-matrix', 'precision', 'recall'], revisits: ['categorical-vocabulary', 'prediction'],
    mathCapabilities: ['calculate-classification-metrics-from-counts', 'reason-about-threshold-cost-tradeoffs'],
    pythonCapabilities: ['implement-confusion-counts-and-metrics', 'sweep-thresholds-and-plot-precision-recall'],
    formulaVocabulary: ['ŷ=𝟙[p≥τ]', 'precision=TP/(TP+FP)', 'recall=TP/(TP+FN)', 'F1=2PR/(P+R)'],
    scratchCodeId: 'classification-metrics-scratch-code', checkpointEvidence: 'calculation', projectIds: ['project-classification-evaluation'],
    sourceModuleIds: ['classification'], migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'tree-forest', arcId: 'classical-supervised-learning', order: 10, role: 'required-core',
    title: copy('决策树与随机森林', 'Decision Trees and Random Forests'),
    learnerQuestion: copy('树如何通过局部切分形成非线性规则，森林又怎样用重采样和特征随机性降低方差？', 'How do trees form nonlinear rules through local splits, and how do forests reduce variance using resampling and feature randomness?'),
    outcomes: [copy('能计算候选切分的 impurity reduction，训练受深度约束的树与随机森林，并用验证误差和置换重要性检查过拟合与捷径特征。', 'Calculate impurity reduction for candidate splits, train depth-constrained trees and random forests, and inspect overfitting and shortcut features using validation error and permutation importance.')],
    prerequisiteIds: ['classification', 'dataset-quality'], introduces: ['decision-tree', 'impurity-reduction', 'random-forest'], revisits: ['threshold', 'label-noise'],
    mathCapabilities: ['calculate-gini-and-weighted-split-gain', 'explain-bagging-variance-reduction'],
    pythonCapabilities: ['enumerate-small-tree-splits', 'train-and-audit-scikit-learn-tree-and-forest-models'],
    formulaVocabulary: ['Gini(S)=1-Σ_k p_k^2', 'ΔI=I(S)-n_L I(S_L)/n-n_R I(S_R)/n', 'f_RF(x)=mode_b f_b(x)'],
    scratchCodeId: 'tree-split-scratch-code', frameworkCodeId: 'scikit-learn-tree-forest', checkpointEvidence: 'experiment', projectIds: ['project-classification-evaluation'],
    sourceModuleIds: ['tree-forest'], migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'ensemble-learning', arcId: 'classical-supervised-learning', order: 11, role: 'depth-topic',
    title: copy('集成学习：投票、装袋与提升', 'Ensemble Learning: Voting, Bagging, and Boosting'),
    learnerQuestion: copy('多个有偏差或高方差的模型在什么条件下能组合成更可靠的预测器？', 'Under what conditions can biased or high-variance models combine into a more reliable predictor?'),
    outcomes: [copy('能比较 voting、bagging 与 boosting 的误差相关性和偏差—方差行为，并通过成员数量与学习率实验判断收益何时饱和或反转。', 'Compare error correlation and bias–variance behavior across voting, bagging, and boosting, and use member-count and learning-rate experiments to detect saturation or reversal of gains.')],
    prerequisiteIds: ['tree-forest'], introduces: ['voting-ensemble', 'bagging', 'boosting'], revisits: ['random-forest', 'residual'],
    mathCapabilities: ['decompose-ensemble-error-using-member-correlation', 'interpret-additive-boosting-updates'],
    pythonCapabilities: ['compare-voting-bagging-and-boosting', 'trace-validation-performance-by-ensemble-size'],
    formulaVocabulary: ['f_ens(x)=B^{-1}Σ_b f_b(x)', 'Var(f̄)=σ²[ρ+(1-ρ)/B]', 'F_m=F_{m-1}+ηh_m'],
    frameworkCodeId: 'scikit-learn-ensemble-learning', checkpointEvidence: 'experiment', projectIds: ['project-classification-evaluation'],
    sourceModuleIds: [], migrationAction: 'add',
  }),
  defineModule({
    id: 'complexity-regularization', arcId: 'generalization-evaluation', order: 12, role: 'required-core',
    title: copy('模型复杂度与正则化', 'Model Complexity and Regularization'),
    learnerQuestion: copy('怎样限制模型自由度，使它保留可泛化信号而不是记住训练噪声？', 'How can model freedom be constrained so it retains generalizable signal rather than memorizing training noise?'),
    outcomes: [copy('能比较 L1、L2、树深与样本量对训练/验证误差的影响，并用正则化路径解释欠拟合、稀疏性和系数收缩。', 'Compare effects of L1, L2, tree depth, and sample size on training/validation error and use regularization paths to explain underfitting, sparsity, and coefficient shrinkage.')],
    prerequisiteIds: ['linear-regression', 'classification'], introduces: ['model-capacity', 'l1-regularization', 'l2-regularization'], revisits: ['objective-function', 'generalization-gap'],
    mathCapabilities: ['form-regularized-objectives', 'interpret-bias-variance-and-parameter-norms'],
    pythonCapabilities: ['trace-l1-and-l2-regularization-paths', 'plot-training-and-validation-learning-curves'],
    formulaVocabulary: ['J_λ(θ)=J(θ)+λΩ(θ)', 'Ω_1(w)=‖w‖_1', 'Ω_2(w)=‖w‖_2^2'],
    scratchCodeId: 'complexity-regularization-scratch-code', frameworkCodeId: 'scikit-learn-regularization', checkpointEvidence: 'experiment', projectIds: ['project-classification-evaluation'],
    sourceModuleIds: ['complexity-regularization'], migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'model-selection', arcId: 'generalization-evaluation', order: 13, role: 'required-core',
    title: copy('模型选择：交叉验证与无偏测试', 'Model Selection: Cross-Validation and an Unbiased Test'),
    learnerQuestion: copy('如何比较模型和超参数而不把验证集反复调成另一个训练集？', 'How can models and hyperparameters be compared without repeatedly tuning the validation set into another training set?'),
    outcomes: [copy('能建立预注册指标的交叉验证搜索，在每折内部拟合预处理，汇报均值与离散度，并只对最终锁定模型使用一次测试集。', 'Run cross-validation search with a preregistered metric, fit preprocessing within each fold, report mean and dispersion, and use the test set once for the locked final model.')],
    prerequisiteIds: ['splits-generalization', 'complexity-regularization'], introduces: ['cross-validation', 'selection-bias'], revisits: ['train-validation-test', 'data-leakage'],
    mathCapabilities: ['aggregate-fold-estimates-and-uncertainty', 'distinguish-selection-from-final-estimation'],
    pythonCapabilities: ['run-leakage-safe-cross-validation-search', 'record-and-replay-a-locked-final-evaluation'],
    formulaVocabulary: ['CV_K(λ)=K^{-1}Σ_k L_k(λ)', 'SE=s/√K', 'λ*=argmin_λ CV_K(λ)'],
    frameworkCodeId: 'scikit-learn-model-selection', checkpointEvidence: 'code', projectIds: ['project-classification-evaluation'],
    sourceModuleIds: ['model-selection'], migrationAction: 'rebuild',
  }),
  defineModule({
    id: 'training-diagnostics', arcId: 'generalization-evaluation', order: 14, role: 'required-core',
    title: copy('训练诊断与可靠评估报告', 'Training Diagnostics and Reliable Evaluation Reports'),
    learnerQuestion: copy('面对不收敛、过拟合或指标异常，怎样用曲线、切片和基线定位原因而不是盲目调参？', 'When training diverges, overfits, or yields suspicious metrics, how do curves, slices, and baselines locate causes instead of prompting blind tuning?'),
    outcomes: [copy('能联合检查优化轨迹、学习曲线、残差或混淆矩阵、数据切片与朴素基线，形成包含不确定性、失败案例和复现实验配置的评估报告。', 'Jointly inspect optimization traces, learning curves, residuals or confusion matrices, data slices, and naive baselines to produce an evaluation report with uncertainty, failure cases, and reproducible configuration.')],
    prerequisiteIds: ['model-selection', 'tree-forest'], introduces: ['learning-curve', 'slice-evaluation', 'diagnostic-baseline'], revisits: ['generalization-gap', 'confusion-matrix', 'regression-residual'],
    mathCapabilities: ['separate-optimization-estimation-and-approximation-errors', 'quantify-slice-performance-and-uncertainty'],
    pythonCapabilities: ['log-and-plot-training-diagnostics', 'generate-reproducible-metric-and-slice-reports'],
    formulaVocabulary: ['gap(n)=L_val(n)-L_train(n)', 'Δ_slice=L_slice-L_overall', 'CI=estimate±critical·SE'],
    frameworkCodeId: 'scikit-learn-training-diagnostics', checkpointEvidence: 'explanation', projectIds: ['project-classification-evaluation'],
    sourceModuleIds: ['training-diagnostics'], migrationAction: 'rebuild',
  }),
] satisfies CurriculumV3ModuleBlueprint[]
