<script lang="ts">
import type { AppLocale, LocalizedCopy } from '../../../types/ml'
import type { StaticAlgorithmFrame } from '../types'
import { AI_OVERVIEW_SEEDS, learnerClusterPoints, qLearningEnvironment, regressionPresets } from '../data/experiments'
import { runKMeans } from '../utils/kmeans'
import { createQTable, evaluateGreedyPolicy, trainEpisodes } from '../utils/qLearning'
import { meanSquaredError, rankRegressionCandidates } from '../utils/regression'

const loc = (zhCN: string, en: string): LocalizedCopy => ({ 'zh-CN': zhCN, en })
const regressionSamples = regressionPresets['clear-trend'].samples
const regressionCandidates = [{ w: 4, b: 48 }, { w: 5, b: 48 }, { w: 6, b: 47 }, { w: 6.6, b: 45.8 }]
const rankedRegression = rankRegressionCandidates(regressionSamples, regressionCandidates)
const regressionStates = [regressionCandidates[0], regressionCandidates[1], regressionCandidates[2], rankedRegression[0]]

export const regressionFrames: StaticAlgorithmFrame[] = regressionStates.map((state, index) => ({
  id: ['initial', 'one-update', 'intermediate', 'converged'][index],
  title: [loc('初始直线', 'Initial line'), loc('一次候选更新', 'One candidate update'), loc('中间候选', 'Intermediate candidate'), loc('最佳候选', 'Best candidate')][index],
  explanation: loc('所有数值都由同一组回归工具计算。', 'Every value is computed by the shared regression utilities.'),
  values: { w: state.w, b: state.b, mse: Number(meanSquaredError(regressionSamples, state.w, state.b).toFixed(2)) },
}))

const kmeansResult = runKMeans(learnerClusterPoints, 3, AI_OVERVIEW_SEEDS.kmeans, 20)
const kmeansHistory = kmeansResult.history
const kmeansStates = [kmeansHistory[0], kmeansHistory[Math.min(2, kmeansHistory.length - 1)], kmeansHistory[Math.floor(kmeansHistory.length / 2)], kmeansHistory.at(-1)!]
export const kmeansFrames: StaticAlgorithmFrame[] = kmeansStates.map((state, index) => ({
  id: ['initial', 'one-update', 'intermediate', 'converged'][index],
  title: [loc('初始中心', 'Initial centers'), loc('一次完整更新', 'One complete update'), loc('中间迭代', 'Intermediate iteration'), loc('稳定分组', 'Converged grouping')][index],
  explanation: loc('阶段来自确定性的 K-means 历史记录。', 'The phase comes from deterministic K-means history.'),
  values: { iteration: state.iteration, phase: state.phase, distance: Number(state.withinGroupDistanceTotal.toFixed(1)) },
}))

const qTrainingCounts = [0, 1, 12, 40]
export const qLearningFrames: StaticAlgorithmFrame[] = qTrainingCounts.map((episodes, index) => {
  const qTable = episodes === 0
    ? createQTable(qLearningEnvironment)
    : trainEpisodes(qLearningEnvironment, { episodes, seed: AI_OVERVIEW_SEEDS.qLearning, explorationRate: 0.3, learningRate: 0.5, discountFactor: 0.9 }).qTable
  const evaluated = evaluateGreedyPolicy(qLearningEnvironment, qTable, 32)
  return {
    id: ['initial', 'one-update', 'intermediate', 'evaluated'][index],
    title: [loc('初始策略检查', 'Initial policy check'), loc('一次训练更新', 'One training update'), loc('中间训练', 'Intermediate training'), loc('贪心策略评估', 'Greedy policy evaluated')][index],
    explanation: loc('训练与评估均由确定性的 Q-learning 工具生成。', 'Training and evaluation are generated by the deterministic Q-learning utilities.'),
    values: { episodes, steps: evaluated.steps, reward: evaluated.cumulativeReward, reachedGoal: evaluated.reachedGoal ? 'yes' : 'no' },
  }
})

export const staticAlgorithmFrames = { regression: regressionFrames, kmeans: kmeansFrames, qLearning: qLearningFrames }
</script>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { aiOverviewVisualCopy } from '../data/course'

const props = defineProps<{ algorithm: 'regression' | 'kmeans' | 'qLearning' }>()
const { locale } = useI18n()
const frames = computed(() => staticAlgorithmFrames[props.algorithm])
if (frames.value.length !== 4) throw new Error('Static fallback frames.length === 4 is required')
</script>

<template>
  <section class="static-fallback" :aria-label="aiOverviewVisualCopy.staticFallback[locale as AppLocale]">
    <h3>{{ aiOverviewVisualCopy.staticFallback[locale as AppLocale] }}</h3>
    <ol>
      <li v-for="frame in frames.slice(0, 4)" :key="frame.id" :data-frame-id="frame.id">
        <strong>{{ frame.title[locale as AppLocale] }}</strong>
        <p>{{ frame.explanation[locale as AppLocale] }}</p>
        <dl><div v-for="(value, key) in frame.values" :key="key"><dt>{{ key }}</dt><dd>{{ value }}</dd></div></dl>
      </li>
    </ol>
  </section>
</template>

<style scoped>
.static-fallback ol { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:.75rem; padding:0; list-style:none; counter-reset:frame; }
.static-fallback li { padding:1rem; border:1px solid #cbded8; border-radius:.75rem; background:#f7fbfa; counter-increment:frame; }
.static-fallback li::before { content:counter(frame); display:inline-grid; place-items:center; width:1.5rem; height:1.5rem; margin-right:.4rem; border-radius:50%; color:white; background:#0f9f8f; }
dl { display:flex; flex-wrap:wrap; gap:.6rem; } dl div { min-width:5rem; } dt { color:#597069; } dd { margin:0; font-weight:800; }
@media (max-width:520px) { .static-fallback ol { grid-template-columns:1fr; } }
</style>
