async (page) => {
  page.setDefaultTimeout(15000)
  page.setDefaultNavigationTimeout(20000)
  const base = 'http://127.0.0.1:4173/ML_tutorial_Site'
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()) })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const visited = []
  for (const [locale, width] of [['zh-CN', 1280], ['en', 390]]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto(base + '/spine')
    await page.waitForLoadState('networkidle')
    await page.getByRole('button', { name: locale === 'en' ? 'EN' : '中', exact: true }).click()
    if (await page.locator('.textbook-unit').count() !== 1) throw new Error('Expected one expanded unit')
    if (await page.locator('.textbook-unit-tabs a').count() !== 6) throw new Error('Missing teaching unit')
    const first = page.locator('.textbook-reading-list a').first()
    const firstUrl = await first.evaluate(anchor => anchor.href)
    await first.click()
    await page.waitForURL(firstUrl)
    for (let i = 0; i < 33; i++) {
      await page.waitForLoadState('networkidle')
      const nav = page.locator('[data-testid="reading-navigation"]').first()
      await nav.waitFor()
      const current = await page.evaluate(() => ({ path: location.pathname, hash: location.hash }))
      if (current.path.includes('/python-notebook/')) {
        const chapter = current.path.split('/').pop()
        await page.locator(`[data-testid="python-data-tools-current-chapter"][data-section-id="${chapter}"]`).waitFor()
      } else if (current.hash) await page.locator(current.hash).waitFor()
      else await page.locator('.algorithm-view').waitFor()
      if (!page.url().includes('route=core-learning-path')) throw new Error('Route context lost: ' + page.url())
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)
      if (overflow) throw new Error('Horizontal overflow: ' + page.url())
      if (page.url().includes('/python-notebook/notebook-workflow')) await page.locator('.python-syntax-bridge').waitFor()
      visited.push({ url: page.url(), locale, width })
      const next = nav.locator('[data-testid="reading-next"]')
      const href = await next.getAttribute('href')
      if (page.url().includes('matplotlib-visualization') && !href.includes('splits-generalization')) throw new Error('Python entered optional chapters')
      const nextUrl = await next.evaluate(anchor => anchor.href)
      await next.click()
      await page.waitForURL(nextUrl)
    }
    await page.goto(base + '/learn/loss-functions/regression-losses?route=core-learning-path')
    await page.waitForLoadState('networkidle')
    const lossNext = await page.locator('[data-testid="reading-next"]').first().getAttribute('href')
    if (!lossNext.includes('calculus-derivatives-local-change')) throw new Error('Regression loss entered classification too early')
    await page.reload()
    await page.waitForLoadState('networkidle')
    if (await page.locator('[data-testid="reading-next"]').first().getAttribute('href') !== lossNext) throw new Error('Refresh changed next lesson')
    await page.goto(base + '/python/seaborn-statistics?route=invalid')
    await page.waitForLoadState('networkidle')
    if (await page.locator('[data-testid="reading-navigation"]').count()) throw new Error('Invalid route did not fall back')
    await page.goto(base + '/spine#stage-data-to-features')
    await page.waitForLoadState('networkidle')
    if (await page.locator('#unit-2').count() !== 1) throw new Error('Legacy spine anchor lost')
    await page.keyboard.press('Tab')
  }
  if (errors.length) throw new Error(errors.join('\n'))
  await page.screenshot({ path: '/tmp/ml-atlas-route-mobile.png', fullPage: false })
  return { passed: visited.length, locales: ['zh-CN', 'en'], viewports: [1280, 390], handoffs: 'continuous through units 1–2' }
}
