import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const lessons = [
  { key: 'vectors', chineseFile: '02-vectors-samples.zh-CN.md', englishFile: '02-vectors-samples.en.md', expectedSections: 12 },
  { key: 'matrices', chineseFile: '03-matrices-batches.zh-CN.md', englishFile: '03-matrices-batches.en.md', expectedSections: 12 },
  { key: 'derivatives', chineseFile: '04-derivatives-error.zh-CN.md', englishFile: '04-derivatives-error.en.md', expectedSections: 12 },
  { key: 'numpy', chineseFile: '05-numpy-implementation.zh-CN.md', englishFile: '05-numpy-implementation.en.md', expectedSections: 12 },
  { key: 'studio', chineseFile: '06-guided-studio.zh-CN.md', englishFile: '06-guided-studio.en.md', expectedSections: 9 },
]

function parseMaster(file) {
  const source = readFileSync(new URL(`../docs/curriculum/v3/math-to-code/${file}`, import.meta.url), 'utf8')
  const matches = [...source.matchAll(/^##\s+(.+?)\s+\{#([a-z0-9-]+)\}\s*$/gm)]
  return matches.map((match, index) => ({
    originalId: match[2],
    title: match[1],
    content: source.slice(match.index + match[0].length, matches[index + 1]?.index ?? source.length).trim(),
  }))
}

const generated = Object.fromEntries(lessons.map((lesson) => {
  const chinese = parseMaster(lesson.chineseFile)
  const english = parseMaster(lesson.englishFile)
  if (chinese.length !== lesson.expectedSections || english.length !== lesson.expectedSections) {
    throw new Error(`${lesson.key} must contain ${lesson.expectedSections} localized sections`)
  }
  if (english.some((section, index) => section.originalId !== chinese[index]?.originalId)) {
    throw new Error(`${lesson.key} localized section IDs must match`)
  }
  return [lesson.key, chinese.map((section, index) => ({
    ...section,
    enTitle: english[index].title,
    en: english[index].content,
  }))]
}))

const output = `// Generated by scripts/generateMathToCodeRuntimeContent.mjs. Do not edit by hand.\n` +
  `export interface RuntimeLessonSection { readonly originalId: string; readonly title: string; readonly content: string; readonly enTitle: string; readonly en: string }\n` +
  `export const runtimeLessonContent = ${JSON.stringify(generated, null, 2)} as const satisfies Record<string, readonly RuntimeLessonSection[]>\n`

const targetIndex = process.argv.indexOf('--target')
const targetUrl = targetIndex >= 0
  ? resolve(process.cwd(), process.argv[targetIndex + 1] ?? '')
  : new URL('../src/modules/math-lab/data/mathToCode/runtimeLessonContent.generated.ts', import.meta.url)

if (process.argv.includes('--check')) {
  const current = readFileSync(targetUrl, 'utf8')
  if (current !== output) {
    console.error('runtimeLessonContent.generated.ts is out of date; run node scripts/generateMathToCodeRuntimeContent.mjs')
    process.exitCode = 1
  } else {
    console.log('runtimeLessonContent.generated.ts is up to date')
  }
} else {
  writeFileSync(targetUrl, output)
}
