import { readFileSync, writeFileSync } from 'node:fs'

const lessons = [
  {
    key: 'vectors', file: '02-vectors-samples.zh-CN.md',
    english: [
      `The previous lesson treated \`x = [2, 3]\` as an ordered list: two base tasks and three hint requests. This lesson asks why those values may be handled as one sample vector, what changes when their order changes, and why \`[4, -1] * [2, 3]\` is not yet a prediction. A representation contract fixes the meaning of every position, the dimension, the pairing rule, and the required scalar output. In the prediction task, \`w\` is not another geometric sample. It is a unit-bearing linear functional: 4 minutes/base task and -1 minute/hint request. We reserve Euclidean length, angle, and projection for a separate dimensionless geometry example. Before calculating, predict the unit of \`w^T x\` and explain which values are data and which are model parameters. The exercises are formative, not graded.`,
      `Three prior ideas are enough. Lists are ordered, so index 0 remains base-task count and index 1 remains hint-request count. A coordinate pair can be drawn as an arrow, but the drawing does not change its data meaning. Error is computed only after prediction: $L=(\\hat y-y)^2$, so $\\hat y=10$ and $y=9$ give $L=1$. Also separate scalars from vectors: 5, 9, and 10 are scalars, while [2,3] and [4,-1] have shape (2,). Shape counts positions; a Euclidean norm is a different quantity and only has a direct geometric interpretation when coordinate units and scales are compatible.`,
      `The shared vocabulary is fixed: \`x = [2, 3]\` is one sample with shape (2,), \`w = [4, -1]\` is a coefficient rule with shape (2,), \`b = 5\` is a scalar bias, \`y_hat = 10\` is the predicted duration, \`y = 9\` is the observed target, and \`L = 1\` is squared error. The compact contract is \`y_hat = w^T x + b\`. Here $w$ is a **unit-bearing linear functional**, not a geometric arrow: $w_1$ has minutes/base-task units and $w_2$ has minutes/hint-request units. Pairing and summing produce minutes. Target $y$ never enters the forward calculation; it appears only in the later comparison.`,
      `Read $w$ as a conversion rule. The first coordinate converts 2 base tasks through 4 minutes/base task into +8 minutes. The second converts 3 hint requests through -1 minute/request into -3 minutes. Compatible minute contributions can be summed to 5, and bias adds another 5. Thus the main-line map is $x\\mapsto w^T x$, a vector-to-scalar linear functional. The affine prediction adds $b$. Increasing only $x_1$ by one changes the weighted contribution by +4 minutes; increasing only $x_2$ by one changes it by -1 minute. These signed effects require no angle story. Bias is added after aggregation and is not a hidden feature contribution.`,
      `For $x,w\\in\\mathbb R^d$, $w^T x=\\sum_{j=1}^d w_jx_j\\in\\mathbb R$. Both inputs need the same dimension; [2,3,1] and [4,-1] are an invalid contract and must not be truncated or padded silently. With fixed $w$, $f_w(x)=w^Tx$ preserves addition and scalar multiplication; adding $b$ makes the map affine. Coordinate order is part of the interface. A common permutation of x and w preserves the value, but permuting only x changes both semantics and result. Scaling a feature unit requires the reciprocal coefficient scaling. NumPy shapes (2,), (1,2), and (2,1) contain similar numbers but expose different interfaces. A checked loop is the transparent baseline for \`@\`, and finite-value checks reject NaN or Infinity before they contaminate prediction and loss.`,
      `Worked example one expands every contribution: \`w^T x = 4*2 + (-1)*3 = 5\`; then \`y_hat = 5 + 5 = 10\`; finally \`L = (10 - 9)^2 = 1\`. The contribution ledger records feature 2, weight 4, contribution 8; feature 3, weight -1, contribution -3; total 5. The elementwise result [8,-3] still has shape (2,), so it cannot be the promised scalar prediction. Summing changes the shape contract to a scalar, bias preserves it, and target is revealed only afterward. This staged calculation localizes order, sign, reduction, bias, and target-leakage bugs.`,
      `Worked example two is deliberately independent and dimensionless. On a same-scale grid let \`u = [3, 4]\` and \`v = [4, 0]\`. Then $\\|u\\|=5$, $\\|v\\|=4$, $u^Tv=12$, and $\\operatorname{proj}_v(u)=(12/16)[4,0]=[3,0]$. The remainder [0,4] is orthogonal to v, and cosine is 0.6. Length, angle, and projection are meaningful because both coordinates share compatible dimensionless units and scale. This auxiliary geometry must never be used to claim that the prediction coefficients w—with minutes-per-feature units—form an ordinary spatial arrow.`,
      `The checked implementation creates finite NumPy arrays \`x = np.array([2.0, 3.0])\` and \`w = np.array([4.0, -1.0])\`, asserts \`x.shape == w.shape == (2,)\`, computes \`contributions = w * x\`, \`weighted_sum = w @ x\`, \`y_hat = weighted_sum + b\`, and \`L = (y_hat - y) ** 2\`. Expected outputs are [8,-3], 5.0, 10.0, and 1.0. The transparent loop and NumPy route should agree. Explicitly reject mismatched dimensions and non-finite inputs; Python \`zip\` alone is unsafe because it silently truncates the longer sequence. Geometry variables remain u and v and never replace x and w.`,
      `Controlled experiment: hold x=[2,3], b=5, and y=9 fixed. Compare w=[4,-1], [8,-2], [-4,1], and [3,-1]. Their dot products are 5, 10, -5, and 3; predictions are 10, 15, 0, and 8; squared errors are 1, 36, 81, and 1. Change one operation per run and record changed factor, fixed factors, dot product, prediction, target, and loss. A larger coefficient or prediction is not automatically better. Formative feedback checks that bias stayed +5, only the intended coordinate changed, and the explanation uses units and contributions rather than arrow length or color.`,
      `Four diagnoses protect the contract. Dimension is not Euclidean norm: u=[3,4] has dimension 2 and norm 5. Elementwise multiplication is not a dot product: w*x is [8,-3], whereas w@x is scalar 5. Prediction coefficients are not automatically geometric directions because their coordinates carry different units. Matching lengths do not prove matching meaning: swapped feature columns can still execute while pairing the wrong semantics. For every failure, state why it seems plausible, inspect the concrete shape/value/unit symptom, restate the correct model, and repair with a schema ledger, finite checks, explicit reduction, and a minimal counterexample.`,
      `### Layer one: representation\n\nExercise 1A Explain why [2,3] and [3,2] are different samples.\n\nHint: Write the index-to-meaning ledger.\n\nReference reasoning: Values share a multiset but not ordered semantics; weights must follow the same permutation. [Review](#vectors-shared-task)\n\nExercise 1B Distinguish dimension from norm.\n\nHint: Use dimensionless u=[3,4].\n\nReference reasoning: It has two coordinates and norm five. [Review](#vectors-worked-auxiliary)\n\nExercise 1C Explain why w is not a main-line arrow.\n\nHint: Inspect units.\n\nReference reasoning: w is a unit-bearing linear functional mapping x to minutes. [Review](#vectors-intuition)\n\n### Layer two: calculation\n\nExercise 2A Recompute prediction after swapping only x.\n\nHint: Preserve w and b.\n\nReference reasoning: 4*3-1*2+5=15, exposing semantic misalignment. [Review](#vectors-formal)\n\nExercise 2B Diagnose output [8,-3].\n\nHint: Check required output shape.\n\nReference reasoning: Contributions still require sum and bias. [Review](#vectors-code)\n\nExercise 2C Project u=[3,4] onto v=[4,0].\n\nHint: Use $(u^Tv/v^Tv)v$.\n\nReference reasoning: The projection is [3,0]. [Review](#vectors-worked-auxiliary)\n\n### Layer three: observation\n\nExercise 3A Compare w and 2w.\n\nHint: Bias does not scale.\n\nReference reasoning: Dot product doubles, but affine prediction does not double. [Review](#vectors-experiment)\n\nExercise 3B Design a finite-value failure.\n\nHint: Insert NaN into x.\n\nReference reasoning: Reject before multiplication so loss stays interpretable. [Review](#vectors-code)\n\nExercise 3C Create a schema-debug log.\n\nHint: Include names, units, shapes, and contributions.\n\nReference reasoning: The log distinguishes shape correctness from semantic correctness. [Review](#vectors-formal)`,
      `The lesson leaves a stable matrix handoff. One sample is an ordered vector; w is a unit-bearing linear functional; only dimensionless same-scale u and v support the geometry example. The shared calculation remains \`w^T x = 4*2 + (-1)*3 = 5\`, \`y_hat = 10\`, and \`L = 1\`. The next lesson stacks samples into \`X = [[2, 3], [1, 4]]\` with shape (2,2), keeps \`w = [4, -1]\` and \`b = 5\`, and expects predictions [10,5] for targets [9,7]. Adding a third row must not alter earlier forward results. Carry forward the feature-order ledger, shape checks, finite checks, and the rule that target enters only after prediction.`,
    ],
  },
  {
    key: 'matrices', file: '03-matrices-batches.zh-CN.md',
    english: [
      `Two samples could be predicted by copying the same dot-product code twice, but duplication hides the shared structure. Stack rows into \`X = [[2, 3], [1, 4]]\`; rows are samples and columns are features. The opening prediction asks which axis is preserved by \`X @ w\`, why adding a row should not change existing rows, and how a program can run while its batch semantics are wrong. The lesson uses a complete shape ledger, a transparent nested-loop baseline, and a vectorized implementation. A separate grid-mirror example explains a transformation matrix without confusing it with the data matrix X. Exercises remain formative and not graded.`,
      `Recall that one row x has shape (2,), w has shape (2,), and w^T x is scalar. A matrix is not merely a nested list: its two axes have named roles. In this course X uses rows for samples and columns for features. Reading row i holds the sample fixed while reading column j follows one feature across samples. Bias b is scalar and broadcasts to each sample prediction; target y is now a length-n vector used after prediction. The vector result [10,5] should reproduce each independently checked scalar calculation.`,
      `The shared shape ledger is \`X: (2,2)\`, \`w: (2,)\`, \`X @ w: (2,)\`, scalar \`b\`, \`y_hat: (2,)\`, and \`y: (2,)\`. In compact form \`y_hat = Xw+b\`. The contraction is \`(Xw)_i = sum_j X_ij w_j\`: feature axis j disappears after pairing with w, while sample axis i remains. For the first row, 4*2-1*3+5=10; for the second, 4*1-1*4+5=5. Targets [9,7] produce residuals [1,-2], squares [1,4], and MSE 2.5.`,
      `Think of X as a labeled table passing through one shared prediction pipeline. Each row follows the same coefficient rule; vectorization changes execution expression, not the mathematics. Adding one row adds one output. Adding or reordering a feature column requires the corresponding w entry to be added or reordered. A matrix used as a geometric transformation plays a different role: its columns say where basis directions land. Always determine a matrix role from provenance, axes, formula position, and output shape rather than from the fact that it is two-dimensional.`,
      `For $X\\in\\mathbb R^{n\\times d}$ and $w\\in\\mathbb R^d$, $Xw\\in\\mathbb R^n$. The inner d dimensions must agree. This is the concrete contract \`(2,2) @ (2,) -> (2,)\`. Adding scalar b broadcasts one value across n predictions; adding a vector of shape (n,) can mean sample-specific offsets but is a different model. MSE is $L=(1/n)\\sum_i(\\hat y_i-y_i)^2$. Axis 0 traverses samples and axis 1 traverses features. Silent broadcasting can create an (n,n) residual matrix when (n,1) predictions meet (n,) targets, so exact assertions are required before subtraction.`,
      `Worked batch prediction expands all shapes and values. X rows [2,3] and [1,4] pair with w=[4,-1]. The contribution matrix is [[8,-3],[4,-4]] with shape (2,2). Reducing across axis 1 yields weighted sums [5,0] with shape (2,). Adding scalar b=5 yields predictions [10,5]. Comparing with targets [9,7] gives residuals [1,-2], squared errors [1,4], and MSE 2.5. A row-by-row loop must reproduce the same values. If it returns only one scalar, the sample axis was collapsed; if it returns a 2x2 array, reduction or broadcasting is wrong.`,
      `The independent geometry example mirrors grid points with \`A = [[1, 0], [0, -1]]\`. With points stored as rows, \`P @ A.T\` maps (u,v) to (u,-v). The four corners [[1,1],[-1,1],[-1,-1],[1,-1]] become [[1,-1],[-1,-1],[-1,1],[1,1]]. A encodes a coordinate transform, whereas X encodes sample rows. A's columns describe transformed basis vectors; X's columns describe feature fields. Declaring the row-vector convention prevents the common silent switch between PA^T and AP.`,
      `A safe NumPy implementation converts X, w, and targets to floating arrays; requires X.ndim==2, w.ndim==1, targets.ndim==1; requires X.shape[1]==w.shape[0] and X.shape[0]==targets.shape[0]; and rejects non-finite values. It computes \`contributions = X * w\`, \`loop_predictions\` with nested sample/feature loops, \`predictions = X @ w + b\`, then asserts vectorized and loop outputs agree. Residual and MSE follow only after shapes match exactly. Print every intermediate shape. Broadcasting is permitted only when its intended axis is explicitly documented.`,
      `Controlled experiment: first append only row [3,2]. X changes from (2,2) to (3,2), predictions become [10,5,15], and the original two results stay unchanged. In a separate run swap the first two rows and swap targets in the same way; predictions and residuals reorder but their values and MSE are preserved. In another separate run swap feature columns and w together; predictions are preserved. Formative feedback asks which axis changed, which companion arrays had to change, and which output should stay fixed or merely reorder. Changing several axes in one run destroys attribution.`,
      `Four legal-looking failures matter. Transposing X changes the sample/feature interpretation even if a square example still runs. Elementwise X*w produces contributions, not reduced predictions. A (n,1) prediction minus (n,) target broadcasts into (n,n), creating pairwise differences rather than aligned residuals. Reordering rows without targets corrupts supervision while every shape remains valid. Diagnose each with named axes, exact shape assertions, a transparent row oracle, and a nonsquare or unequal-value counterexample. “NumPy did not raise” is execution evidence, not semantic evidence.`,
      `### Layer one: shape\n\nExercise 1A Label both axes of X.\n\nHint: Rows are samples.\n\nReference reasoning: Axis 0 indexes samples and axis 1 indexes features. [Review](#matrices-shared-task)\n\nExercise 1B Predict the output shape.\n\nHint: Track the contracted d axis.\n\nReference reasoning: (n,d)@(d,) leaves (n,). [Review](#matrices-formal)\n\nExercise 1C Distinguish X from A.\n\nHint: Ask what rows and columns mean.\n\nReference reasoning: X stores samples; A defines a coordinate transform. [Review](#matrices-worked-auxiliary)\n\n### Layer two: calculation\n\nExercise 2A Compute the second row.\n\nHint: 4*1-1*4.\n\nReference reasoning: Weighted sum 0 and prediction 5. [Review](#matrices-worked-shared)\n\nExercise 2B Compute MSE.\n\nHint: Average [1,4].\n\nReference reasoning: MSE is 2.5. [Review](#matrices-worked-shared)\n\nExercise 2C Diagnose an (n,n) residual.\n\nHint: Compare (n,1) with (n,).\n\nReference reasoning: Broadcasting formed pairwise rather than aligned differences. [Review](#matrices-code)\n\n### Layer three: observation\n\nExercise 3A Append one row.\n\nHint: Keep w and old rows fixed.\n\nReference reasoning: Only one new prediction appears. [Review](#matrices-experiment)\n\nExercise 3B Permute rows safely.\n\nHint: Move targets together.\n\nReference reasoning: Predictions and residuals reorder; MSE stays fixed. [Review](#matrices-experiment)\n\nExercise 3C Build a nonsquare debug case.\n\nHint: Use n=3,d=2.\n\nReference reasoning: It exposes accidental transposes hidden by square data. [Review](#matrices-formal)`,
      `The matrix lesson hands the derivative lesson a verified batch: X=[[2,3],[1,4]], w=[4,-1], b=5, predictions=[10,5], targets=[9,7], residuals=[1,-2], and MSE=2.5. Every array has an explicit role and shape. The derivative lesson will hold X and targets fixed, treat the scalar batch loss as a function of one probed parameter at a time, and estimate local sensitivity. It must not confuse estimating a derivative with taking a gradient-descent update. Preserve the loop oracle, exact finite checks, and the requirement that targets reorder with samples.`,
    ],
  },
  {
    key: 'derivatives', file: '04-derivatives-error.zh-CN.md',
    english: [
      `The verified batch has MSE 2.5, but that single value does not say how loss changes near the current parameters. The opening question asks: if one parameter moves slightly while X, targets, and all other parameters stay fixed, does loss rise, fall, or stay locally flat? We will compare symmetric nearby evaluations rather than update the model. A central-difference estimate is a measurement of local sensitivity; it is **not gradient descent**. The lesson connects average change, derivatives, partial derivatives, finite-step failure, and a separate motion example. Exercises are formative and not graded.`,
      `Average rate compares two separated points: [F(theta+h)-F(theta)]/h. MSE summarizes residual squares for the fixed batch. A controlled experiment changes one factor while fixing the rest. Derivatives combine these ideas by shrinking a local observation window. The current prediction chain remains x,w,b -> y_hat, followed by y_hat,y -> L. A derivative does not feed target into prediction; it repeatedly evaluates the same valid loss function at neighboring parameter values.`,
      `Define $L(w,b)=\\operatorname{MSE}(Xw+b,y)$ for fixed X and y. At w=[4,-1], b=5, predictions are [10,5] and L=2.5. To probe $w_1$, make a copied parameter vector, change only coordinate 0, recompute predictions and loss, and restore the baseline for every evaluation. Repeat independently for $w_2$ and b. The local sensitivities are approximately [0,-5] for w and -1 for b. These numbers describe slope at the current state; they are not new weights and do not by themselves choose a step size.`,
      `A derivative is the slope of a local linear approximation. On a motion graph it reads velocity near one time; on a loss landscape it reads how loss responds near one parameter value. Positive sensitivity means increasing that parameter slightly tends to increase loss; negative means increasing it slightly tends to decrease loss; near zero means locally flat along that coordinate. None is a global guarantee. A curve can turn, a nonsmooth point can lack one derivative, and a step far outside the local neighborhood can contradict the tangent prediction.`,
      `The derivative is $F'(theta)=lim_{h->0}[F(theta+h)-F(theta)]/h$. For numerical work, central difference is $[L(\\theta+h)-L(\\theta-h)]/(2h)$. It cancels more first-order asymmetry than a one-sided estimate. A partial derivative varies one coordinate and fixes all others. Step h must be positive and finite; too large measures a broad secant, while too small can lose significant digits through subtraction. The function outputs must be finite. Estimation and optimization remain separate APIs: central difference returns a slope; gradient descent would additionally choose eta and update theta, which this lesson does not do.`,
      `Worked example one evaluates the fixed batch around each parameter with h=1e-4. The analytic MSE derivatives are dL/dw_j=(2/n) sum_i residual_i X_ij and dL/db=(2/n)sum_i residual_i. With residuals [1,-2], X columns [2,1] and [3,4], dL/dw1 = 1*2 + (-2)*1 = 0; dL/dw2 = 1*3 + (-2)*4 = -5; dL/db = 1 + (-2) = -1. Central difference should reproduce approximately \`[0, -5, -1]\`. Agreement checks implementation; it does not perform an update.`,
      `The independent motion example uses $s(t)=2+3t$. Between t-h and t+h, central difference is [(2+3(t+h))-(2+3(t-h))]/(2h)=3 for every positive h. Its derivative is 3 meters/second. A quadratic motion curve would make shrinking h more visible, but the linear example establishes units and the distinction between position and velocity cleanly. This t/s example is separate from the loss parameter probe and never changes w, b, predictions, or targets.`,
      `Implementation wraps the quantity being probed in a one-argument function. \`loss_for_w1(value)\` copies w, replaces index 0, calls the checked batch predictor, and returns MSE. The reusable \`central_difference(fn, value, step)\` validates finite value and positive finite step, evaluates fn(value+step) and fn(value-step), validates both outputs and the quotient, and returns their difference divided by 2*step. Copies prevent mutation leaking between plus and minus evaluations. Print L+, L-, numerator, denominator, and estimate when debugging.`,
      `Controlled experiment: keep X, y, baseline parameters, and derivative formula fixed; vary only h through 1, 0.1, 0.01, 1e-4, and a very tiny value. Record L(theta+h), L(theta-h), numerator, denominator, and estimate. A stable middle range should approach the analytic sensitivity; a broad window can bias a nonlinear loss, and an extremely tiny window can show floating-point noise. Formative feedback asks whether only h changed, whether each evaluation started from a fresh copy, and whether the conclusion reports stability rather than declaring the smallest h automatically best.`,
      `Four boundary errors recur. A finite difference is not gradient descent: it measures slope but does not update parameters. A derivative is local, not a promise about the whole curve. Smaller h is not always more accurate because cancellation and rounding eventually dominate. Mutating one shared weight array means the minus evaluation may start from the plus state, invalidating symmetry. Repair by separating estimator and updater names, sweeping h, comparing an analytic case, copying parameter arrays, and logging both neighbor losses. At kinks such as absolute value at zero, report the nonsmooth boundary instead of inventing one stable derivative.`,
      `### Layer one: meaning\n\nExercise 1A Interpret a negative derivative.\n\nHint: Describe a tiny positive parameter move.\n\nReference reasoning: Loss tends to decrease locally, not necessarily globally. [Review](#derivatives-intuition)\n\nExercise 1B Separate estimation and update.\n\nHint: Look for eta.\n\nReference reasoning: Central difference estimates slope; gradient descent also chooses a learning rate and changes theta. [Review](#derivatives-formal)\n\nExercise 1C State fixed quantities for dL/dw2.\n\nHint: Hold X,y,w1,b fixed.\n\nReference reasoning: Only w2 varies in the partial derivative. [Review](#derivatives-shared-task)\n\n### Layer two: calculation\n\nExercise 2A Derive dL/dw1.\n\nHint: Pair residuals with column 1.\n\nReference reasoning: 1*2-2*1=0. [Review](#derivatives-worked-shared)\n\nExercise 2B Derive dL/db.\n\nHint: Bias derivative is one per sample.\n\nReference reasoning: 1-2=-1. [Review](#derivatives-worked-shared)\n\nExercise 2C Evaluate the motion slope.\n\nHint: Expand s(t+h) and s(t-h).\n\nReference reasoning: The quotient is exactly 3. [Review](#derivatives-worked-auxiliary)\n\n### Layer three: experiment\n\nExercise 3A Sweep h.\n\nHint: Log both neighbor losses.\n\nReference reasoning: Seek a stable range, not the smallest representable number. [Review](#derivatives-experiment)\n\nExercise 3B Create a mutation bug.\n\nHint: Reuse one array.\n\nReference reasoning: The asymmetric state proves why copies are required. [Review](#derivatives-code)\n\nExercise 3C Probe absolute value at zero.\n\nHint: Compare left and right slopes.\n\nReference reasoning: Opposite one-sided slopes reveal nonsmoothness. [Review](#derivatives-misconceptions)`,
      `The NumPy handoff contains a fully auditable derivative contract: fixed X=[[2,3],[1,4]], targets [9,7], baseline w=[4,-1], b=5, predictions [10,5], MSE 2.5, central-difference sensitivities approximately w=[0,-5] and b=-1, and a documented h sweep. The next lesson must reproduce these outputs with array shape and finite checks, fresh copies for perturbations, and real failure messages. It must retain the sentence that central difference is not gradient descent and must not introduce a learning-rate update into this measurement task.`,
    ],
  },
  {
    key: 'numpy', file: '05-numpy-implementation.zh-CN.md',
    english: [
      `A one-line NumPy expression can execute and still compute the wrong object. Broadcasting, accidental transposes, integer dtype, mutation, or non-finite values may all produce legal arrays with invalid lesson semantics. This lesson turns the previous mathematics into a safe numerical contract: values, roles, shapes, dtypes, axes, finite checks, expected outputs, and failure messages are all observable. The shared batch must reproduce predictions [10,5], MSE 2.5, and central-difference sensitivities [0,-5,-1]. A separate sensor-grid example practices axis debugging. Exercises are formative and not graded.`,
      `The scalar, vector, matrix, and derivative contracts now join one pipeline. x has shape (d,), X has shape (n,d), w has shape (d,), predictions and targets have shape (n,), and MSE is scalar. \`*\` is elementwise, \`@\` contracts the shared feature axis, and a scalar bias broadcasts across samples. Target comparison happens after prediction. Central difference calls the loss with copied perturbed parameters and returns sensitivity, not an updated model. NumPy should make these contracts shorter to express, never less explicit to verify.`,
      `Names map one-to-one to mathematics: \`X\` is the sample matrix, \`w\` is the coefficient vector, \`b\` is scalar bias, \`predictions = X @ w + b\`, \`residuals = predictions - targets\`, \`squared_errors = residuals ** 2\`, and \`MSE = squared_errors.mean()\`. With X=[[2,3],[1,4]], w=[4,-1], b=5, and targets=[9,7], the expected values are weighted sums [5,0], predictions [10,5], residuals [1,-2], squares [1,4], and MSE 2.5. Every name preserves the course vocabulary rather than hiding several stages in an anonymous expression.`,
      `Treat shape as a runtime type description. It tells how many axes exist and what each axis is expected to mean. Shape alone is necessary but insufficient: a (2,2) transpose can keep the same dimensions while swapping semantic roles, and two (2,) arrays can refer to samples versus features. Therefore checks pair shapes with an axis ledger and known-value oracles. Intermediate arrays are not clutter: they make contribution, reduction, broadcasting, residual alignment, and failure localization visible. Compactness is earned only after equivalence has been demonstrated.`,
      `Convert with \`np.asarray(value, dtype=float)\` and validate dimensions before arithmetic. Require X.ndim==2, w.ndim==1, targets.ndim==1, X.shape[1]==w.shape[0], X.shape[0]==targets.shape[0], scalar finite b, and \`np.isfinite(...).all()\`. Broadcasting follows trailing-axis compatibility; it is not aware of “sample” or “target” meaning. Reductions must name the intended axis: contribution sums use axis 1, dataset MSE reduces all aligned sample errors to a scalar. Never use reshape merely to silence an exception without first stating the target semantic shape.`,
      `Worked example one reproduces Task 1 exactly. After validation, \`weighted_sums = X @ w\` gives [5.0,0.0], \`predictions = weighted_sums + b\` gives \`predictions = [10.0, 5.0]\`, residuals are [1.0,-2.0], squared errors are [1.0,4.0], and \`MSE = 2.5\`. A checked nested-loop oracle computes the same values. The derivative wrapper copies w for each perturbation and obtains approximately [0.0,-5.0] with bias sensitivity -1.0. Assertions use tolerances for finite differences, but exact shapes and finite status remain non-negotiable.`,
      `The independent sensor example starts with a 2x3 grid: two timestamps and three sensors. Per-sensor means reduce axis 0 and have shape (3,); per-timestamp means reduce axis 1 and have shape (2,). Subtracting the wrong mean may fail or broadcast along an unintended axis. Label rows and columns before calculating, then verify one value by hand. Transposing the grid changes its semantic convention even when all six values remain. This example teaches axis selection without borrowing prediction variables or targets.`,
      `The complete implementation defines validators, \`predict_batch_checked\`, \`mse_checked\`, and a side-effect-free \`central_difference\`. It calls \`np.asarray(..., dtype=float)\`, checks exact dimensions and compatible lengths, rejects empty batches, NaN, Infinity, nonpositive h, and non-finite function results, then returns fresh arrays or scalars. Expected failure includes \`ValueError\` for X.shape (2,3) with w.shape (2,), for a target length mismatch, and for non-finite input. Real output text documents shapes and values, not only “success.”`,
      `Controlled experiment compares a transparent nested-loop implementation with \`X @ w + b\` while holding all inputs fixed. First compare values and shape on the two-row baseline; then add a third row and compare again. The vectorized route may be more compact or faster, but output equality is the success criterion. Formative feedback asks for both results, an \`allclose\` assertion, named shapes, and a description of what changed in execution versus what stayed mathematically identical. Timing, if measured, uses repeated runs and is secondary to correctness.`,
      `Four “legal errors” deserve explicit tests. Broadcasting (n,1) predictions against (n,) targets creates an (n,n) matrix. Integer arrays can truncate an in-place floating update. A view can mutate its parent array and contaminate the minus perturbation. NaN can propagate without raising and make every later metric meaningless. Repair with exact shape assertions, float conversion, copies at mutation boundaries, finite checks before and after key operations, and small known-output tests. A raised \`ValueError\` is part of the safe contract, not an inconvenience to suppress.`,
      `### Layer one: read shapes\n\nExercise 1A Predict X@w shape.\n\nHint: Contract the feature axis.\n\nReference reasoning: (n,d)@(d,) returns (n,). [Review](#numpy-shared-task)\n\nExercise 1B Choose the sensor mean axis.\n\nHint: Preserve sensors.\n\nReference reasoning: Reducing axis 0 returns one mean per sensor. [Review](#numpy-worked-auxiliary)\n\nExercise 1C Explain why shape is not full semantics.\n\nHint: Consider a square transpose.\n\nReference reasoning: Dimensions can match while axis roles are swapped. [Review](#numpy-intuition)\n\n### Layer two: reproduce\n\nExercise 2A Compute predictions.\n\nHint: First compute [5,0].\n\nReference reasoning: Adding b gives [10,5]. [Review](#numpy-worked-shared)\n\nExercise 2B Compute MSE.\n\nHint: Residuals are [1,-2].\n\nReference reasoning: Mean of [1,4] is 2.5. [Review](#numpy-worked-shared)\n\nExercise 2C Trigger a shape failure.\n\nHint: Give X three columns and w two values.\n\nReference reasoning: Validation raises ValueError before matmul. [Review](#numpy-code)\n\n### Layer three: debug\n\nExercise 3A Compare loop and vectorized paths.\n\nHint: Use allclose and exact shapes.\n\nReference reasoning: Execution differs while mathematical output stays equal. [Review](#numpy-experiment)\n\nExercise 3B Expose a broadcasting bug.\n\nHint: Subtract (n,) from (n,1).\n\nReference reasoning: The unexpected (n,n) result reveals pairwise differences. [Review](#numpy-misconceptions)\n\nExercise 3C Protect finite difference from mutation.\n\nHint: Copy each candidate parameter array.\n\nReference reasoning: Independent plus/minus states preserve symmetry. [Review](#numpy-code)`,
      `This lesson hands a reproducible artifact to the guided studio: checked float arrays, exact axis semantics, predictions [10,5], targets [9,7], residuals [1,-2], MSE 2.5, numerical sensitivities [0,-5,-1], loop/vectorized equivalence, and real ValueError examples for bad shapes and non-finite input. The studio can now assemble these stages without changing vocabulary or hiding intermediate values. Formal Project 1 still follows Gradient Descent and Monte Carlo; this pilot handoff remains local formative practice and creates no new evidence-persistence path.`,
    ],
  },
]

function parseChinese(file) {
  const source = readFileSync(new URL(`../docs/curriculum/v3/math-to-code/${file}`, import.meta.url), 'utf8')
  const matches = [...source.matchAll(/^##\s+(.+?)\s+\{#([a-z0-9-]+)\}\s*$/gm)]
  return matches.map((match, index) => ({
    originalId: match[2],
    title: match[1],
    content: source.slice(match.index + match[0].length, matches[index + 1]?.index ?? source.length).trim(),
  }))
}

const generated = Object.fromEntries(lessons.map((lesson) => {
  const chinese = parseChinese(lesson.file)
  if (chinese.length !== 12 || lesson.english.length !== 12) throw new Error(`${lesson.key} must contain 12 localized sections`)
  return [lesson.key, chinese.map((section, index) => ({ ...section, en: lesson.english[index] }))]
}))

const output = `// Generated by scripts/generateMathToCodeRuntimeContent.mjs. Do not edit by hand.\n` +
  `export interface RuntimeLessonSection { readonly originalId: string; readonly title: string; readonly content: string; readonly en: string }\n` +
  `export const runtimeLessonContent = ${JSON.stringify(generated, null, 2)} as const satisfies Record<string, readonly RuntimeLessonSection[]>\n`

writeFileSync(new URL('../src/modules/math-lab/data/mathToCode/runtimeLessonContent.generated.ts', import.meta.url), output)
